# Uncomment to use the desired platform
PLATFORM = stm32

EXAMPLE ?= basic

include ../../tools/scripts/generic_variables.mk

include ../../tools/scripts/examples.mk

include src.mk

include ../../tools/scripts/generic.mk
