CONFIG_UART=y
CONFIG_IRQ=y
CONFIG_TIMER=y
CONFIG_IIO=y
CONFIG_ADC=y
CONFIG_ADC_DEMO=y
CONFIG_ADC_IIO_DEMO=y
CONFIG_DAC=y
CONFIG_DAC_DEMO=y
CONFIG_DAC_IIO_DEMO=y
CONFIG_IIO_DEMO_IIO_SW_TRIGGER_EXAMPLE=y
