# Uncomment to use the desired platform
# PLATFORM = xilinx
# PLATFORM = altera
# PLATFORM = aducm3029
# PLATFORM = stm32
# PLATFORM = linux

# Select the example you want to enable by chossing y for enabling and n for disabling
IIO_EXAMPLE = y
IIO_TRIGGER_EXAMPLE = n


include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
