# Uncomment to use the desired platform
# PLATFORM = xilinx
# PLATFORM = altera
# PLATFORM = aducm3029

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
