## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/fmcomms2/zcu102/fmcomms2_zcu102.sdk/system_top.hdf

include $(NOOS-DIR)/fmcomms2/fmcomms2.mk
include $(NOOS-DIR)/scripts/zynq_u.mk

