# To choose the example at compile time, build with `make <EXAMPLE_NAME=y>`.
# For instance, build with `make BASIC_EXAMPLE=y` to choose the BASIC_EXAMPLE.

# Force select an example by assigning y for enabling.
BASIC_EXAMPLE = y

# Targeted for Maxim MAX78000FTHR
include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk



