## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/ad7616_sdz/zed/ad7616_sdz_zed.sdk/system_top.hdf

include $(NOOS-DIR)/ad7616-sdz/ad7616_sdz.mk
include $(NOOS-DIR)/scripts/zynq_ps7.mk

