CONFIG_XILINX_HDL_DESIGN="daq2"
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_UART=y
CONFIG_IIO=y
CONFIG_ADC=y
CONFIG_ADC_IIO_AD9680=y
CONFIG_DAC=y
CONFIG_DAC_IIO_AD9144=y
CONFIG_FREQUENCY=y
CONFIG_FREQUENCY_AD9523=y
CONFIG_AXI_CORE=y
CONFIG_AXI_CORE_AXI_ADC_CORE=y
CONFIG_AXI_CORE_AXI_DAC_CORE=y
CONFIG_AXI_CORE_AXI_DMAC=y
CONFIG_AXI_CORE_CLK_AXI_CLKGEN=y
CONFIG_AXI_CORE_JESD204=y
CONFIG_AXI_CORE_IIO_AXI_ADC=y
CONFIG_AXI_CORE_IIO_AXI_DAC=y
CONFIG_FMCDAQ2_IIO_EXAMPLE=y
