CONFIG_XILINX_HDL_DESIGN="ad5766_sdz"
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_UART=y
CONFIG_AXI_CORE=y
CONFIG_AXI_CORE_AXI_DMAC=y
CONFIG_AXI_CORE_SPI_ENGINE=y
CONFIG_DAC=y
CONFIG_DAC_AD5766=y
CONFIG_AD5766_SDZ_EXAMPLE_EXAMPLE=y
