## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/daq3/kcu105/daq3_kcu105.sdk/system_top.hdf

include $(NOOS-DIR)/ad-fmcdaq3-ebz/ad_fmcdaq3_ebz.mk
include $(NOOS-DIR)/scripts/microblaze.mk

