## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/ad9467_fmc/kc705/ad9467_fmc_kc705.sdk/system_top.hdf


include $(NOOS-DIR)/AD9467-FMC-EBZ/ad9467.mk
include $(NOOS-DIR)/scripts/microblaze.mk

