drivers:
  - changed-files:
      - any-glob-to-any-file:
          - 'drivers/**/*.c'
          - 'drivers/**/*.h'
          - 'drivers/**/*.cpp'
          - 'drivers/**/*.json'
          - 'drivers/**/Makefile'
          - 'include/**/*.h'

projects:
  - changed-files:
      - any-glob-to-any-file:
          - 'projects/**/*.c'
          - 'projects/**/*.h'
          - 'projects/**/*.mk'
          - 'projects/**/Makefile'
          - 'projects/**/*.ld'
          - 'projects/**/*.tcl'
          - 'projects/**/*.xdc'
          - 'projects/**/*.json'
          - 'projects/**/*.ioc'

documentation:
  - changed-files:
      - any-glob-to-any-file:
          - 'doc/**'
          - '**/*.md'
          - '**/*.rst'

CI:
  - changed-files:
      - any-glob-to-any-file:
          - 'tools/scripts/**'
          - 'ci/**'
          - '.github/**'
          - 'azure-pipelines.yml'
          - 'build_projects.yml'
