## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/ad6676evb/zc706/ad6676evb_zc706.sdk/system_top.hdf

include $(NOOS-DIR)/ad6676-ebz/ad6676_ebz.mk
include $(NOOS-DIR)/scripts/zynq.mk

