add_executable(adv7511)

target_sources(adv7511 PRIVATE
	${CMAKE_CURRENT_SOURCE_DIR}/src/main.c
	${CMAKE_CURRENT_SOURCE_DIR}/src/cf_hdmi.c
	${CMAKE_CURRENT_SOURCE_DIR}/src/edid.c
	${CMAKE_CURRENT_SOURCE_DIR}/src/transmitter.c
	${CMAKE_CURRENT_SOURCE_DIR}/src/wrapper.c
	${CMAKE_CURRENT_SOURCE_DIR}/TX/HAL/COMMON/tx_hal.c
	${CMAKE_CURRENT_SOURCE_DIR}/TX/HAL/WIRED/wrd_hal.c
	${CMAKE_CURRENT_SOURCE_DIR}/TX/HAL/WIRED/ADV7511/7511_hal.c
	${CMAKE_CURRENT_SOURCE_DIR}/TX/LIB/tx_cec.c
	${CMAKE_CURRENT_SOURCE_DIR}/TX/LIB/tx_isr.c
	${CMAKE_CURRENT_SOURCE_DIR}/TX/LIB/tx_lib.c
	${CMAKE_CURRENT_SOURCE_DIR}/TX/LIB/tx_multi.c
)

target_include_directories(adv7511 PUBLIC
	${CMAKE_CURRENT_SOURCE_DIR}/src
	${CMAKE_CURRENT_SOURCE_DIR}/TX
	${CMAKE_CURRENT_SOURCE_DIR}/TX/HAL/COMMON
	${CMAKE_CURRENT_SOURCE_DIR}/TX/HAL/WIRED
	${CMAKE_CURRENT_SOURCE_DIR}/TX/HAL/WIRED/ADV7511
	${CMAKE_CURRENT_SOURCE_DIR}/TX/HAL/WIRED/ADV7511/MACROS
	${CMAKE_CURRENT_SOURCE_DIR}/TX/LIB
)

target_compile_definitions(adv7511 PRIVATE PLATFORM_ZED)

target_link_libraries(adv7511 no-os)

config_platform_sdk(adv7511)
add_flash_target(adv7511)
post_build_config(adv7511)
