## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/ad7768_evb/zed/ad7768_evb_zed.sdk/system_top.hdf

include $(NOOS-DIR)/ad7768-evb/ad7768_evb.mk
include $(NOOS-DIR)/scripts/zynq.mk

