## Makefile

include ../../scripts/noos.mk

M_SOPCINFO_FILE := $(HDL-DIR)/projects/fmcjesdadc1/a10gx/system_bd.sopcinfo
M_SOF_FILE := fmcjesdadc1_a10gx.sof

include $(NOOS-DIR)/ad-fmcjesdadc1-ebz/ad-fmcjesdadc1-ebz.mk
include $(NOOS-DIR)/scripts/nios_ii.mk
