CONFIG_UART=y
CONFIG_IRQ=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_DMA=y
CONFIG_TIMER=y
CONFIG_IIO=y
CONFIG_ADC=y
CONFIG_ADC_IIO_AD7091R8_TRIG=y
CONFIG_AD7091R8_SDZ_IIO_TIMER_TRIGGER_EXAMPLE=y
CONFIG_AD7091R8_SDZ_DEV_R4=y
