# Targeted for Maxim MAX78000FTHR
include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk

# To choose the example at compile time, build with `make <EXAMPLE_NAME=y>`.
# For instance, build with `make BASIC_EXAMPLE=y` to choose the BASIC_EXAMPLE.

# Force select an example by assigning y for enabling.
#BASIC_EXAMPLE = y

# Force select an example by assigning y for enabling.
# IIO_EXAMPLE = y

# Force select an example by assigning y for enabling.
# IIO_TIMER_TRIGGER_EXAMPLE = y

# Select the device you want to enable by choosing y for enabling and n for disabling
# AD7091R2 = y
# AD7091R4 = y
AD7091R8 = y
