# Targeted for Maxim MAX78000FTHR
EXAMPLE ?= iio

# Select the device you want to enable by choosing y for enabling and n for disabling
# AD7091R2 = y
# AD7091R4 = y
AD7091R8 = y

include ../../tools/scripts/generic_variables.mk

include ../../tools/scripts/examples.mk

include src.mk

include ../../tools/scripts/generic.mk
