CONFIG_UART=y
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_DMA=y
CONFIG_TIMER=y
CONFIG_IIO=y
CONFIG_METER=y
CONFIG_METER_ADE9430=y
CONFIG_EVAL_PQMON_BASIC_EXAMPLE=y
CONFIG_EVAL_PQMON_CONN_USB=y
