CONFIG_UART=y
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_DMA=y
CONFIG_TIMER=y
CONFIG_IIO=y
CONFIG_METER=y
CONFIG_METER_ADE9430=y
CONFIG_NET=y
CONFIG_ADIN1110=y
CONFIG_LWIP=y
CONFIG_NO_OS_STATIC_IP=y
CONFIG_NO_OS_LWIP_INIT_ONETIME=y
CONFIG_NO_OS_IP="192.168.97.40"
CONFIG_NO_OS_NETMASK="255.255.0.0"
CONFIG_NO_OS_GATEWAY="0.0.0.0"
CONFIG_EVAL_PQMON_BASIC_EXAMPLE=y
CONFIG_EVAL_PQMON_CONN_T1L=y
