CONFIG_UART=y
CONFIG_IRQ=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_IIO=y
CONFIG_ADC=y
CONFIG_ADC_AD7124=y
CONFIG_ADC_IIO_AD7124=y
CONFIG_AD7124_8PMDZ_IIO_EXAMPLE=y
CONFIG_AD7124_8PMDZ_NETWORKING=y
CONFIG_WIFI_SSID="RouterSSID"
CONFIG_WIFI_PWD="******"
