message(STATUS "Altera / Intel FPGA platform")

# This toolchain file supports both the legacy Altera/Nios II style flow and
# the newer Nios V / Intel FPGA BSP-based flow. The selected mode can come
# from Kconfig (CONFIG_ALTERA_PLATFORM_NIOSV) or from the exported
# ALTERA_PLATFORM_NIOSV environment variable. For Nios V BSP mode, the
# toolchain uses the standard CMake compiler variables directly.

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR niosv)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

function(_altera_resolve_tool_path OUT_VAR TOOL_NAME)
    if(NOT DEFINED CMAKE_C_COMPILER OR CMAKE_C_COMPILER STREQUAL "")
        set(${OUT_VAR} "" PARENT_SCOPE)
        return()
    endif()

    get_filename_component(_altera_compiler_dir "${CMAKE_C_COMPILER}" DIRECTORY)
    get_filename_component(_altera_compiler_name "${CMAKE_C_COMPILER}" NAME)

    set(_altera_candidate_names "${TOOL_NAME}")
    string(REGEX REPLACE "(-gcc|-g\\+\\+|-cc|-clang|-clang\\+\\+)$" "" _altera_tool_prefix "${_altera_compiler_name}")
    if(_altera_tool_prefix AND NOT _altera_tool_prefix STREQUAL "${_altera_compiler_name}")
        list(APPEND _altera_candidate_names "${_altera_tool_prefix}-${TOOL_NAME}")
    endif()
    if(TOOL_NAME STREQUAL "g++" AND _altera_compiler_name MATCHES "gcc$")
        string(REGEX REPLACE "gcc$" "g++" _altera_prefixed_name "${_altera_compiler_name}")
        list(APPEND _altera_candidate_names "${_altera_prefixed_name}")
    elseif(TOOL_NAME STREQUAL "gcc" AND _altera_compiler_name MATCHES "g\\+\\+$")
        string(REGEX REPLACE "g\\+\\+$" "gcc" _altera_prefixed_name "${_altera_compiler_name}")
        list(APPEND _altera_candidate_names "${_altera_prefixed_name}")
    endif()

    if(_altera_compiler_dir)
        foreach(_altera_candidate_name IN LISTS _altera_candidate_names)
            set(_altera_candidate_path "${_altera_compiler_dir}/${_altera_candidate_name}")
            if(EXISTS "${_altera_candidate_path}")
                set(${OUT_VAR} "${_altera_candidate_path}" PARENT_SCOPE)
                return()
            endif()
        endforeach()
    endif()

    find_program(_altera_resolved NAMES ${_altera_candidate_names} PATHS "${_altera_compiler_dir}" NO_DEFAULT_PATH)
    if(_altera_resolved)
        set(${OUT_VAR} "${_altera_resolved}" PARENT_SCOPE)
    else()
        set(${OUT_VAR} "" PARENT_SCOPE)
    endif()
endfunction()

set(_altera_use_niosv OFF)
if(DEFINED CONFIG_ALTERA_PLATFORM_NIOSV AND "${CONFIG_ALTERA_PLATFORM_NIOSV}" STREQUAL "ON")
    set(_altera_use_niosv ON)
elseif(DEFINED ENV{ALTERA_PLATFORM_NIOSV} AND NOT "$ENV{ALTERA_PLATFORM_NIOSV}" STREQUAL "")
    set(_altera_use_niosv ON)
elseif(DEFINED BOARD AND "${BOARD}" STREQUAL "altera")
    set(_altera_use_niosv ON)
endif()

set(_altera_cc "")
if(DEFINED ENV{CMAKE_C_COMPILER} AND NOT "$ENV{CMAKE_C_COMPILER}" STREQUAL "")
    set(_altera_cc "$ENV{CMAKE_C_COMPILER}")
elseif(DEFINED CMAKE_C_COMPILER AND NOT CMAKE_C_COMPILER STREQUAL "")
    if(IS_ABSOLUTE "${CMAKE_C_COMPILER}" OR "${CMAKE_C_COMPILER}" MATCHES "/")
        set(_altera_cc "${CMAKE_C_COMPILER}")
    else()
        message(FATAL_ERROR "Altera toolchain requires a full path in CMAKE_C_COMPILER; got '${CMAKE_C_COMPILER}'.")
    endif()
endif()

if(_altera_use_niosv AND (NOT DEFINED ENV{ALTERA_BSP_DIR} OR "$ENV{ALTERA_BSP_DIR}" STREQUAL ""))
    message(FATAL_ERROR "ALTERA_BSP_DIR is not set. Export the generated BSP directory before configuring a Nios V build.")
endif()

if(_altera_cc STREQUAL "")
    message(STATUS "Altera toolchain: CMAKE_C_COMPILER was not supplied; relying on CMake's compiler detection")
else()
    set(CMAKE_C_COMPILER "${_altera_cc}" CACHE FILEPATH "C compiler" FORCE)
endif()

_altera_resolve_tool_path(_altera_linker "ld")
if(_altera_linker)
    set(CMAKE_LINKER "${_altera_linker}" CACHE FILEPATH "Linker" FORCE)
endif()
_altera_resolve_tool_path(_altera_size "size")
if(_altera_size)
    set(CMAKE_SIZE "${_altera_size}" CACHE FILEPATH "Size tool" FORCE)
endif()
_altera_resolve_tool_path(_altera_objcopy "objcopy")
if(_altera_objcopy)
    set(CMAKE_OBJCOPY "${_altera_objcopy}" CACHE FILEPATH "Objcopy" FORCE)
endif()
_altera_resolve_tool_path(_altera_objdump "objdump")
if(_altera_objdump)
    set(CMAKE_OBJDUMP "${_altera_objdump}" CACHE FILEPATH "Objdump" FORCE)
endif()

set(CMAKE_C_FLAGS "-ffunction-sections -fdata-sections -std=gnu11 -Wall -Wextra" CACHE STRING "C compiler flags" FORCE)
set(CMAKE_CXX_FLAGS "-ffunction-sections -fdata-sections -Wall -Wextra" CACHE STRING "C++ compiler flags" FORCE)
set(CMAKE_ASM_FLAGS "-D__ASSEMBLY__" CACHE STRING "ASM compiler flags" FORCE)

if(DEFINED ENV{ALTERA_CFLAGS} AND NOT "$ENV{ALTERA_CFLAGS}" STREQUAL "")
    string(APPEND CMAKE_C_FLAGS " $ENV{ALTERA_CFLAGS}")
    string(APPEND CMAKE_CXX_FLAGS " $ENV{ALTERA_CFLAGS}")
    string(APPEND CMAKE_ASM_FLAGS " $ENV{ALTERA_CFLAGS}")
endif()

if(DEFINED ENV{ALTERA_LDFLAGS} AND NOT "$ENV{ALTERA_LDFLAGS}" STREQUAL "")
    set(CMAKE_EXE_LINKER_FLAGS "$ENV{ALTERA_LDFLAGS}" CACHE STRING "Linker flags" FORCE)
endif()

message(STATUS "Configured Altera toolchain mode: ${_altera_use_niosv}")
if(_altera_cc STREQUAL "")
    message(STATUS "  prefix: ${_altera_prefix}")
else()
    message(STATUS "  compiler: ${_altera_cc}")
endif()
if(_altera_use_niosv)
    message(STATUS "  BSP directory: $ENV{ALTERA_BSP_DIR}")
endif()
