CONFIG_UART=y
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_DMA=y
CONFIG_MDIO=y
CONFIG_EEPROM=y
CONFIG_RTC=y
CONFIG_PWM=y
CONFIG_IIO=y
CONFIG_RF_TRANSCEIVER=y
CONFIG_RF_TRANSCEIVER_IIO_HMC630X=y
CONFIG_NET=y
CONFIG_NET_ADIN1300=y
CONFIG_NET_IIO_ADIN1300=y
CONFIG_NET_MAX24287=y
CONFIG_NET_IIO_MAX24287=y
CONFIG_NET_MDIO_BITBANG=y
CONFIG_ADC=y
CONFIG_ADC_IIO_ADM1177=y
CONFIG_EEPROM_DRIVERS=y
CONFIG_EEPROM_DRIVERS_24XX32A=y
CONFIG_WETHLINK_WETHLINK_REVA_EXAMPLE=y
