# Select the example you want to enable by choosing y for enabling and n for disabling
BASIC_EXAMPLE = n
DMA_EXAMPLE = n
IIO_EXAMPLE = y

# Select by placing y for the use of the desired profile
JESD204B_NO_ORX_PROFILE = n
JESD204B_ORX_PROFILE = y

# Uncomment to use the desired platform
PLATFORM = xilinx

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
