EXAMPLE ?= iio_example

# Select by placing y for the use of the desired profile
JESD204B_NO_ORX_PROFILE = n
JESD204B_ORX_PROFILE = y
JESD204C_ORX_PROFILE = n

# Uncomment to use the desired platform
PLATFORM = xilinx

include ../../tools/scripts/generic_variables.mk

include ../../tools/scripts/examples.mk

include src.mk

include ../../tools/scripts/generic.mk
