CONFIG_XILINX_HDL_DESIGN="ad6676evb"
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_UART=y
CONFIG_IIO=y
CONFIG_ADC=y
CONFIG_ADC_AD6676=y
CONFIG_AXI_CORE=y
CONFIG_AXI_CORE_AXI_ADC_CORE=y
CONFIG_AXI_CORE_AXI_DMAC=y
CONFIG_AXI_CORE_CLK_AXI_CLKGEN=y
CONFIG_AXI_CORE_JESD204=y
CONFIG_AXI_CORE_IIO_AXI_ADC=y
CONFIG_AD6676_EBZ_IIO_EXAMPLE=y
