## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/fmcomms2/kc705/fmcomms2_kc705.sdk/system_top.hdf

include $(NOOS-DIR)/fmcomms2/fmcomms2.mk
include $(NOOS-DIR)/scripts/microblaze.mk

