# Select the example you want to enable by choosing y and disable others by choosing n.

CFG_DIAG_MAX96792_MAX96793_UC_EX = y

# Targeted for GMSL
include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
