# Select the example you want to enable by choosing y for enabling and n for disabling
BASIC_EXAMPLE = y
DMA_EXAMPLE = n
IIO_EXAMPLE = n

# Uncomment to use the desired platform
PLATFORM = xilinx

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
