/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.8 at 7/19/2021 9:28:21 PM.
 * 
 * @copyright copyright(c) 2021 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup APOLLO_BF
 * @{
 */
#ifndef __ADI_APOLLO_BF_JRX_DL_204C_H__
#define __ADI_APOLLO_BF_JRX_DL_204C_H__

/*============= D E F I N E S ==============*/
#define JRX_DL_204C_JRX_TX_DIGITAL0                            0x61610000
#define JRX_DL_204C_JRX_TX_DIGITAL1                            0x61E10000

#define REG_JRX_DL_204C_CONFIG_ADDR(inst)                      ((inst) + 0x00000000)
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204C_CRC_FEC_REVERSE_CFG_INFO(inst)          ((inst) + 0x00000000), 0x00000100
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204C_LINK_LOCK_INFO(inst)                    ((inst) + 0x00000000), 0x00000102
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204C_CLR_ERR_CNT_INFO(inst)                  ((inst) + 0x00000000), 0x00000103
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204C_HOLD_ERR_CNT_INFO(inst)                 ((inst) + 0x00000000), 0x00000104
#endif /* USE_PRIVATE_BF */
#define BF_JRX_DL_204C_SYNC_WORD_SEL_INFO(inst)                ((inst) + 0x00000000), 0x00000206

#ifdef USE_PRIVATE_BF
#define REG_JRX_DL_204C_MB_ADDR(inst)                          ((inst) + 0x00000001)
#define BF_JRX_DL_204C_MB_ERR_CFG_INFO(inst)                   ((inst) + 0x00000001), 0x00000400
#define BF_JRX_DL_204C_MB_REQD_CFG_INFO(inst)                  ((inst) + 0x00000001), 0x00000404
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_DL_204C_SH_ERR_ADDR(inst)                      ((inst) + 0x00000002)
#define BF_JRX_DL_204C_SH_ERR_CFG_INFO(inst)                   ((inst) + 0x00000002), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_DL_204C_SH_REQD_ADDR(inst)                     ((inst) + 0x00000003)
#define BF_JRX_DL_204C_SH_REQD_CFG_INFO(inst)                  ((inst) + 0x00000003), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_DL_204C_EMB_ADDR(inst)                         ((inst) + 0x00000005)
#define BF_JRX_DL_204C_EMB_ERR_CFG_INFO(inst)                  ((inst) + 0x00000005), 0x00000300
#define BF_JRX_DL_204C_EMB_REQD_CFG_INFO(inst)                 ((inst) + 0x00000005), 0x00000404
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_DL_204C_LANE_SKEW0_ADDR(inst, n)               ((inst) + 0x00000010 + 1 * (n))
#define BF_JRX_DL_204C_LANE_SKEW_INFO(inst, n)                 ((inst) + 0x00000010 + 1 * (n)), 0x00000900
#endif /* USE_PRIVATE_BF */

#define REG_JRX_DL_204C_LANE_SKEW1_ADDR(inst, n)               ((inst) + 0x00000020 + 1 * (n))

#ifdef USE_PRIVATE_BF
#define REG_JRX_DL_204C_LANE_STATUS_ADDR(inst, n)              ((inst) + 0x00000030 + 1 * (n))
#define BF_JRX_DL_204C_STATE_INFO(inst, n)                     ((inst) + 0x00000030 + 1 * (n)), 0x00000300
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_DL_204C_LANE_SH_ERR_ADDR(inst, n)              ((inst) + 0x00000040 + 1 * (n))
#define BF_JRX_DL_204C_SH_ERR_CNT_INFO(inst, n)                ((inst) + 0x00000040 + 1 * (n)), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_DL_204C_LANE_FEC_ERR_ADDR(inst, n)             ((inst) + 0x00000050 + 1 * (n))
#define BF_JRX_DL_204C_FEC_ERR_CNT_INFO(inst, n)               ((inst) + 0x00000050 + 1 * (n)), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_DL_204C_LANE_FEC_UNC_ERR_ADDR(inst, n)         ((inst) + 0x00000060 + 1 * (n))
#define BF_JRX_DL_204C_FEC_UNCORRECTABLE_ERR_CNT_INFO(inst, n) ((inst) + 0x00000060 + 1 * (n)), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_DL_204C_LANE_CRC_ERR_ADDR(inst, n)             ((inst) + 0x00000070 + 1 * (n))
#define BF_JRX_DL_204C_CRC_ERR_CNT_INFO(inst, n)               ((inst) + 0x00000070 + 1 * (n)), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_DL_204C_LANE_BLOCK_ERR_ADDR(inst, n)           ((inst) + 0x00000080 + 1 * (n))
#define BF_JRX_DL_204C_MB_ERR_CNT_INFO(inst, n)                ((inst) + 0x00000080 + 1 * (n)), 0x00000400
#define BF_JRX_DL_204C_EMB_ERR_CNT_INFO(inst, n)               ((inst) + 0x00000080 + 1 * (n)), 0x00000404
#endif /* USE_PRIVATE_BF */

#endif /* __ADI_APOLLO_BF_JRX_DL_204C_H__ */
/*! @} */
