/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.8 at 7/19/2021 9:28:19 PM.
 * 
 * @copyright copyright(c) 2021 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup APOLLO_BF
 * @{
 */
#ifndef __ADI_APOLLO_BF_RX_LOOPBACK_H__
#define __ADI_APOLLO_BF_RX_LOOPBACK_H__

/*============= D E F I N E S ==============*/
#define RX_LOOPBACK_RX_SLICE_0_RX_DIGITAL0 0x60200000
#define RX_LOOPBACK_RX_SLICE_1_RX_DIGITAL0 0x60400000
#define RX_LOOPBACK_RX_SLICE_0_RX_DIGITAL1 0x60A00000
#define RX_LOOPBACK_RX_SLICE_1_RX_DIGITAL1 0x60C00000

#define REG_WRPTR_SYNC_RSTVAL_ADDR(inst)   ((inst) + 0x00000000)
#define BF_WRPTR_SYNC_RSTVAL_INFO(inst)    ((inst) + 0x00000000), 0x00000200

#define REG_ADC_DATA_OVR_STATUS_ADDR(inst) ((inst) + 0x00000001)
#define BF_ADC_DATA_OVR_STATUS_INFO(inst)  ((inst) + 0x00000001), 0x00000400

#define REG_ADC_DATA_OVR_CLR_ADDR(inst)    ((inst) + 0x00000002)
#define BF_ADC_DATA_OVR_CLEAR_INFO(inst)   ((inst) + 0x00000002), 0x00000400

#define REG_LPBK_WR_EN_ADDR(inst)          ((inst) + 0x00000003)
#define BF_LPBK_WR_EN_INFO(inst)           ((inst) + 0x00000003), 0x00000100

#define REG_DBG_DATA_OFF_EN_ADDR(inst)     ((inst) + 0x00000004)
#define BF_DBG_DATA_OFF_EN_INFO(inst)      ((inst) + 0x00000004), 0x00000100

#endif /* __ADI_APOLLO_BF_RX_LOOPBACK_H__ */
/*! @} */
