
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2022.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2023 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xscutimer.h"

/*
* The configuration table for devices
*/

XScuTimer_Config XScuTimer_ConfigTable[XPAR_XSCUTIMER_NUM_INSTANCES] =
{
	{
		XPAR_PS7_SCUTIMER_0_DEVICE_ID,
		XPAR_PS7_SCUTIMER_0_BASEADDR
	}
};


