## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/ad9467_fmc/kc705/ad9467_fmc_ebz.sdk/system_top.hdf

include $(NOOS-DIR)/ad9467-fmc-ebz/ad9467_fmc_ebz.mk
include $(NOOS-DIR)/scripts/microblaze.mk

