## Makefile

include ../../scripts/noos.mk

M_SOPCINFO_FILE := $(HDL-DIR)/projects/daq3/a10gx/system_bd.sopcinfo
M_SOF_FILE := daq3.sof

include $(NOOS-DIR)/ad-fmcdaq3-ebz/ad_fmcdaq3_ebz.mk
include $(NOOS-DIR)/scripts/nios_ii.mk

