## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/daq3/zcu102/daq3_zcu102.sdk/system_top.hdf

include $(NOOS-DIR)/fmcdaq3/fmcdaq3.mk
include $(NOOS-DIR)/scripts/zynq_u.mk

