/**
 * \file
 * \brief BitField accessors for ADRV9001
 *
 * Autogenerated with yoda-gen 1.1.0. Do not modify.
 *
 * \copyright Copyright (c) 2020 Analog Devices, Inc. All Rights Reserved.
 * This software is proprietary to Analog Devices, Inc. and its licensors.
 */

 #ifndef __ADRV9001_BF_H__
 #define __ADRV9001_BF_H__

#include "adrv9001_nvs_regmap_core.h"
#include "adrv9001_nvs_regmap_core_1.h"
#include "adrv9001_nvs_regmap_core_2.h"
#include "adrv9001_nvs_regmap_tx.h"
#include "adrv9001_nvs_regmap_txb.h"
#include "adrv9001_nvs_regmap_rx.h"
#include "adrv9001_nvs_regmap_rxb.h"
#include "adrv9001_nvs_regmap_core_3.h"
#include "adrv9001_nvs_pll_mem_map.h"
#include "adrv9001_adc1_mem_map.h"
#include "adrv9001_adc2_mem_map.h"
#include "adrv9001_txdac_mem_map.h"
#include "adrv9001_analog_rx_mem_map.h"
#include "adrv9001_analog_rxb_mem_map.h"
#include "adrv9001_analog_tx_mem_map.h"
#include "adrv9001_vco_adc_mem_map.h"

#endif // __ADRV9001_BF_H__