CONFIG_XILINX_HDL_DESIGN="ad9467_fmc"
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_UART=y
CONFIG_IIO=y
CONFIG_ADC=y
CONFIG_ADC_AD9467=y
CONFIG_FREQUENCY=y
CONFIG_FREQUENCY_AD9517=y
CONFIG_AXI_CORE=y
CONFIG_AXI_CORE_AXI_ADC_CORE=y
CONFIG_AXI_CORE_AXI_DMAC=y
CONFIG_AXI_CORE_IIO_AXI_ADC=y
CONFIG_AD9467_IIO_EXAMPLE=y
