INCS += $(PLATFORM_DRIVERS)/$(PLATFORM)_spi.h		\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_i2c.h		\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_timer.h	\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_delay.h	\

SRCS += $(PLATFORM_DRIVERS)/$(PLATFORM)_delay.c	\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_spi.c		\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_i2c.c		\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_timer.c	\
