CONFIG_UART=y
CONFIG_IRQ=y
CONFIG_GPIO=y
CONFIG_I2C=y
CONFIG_DMA=y
CONFIG_TIMER=y
CONFIG_FREERTOS=y
CONFIG_FREERTOS_CONF_PATH="projects/iio_demo_freeRTOS/src/platform/maxim/FreeRTOSConfig.h"
CONFIG_IIO=y
CONFIG_ADC=y
CONFIG_ADC_IIO_DEMO=y
CONFIG_DAC=y
CONFIG_DAC_IIO_DEMO=y
CONFIG_IIO_DEMO_FREERTOS_IIO_EXAMPLE=y
