# Select the example you want to enable
EXAMPLE = iio_example
LIBRARIES += freertos

include ../../tools/scripts/generic_variables.mk

include ../../tools/scripts/examples.mk

include src.mk

include ../../tools/scripts/generic.mk
