# Select the example you want to enable by chossing y for enabling and n for disabling
DUMMY_EXAMPLE = n
TEST_EXAMPLE = n
VOLTAGE_OUTPUT_EXAMPLE = n
CURRENT_OUTPUT_EXAMPLE = y

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
