CONFIG_UART=y
CONFIG_IRQ=y
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_DMA=y
CONFIG_TIMER=y
CONFIG_FREERTOS=y
CONFIG_FREERTOS_CONF_PATH="projects/apard32690/src/FreeRTOSConfig.h"
CONFIG_ESH=y
CONFIG_APARD32690_ESH_EXAMPLE=y
