APARD32690_BASIC_EXAMPLE = n
APARD32690_ECHO_SERVER_EXAMPLE = y

PLATFORM=maxim
TARGET=max32690

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
