CONFIG_UART=y
CONFIG_IRQ=y
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_DMA=y
CONFIG_TIMER=y
CONFIG_LWIP=y
CONFIG_NET=y
CONFIG_ADIN1110=y
CONFIG_APARD32690_ECHO_SERVER_EXAMPLE=y

CONFIG_NO_OS_STATIC_IP=y
CONFIG_NO_OS_IP="192.168.97.40"
CONFIG_NO_OS_NETMASK="255.255.0.0"
CONFIG_NO_OS_GATEWAY="0.0.0.0"
