## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/daq3/zc706/daq3_zc706.sdk/system_top.hdf

include $(NOOS-DIR)/ad-fmcdaq3-ebz/ad_fmcdaq3_ebz.mk
include $(NOOS-DIR)/scripts/zynq.mk

