# Select the example you want to enable by choosing y for enabling and n for disabling
FRAME_RX_TX = y

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
