CONFIG_UART=y
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_DMA=y
CONFIG_IIO=y
CONFIG_ADC=y
CONFIG_ADC_IIO_PULSAR_ADC=y
CONFIG_AXI_CORE=y
CONFIG_AXI_CORE_SPI_ENGINE=y
CONFIG_PULSAR_ADC_IIO_EXAMPLE=y
