# Uncomment to use the desired platform
# PLATFORM = stm32
PLATFORM = mbed

# Select the example you want to enable by chossing y for enabling and n for disabling
BASIC_EXAMPLE = n
IIO_EXAMPLE = y

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
