CONFIG_UART=y
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_DMA=y
CONFIG_PWM=y
CONFIG_PWM_STM32=y
CONFIG_ADC=y
CONFIG_ADC_AD738X=y
CONFIG_AD738X_FMCZ_USE_STANDARD_SPI=y
CONFIG_AD738X_FMCZ_BASIC_EXAMPLE=y
