## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/fmcomms5/zc702/fmcomms5_zc702.sdk/system_top.hdf

include $(NOOS-DIR)/fmcomms5/fmcomms5.mk
include $(NOOS-DIR)/scripts/zynq_ps7.mk

