CONFIG_UART=y
CONFIG_SPI=y
CONFIG_DMA=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_I2C=y
CONFIG_I2C_STM32=y
CONFIG_IIO=y
CONFIG_EEPROM=y
CONFIG_EEPROM_DRIVERS=y
CONFIG_EEPROM_DRIVERS_24XX32A=y
CONFIG_POSITION=y
CONFIG_POSITION_IIO_ADMT4000_TRIG=y
CONFIG_ADMT4000_IIO_TRIGGER_EXAMPLE=y
