FW_VERSION ?= 1.0.0.a.0
TMC_ENABLED ?= y

PLATFORM ?= stm32

EXAMPLE ?= iio_trigger_example

include ../../tools/scripts/generic_variables.mk

include ../../tools/scripts/examples.mk

include src.mk

include ../../tools/scripts/generic.mk