# Select the example you want to enable by chossing y for enabling and n for disabling
BASIC_EXAMPLE = n
TEST_EXAMPLE = n
VOLTAGE_OUTPUT_EXAMPLE = n
CURRENT_OUTPUT_EXAMPLE = n
VOLTAGE_INPUT_EXAMPLE = n
CURRENT_INPUT_EXT_EXAMPLE = n
CURRENT_INPUT_LOOP_EXAMPLE = n
MULTIPLE_DEVICES_EXAMPLE = n
DIGITAL_INPUT_LOGIC_EXAMPLE = n
DIGITAL_INPUT_LOOP_EXAMPLE = n
DIGITAL_OUTPUT_EXAMPLE = y
TEMPERATURE_2WIRE_RTD_EXAMPLE = n
TEMPERATURE_3WIRE_RTD_EXAMPLE = n

# Select the device you want to enable by choosing y for enabling and n for disabling
include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
