# Select the example you want to enable by chossing y for enabling and n for disabling
BASIC_EXAMPLE = n
TEST_EXAMPLE = n
VOLTAGE_OUTPUT_EXAMPLE = n
CURRENT_OUTPUT_EXAMPLE = n
VOLTAGE_INPUT_EXAMPLE = n
CURRENT_INPUT_EXT_EXAMPLE = n
MULTIPLE_DEVICES_EXAMPLE = y

# Select the device you want to enable by choosing y for enabling and n for disabling
include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
