CONFIG_UART=y
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_DMA=y
CONFIG_IIO=y
CONFIG_AFE=y
CONFIG_AFE_IIO_AD5940=y
CONFIG_SWITCH=y
CONFIG_SWITCH_IIO_ADG2128=y
CONFIG_CN0565_EIT_IIO_EXAMPLE=y
