# Uncomment to use the desired platform
# PLATFORM = xilinx
# PLATFORM = altera
# PLATFORM = aducm3029
# PLATFORM = stm32
CFLAGS += -DENABLE_UART_STDIO

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
