## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/fmcjesdadc1/kc705/fmcjesdadc1_kc705.sdk/system_top.hdf

include $(NOOS-DIR)/ad-fmcjesdadc1-ebz/ad-fmcjesdadc1-ebz.mk

include $(NOOS-DIR)/scripts/microblaze.mk

