## Makefile

M_SRC_DIRS := $(NOOS-DIR)/ad9361/sw
ifeq ($(PLATFORM),ALTERA)
	M_SRC_DIRS += $(NOOS-DIR)/ad9361/sw/platform_altera
endif
ifeq ($(PLATFORM),XILINX)
	M_SRC_DIRS += $(NOOS-DIR)/ad9361/sw/platform_xilinx
endif

M_DEFINES := CONFIG_H_
M_DEFINES += AXI_ADC_NOT_LEGACY_DIGITAL_TUNE
M_DEFINES += HAVE_VERBOSE_MESSAGES
M_DEFINES += HAVE_SPLIT_GAIN_TABLE=1
M_DEFINES += HAVE_TDD_SYNTH_TABLE=1
ifeq ($(MODE),2R2T)
	M_DEFINES += AD9361_DEVICE=1
	M_DEFINES += AD9364_DEVICE=0
endif
ifeq ($(MODE),1R1T)
	M_DEFINES += AD9361_DEVICE=0
	M_DEFINES += AD9364_DEVICE=1
endif
M_DEFINES += AD9363A_DEVICE=0
ifeq ($(PLATFORM),XILINX)
	M_DEFINES += XILINX_PLATFORM
endif


