/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.8 at 7/19/2021 9:28:21 PM.
 * 
 * @copyright copyright(c) 2021 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup APOLLO_BF
 * @{
 */
#ifndef __ADI_APOLLO_BF_TX_MISC_H__
#define __ADI_APOLLO_BF_TX_MISC_H__

/*============= D E F I N E S ==============*/
#define TX_MISC_TX_TOP_TX_DIGITAL0                    0x61000000
#define TX_MISC_TX_TOP_TX_DIGITAL1                    0x61800000

#define REG_DP_CFG_ADDR(inst)                         ((inst) + 0x00000000)
#define BF_MODSW0_INFO(inst)                          ((inst) + 0x00000000), 0x00000300
#define BF_MODSW1_INFO(inst)                          ((inst) + 0x00000000), 0x00000303
#define BF_DIS_SCALE_INFO(inst)                       ((inst) + 0x00000000), 0x00000206

#ifdef USE_PRIVATE_BF
#define REG_HS_XBAR_CTRL_ADDR(inst)                   ((inst) + 0x00000001)
#define BF_HS_XBAR_CTRL_INFO(inst)                    ((inst) + 0x00000001), 0x00000800
#endif /* USE_PRIVATE_BF */

#define REG_FDUC_ENABLES00_ADDR(inst)                 ((inst) + 0x00000002)
#define BF_FDUC_ENABLES00_INFO(inst)                  ((inst) + 0x00000002), 0x00000800

#define REG_FDUC_ENABLES01_ADDR(inst)                 ((inst) + 0x00000003)
#define BF_FDUC_ENABLES01_INFO(inst)                  ((inst) + 0x00000003), 0x00000800

#define REG_FDUC_ENABLES10_ADDR(inst)                 ((inst) + 0x00000004)
#define BF_FDUC_ENABLES10_INFO(inst)                  ((inst) + 0x00000004), 0x00000800

#define REG_FDUC_ENABLES11_ADDR(inst)                 ((inst) + 0x00000005)
#define BF_FDUC_ENABLES11_INFO(inst)                  ((inst) + 0x00000005), 0x00000800

#define REG_LOW_SAMP_TX_MISC_ADDR(inst)               ((inst) + 0x00000007)
#define BF_LOW_SAMP_TX_MISC_INFO(inst)                ((inst) + 0x00000007), 0x00000100

#define REG_SL0_FDUC0_HB_IRQ_EN0_ADDR(inst)           ((inst) + 0x00000008)
#define BF_EN_SL0_FDUC0_HB1_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000008), 0x00000100
#define BF_EN_SL0_FDUC0_HB2_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000008), 0x00000101
#define BF_EN_SL0_FDUC0_HB3_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000008), 0x00000102
#define BF_EN_SL0_FDUC0_HB4_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000008), 0x00000103
#define BF_EN_SL0_FDUC0_HB5_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000008), 0x00000104
#define BF_EN_SL0_FDUC0_HB6_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000008), 0x00000105

#define REG_SL0_FDUC0_HB_IRQ_EN1_ADDR(inst)           ((inst) + 0x00000009)
#define BF_EN_SL0_FDUC0_HB1_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000009), 0x00000100
#define BF_EN_SL0_FDUC0_HB2_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000009), 0x00000101
#define BF_EN_SL0_FDUC0_HB3_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000009), 0x00000102
#define BF_EN_SL0_FDUC0_HB4_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000009), 0x00000103
#define BF_EN_SL0_FDUC0_HB5_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000009), 0x00000104
#define BF_EN_SL0_FDUC0_HB6_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000009), 0x00000105

#define REG_SL0_FDUC1_IRQ_ADDR(inst)                  ((inst) + 0x0000000A)
#define BF_EN_SL0_FDUC1_HB1_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000A), 0x00000100
#define BF_EN_SL0_FDUC1_HB2_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000A), 0x00000101
#define BF_EN_SL0_FDUC1_HB3_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000A), 0x00000102
#define BF_EN_SL0_FDUC1_HB4_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000A), 0x00000103
#define BF_EN_SL0_FDUC1_HB5_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000A), 0x00000104
#define BF_EN_SL0_FDUC1_HB6_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000A), 0x00000105

#define REG_SL0_FDUC1_HB_IRQ_EN1_ADDR(inst)           ((inst) + 0x0000000B)
#define BF_EN_SL0_FDUC1_HB1_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000B), 0x00000100
#define BF_EN_SL0_FDUC1_HB2_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000B), 0x00000101
#define BF_EN_SL0_FDUC1_HB3_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000B), 0x00000102
#define BF_EN_SL0_FDUC1_HB4_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000B), 0x00000103
#define BF_EN_SL0_FDUC1_HB5_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000B), 0x00000104
#define BF_EN_SL0_FDUC1_HB6_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000B), 0x00000105

#define REG_SL0_FNCO_IRQ_EN_ADDR(inst)                ((inst) + 0x0000000C)
#define BF_EN_SL0_FDUC0_FNCO_OVR_I_IRQ0_INFO(inst)    ((inst) + 0x0000000C), 0x00000100
#define BF_EN_SL0_FDUC0_FNCO_OVR_I_IRQ1_INFO(inst)    ((inst) + 0x0000000C), 0x00000101
#define BF_EN_SL0_FDUC0_FNCO_OVR_Q_IRQ0_INFO(inst)    ((inst) + 0x0000000C), 0x00000102
#define BF_EN_SL0_FDUC0_FNCO_OVR_Q_IRQ1_INFO(inst)    ((inst) + 0x0000000C), 0x00000103
#define BF_EN_SL0_FDUC1_FNCO_OVR_I_IRQ0_INFO(inst)    ((inst) + 0x0000000C), 0x00000104
#define BF_EN_SL0_FDUC1_FNCO_OVR_I_IRQ1_INFO(inst)    ((inst) + 0x0000000C), 0x00000105
#define BF_EN_SL0_FDUC1_FNCO_OVR_Q_IRQ0_INFO(inst)    ((inst) + 0x0000000C), 0x00000106
#define BF_EN_SL0_FDUC1_FNCO_OVR_Q_IRQ1_INFO(inst)    ((inst) + 0x0000000C), 0x00000107

#define REG_SL1_FDUC0_HB_IRQ_EN0_ADDR(inst)           ((inst) + 0x0000000D)
#define BF_EN_SL1_FDUC0_HB1_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000D), 0x00000100
#define BF_EN_SL1_FDUC0_HB2_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000D), 0x00000101
#define BF_EN_SL1_FDUC0_HB3_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000D), 0x00000102
#define BF_EN_SL1_FDUC0_HB4_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000D), 0x00000103
#define BF_EN_SL1_FDUC0_HB5_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000D), 0x00000104
#define BF_EN_SL1_FDUC0_HB6_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000D), 0x00000105

#define REG_SL1_FDUC0_HB_IRQ_EN1_ADDR(inst)           ((inst) + 0x0000000E)
#define BF_EN_SL1_FDUC0_HB1_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000E), 0x00000100
#define BF_EN_SL1_FDUC0_HB2_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000E), 0x00000101
#define BF_EN_SL1_FDUC0_HB3_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000E), 0x00000102
#define BF_EN_SL1_FDUC0_HB4_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000E), 0x00000103
#define BF_EN_SL1_FDUC0_HB5_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000E), 0x00000104
#define BF_EN_SL1_FDUC0_HB6_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000E), 0x00000105

#define REG_SL1_FDUC1_IRQ_ADDR(inst)                  ((inst) + 0x0000000F)
#define BF_EN_SL1_FDUC1_HB1_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000F), 0x00000100
#define BF_EN_SL1_FDUC1_HB2_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000F), 0x00000101
#define BF_EN_SL1_FDUC1_HB3_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000F), 0x00000102
#define BF_EN_SL1_FDUC1_HB4_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000F), 0x00000103
#define BF_EN_SL1_FDUC1_HB5_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000F), 0x00000104
#define BF_EN_SL1_FDUC1_HB6_I_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x0000000F), 0x00000105

#define REG_SL1_FDUC1_HB_IRQ_EN1_ADDR(inst)           ((inst) + 0x00000010)
#define BF_EN_SL1_FDUC1_HB1_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000010), 0x00000100
#define BF_EN_SL1_FDUC1_HB2_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000010), 0x00000101
#define BF_EN_SL1_FDUC1_HB3_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000010), 0x00000102
#define BF_EN_SL1_FDUC1_HB4_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000010), 0x00000103
#define BF_EN_SL1_FDUC1_HB5_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000010), 0x00000104
#define BF_EN_SL1_FDUC1_HB6_Q_OVERFLOW_IRQ_INFO(inst) ((inst) + 0x00000010), 0x00000105

#define REG_SL1_FNCO_IRQ_EN_ADDR(inst)                ((inst) + 0x00000011)
#define BF_EN_SL1_FDUC0_FNCO_OVR_I_IRQ0_INFO(inst)    ((inst) + 0x00000011), 0x00000100
#define BF_EN_SL1_FDUC0_FNCO_OVR_I_IRQ1_INFO(inst)    ((inst) + 0x00000011), 0x00000101
#define BF_EN_SL1_FDUC0_FNCO_OVR_Q_IRQ0_INFO(inst)    ((inst) + 0x00000011), 0x00000102
#define BF_EN_SL1_FDUC0_FNCO_OVR_Q_IRQ1_INFO(inst)    ((inst) + 0x00000011), 0x00000103
#define BF_EN_SL1_FDUC1_FNCO_OVR_I_IRQ0_INFO(inst)    ((inst) + 0x00000011), 0x00000104
#define BF_EN_SL1_FDUC1_FNCO_OVR_I_IRQ1_INFO(inst)    ((inst) + 0x00000011), 0x00000105
#define BF_EN_SL1_FDUC1_FNCO_OVR_Q_IRQ0_INFO(inst)    ((inst) + 0x00000011), 0x00000106
#define BF_EN_SL1_FDUC1_FNCO_OVR_Q_IRQ1_INFO(inst)    ((inst) + 0x00000011), 0x00000107

#define REG_SL0_FDUC0_HB_OVERFLOW0_ADDR(inst)         ((inst) + 0x00000012)
#define BF_IRQ_SL0_FDUC0_HB1_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000012), 0x00000100
#define BF_IRQ_SL0_FDUC0_HB2_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000012), 0x00000101
#define BF_IRQ_SL0_FDUC0_HB3_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000012), 0x00000102
#define BF_IRQ_SL0_FDUC0_HB4_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000012), 0x00000103
#define BF_IRQ_SL0_FDUC0_HB5_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000012), 0x00000104
#define BF_IRQ_SL0_FDUC0_HB6_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000012), 0x00000105
#define BF_IRQ_FDUC_OVER_FLOW_ALL_INFO(inst)          ((inst) + 0x00000012), 0x00000106

#define REG_SL0_FDUC0_HB_OVERFLOW1_ADDR(inst)         ((inst) + 0x00000013)
#define BF_IRQ_SL0_FDUC0_HB1_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000013), 0x00000100
#define BF_IRQ_SL0_FDUC0_HB2_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000013), 0x00000101
#define BF_IRQ_SL0_FDUC0_HB3_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000013), 0x00000102
#define BF_IRQ_SL0_FDUC0_HB4_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000013), 0x00000103
#define BF_IRQ_SL0_FDUC0_HB5_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000013), 0x00000104
#define BF_IRQ_SL0_FDUC0_HB6_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000013), 0x00000105

#define REG_SL0_FDUC1_HB_OVERFLOW0_ADDR(inst)         ((inst) + 0x00000014)
#define BF_IRQ_SL0_FDUC1_HB1_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000014), 0x00000100
#define BF_IRQ_SL0_FDUC1_HB2_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000014), 0x00000101
#define BF_IRQ_SL0_FDUC1_HB3_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000014), 0x00000102
#define BF_IRQ_SL0_FDUC1_HB4_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000014), 0x00000103
#define BF_IRQ_SL0_FDUC1_HB5_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000014), 0x00000104
#define BF_IRQ_SL0_FDUC1_HB6_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000014), 0x00000105

#define REG_SL0_FDUC1_HB_OVERFLOW1_ADDR(inst)         ((inst) + 0x00000015)
#define BF_IRQ_SL0_FDUC1_HB1_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000015), 0x00000100
#define BF_IRQ_SL0_FDUC1_HB2_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000015), 0x00000101
#define BF_IRQ_SL0_FDUC1_HB3_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000015), 0x00000102
#define BF_IRQ_SL0_FDUC1_HB4_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000015), 0x00000103
#define BF_IRQ_SL0_FDUC1_HB5_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000015), 0x00000104
#define BF_IRQ_SL0_FDUC1_HB6_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000015), 0x00000105

#define REG_SL0_FNCO_OVERFLOW_ADDR(inst)              ((inst) + 0x00000016)
#define BF_IRQ_SL0_FDUC0_FNCO_I_OVER_FLOW0_INFO(inst) ((inst) + 0x00000016), 0x00000100
#define BF_IRQ_SL0_FDUC0_FNCO_I_OVER_FLOW1_INFO(inst) ((inst) + 0x00000016), 0x00000101
#define BF_IRQ_SL0_FDUC0_FNCO_Q_OVER_FLOW0_INFO(inst) ((inst) + 0x00000016), 0x00000102
#define BF_IRQ_SL0_FDUC0_FNCO_Q_OVER_FLOW1_INFO(inst) ((inst) + 0x00000016), 0x00000103
#define BF_IRQ_SL0_FDUC1_FNCO_I_OVER_FLOW0_INFO(inst) ((inst) + 0x00000016), 0x00000104
#define BF_IRQ_SL0_FDUC1_FNCO_I_OVER_FLOW1_INFO(inst) ((inst) + 0x00000016), 0x00000105
#define BF_IRQ_SL0_FDUC1_FNCO_Q_OVER_FLOW0_INFO(inst) ((inst) + 0x00000016), 0x00000106
#define BF_IRQ_SL0_FDUC1_FNCO_Q_OVER_FLOW1_INFO(inst) ((inst) + 0x00000016), 0x00000107

#define REG_SL1_FDUC0_HB_OVERFLOW0_ADDR(inst)         ((inst) + 0x00000017)
#define BF_IRQ_SL1_FDUC0_HB1_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000017), 0x00000100
#define BF_IRQ_SL1_FDUC0_HB2_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000017), 0x00000101
#define BF_IRQ_SL1_FDUC0_HB3_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000017), 0x00000102
#define BF_IRQ_SL1_FDUC0_HB4_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000017), 0x00000103
#define BF_IRQ_SL1_FDUC0_HB5_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000017), 0x00000104
#define BF_IRQ_SL1_FDUC0_HB6_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000017), 0x00000105

#define REG_SL1_FDUC0_HB_OVERFLOW1_ADDR(inst)         ((inst) + 0x00000018)
#define BF_IRQ_SL1_FDUC0_HB1_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000018), 0x00000100
#define BF_IRQ_SL1_FDUC0_HB2_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000018), 0x00000101
#define BF_IRQ_SL1_FDUC0_HB3_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000018), 0x00000102
#define BF_IRQ_SL1_FDUC0_HB4_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000018), 0x00000103
#define BF_IRQ_SL1_FDUC0_HB5_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000018), 0x00000104
#define BF_IRQ_SL1_FDUC0_HB6_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x00000018), 0x00000105

#define REG_SL1_FDUC1_HB_OVERFLOW0_ADDR(inst)         ((inst) + 0x00000019)
#define BF_IRQ_SL1_FDUC1_HB1_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000019), 0x00000100
#define BF_IRQ_SL1_FDUC1_HB2_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000019), 0x00000101
#define BF_IRQ_SL1_FDUC1_HB3_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000019), 0x00000102
#define BF_IRQ_SL1_FDUC1_HB4_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000019), 0x00000103
#define BF_IRQ_SL1_FDUC1_HB5_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000019), 0x00000104
#define BF_IRQ_SL1_FDUC1_HB6_I_OVER_FLOW_INFO(inst)   ((inst) + 0x00000019), 0x00000105

#define REG_SL1_FDUC1_HB_OVERFLOW1_ADDR(inst)         ((inst) + 0x0000001A)
#define BF_IRQ_SL1_FDUC1_HB1_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x0000001A), 0x00000100
#define BF_IRQ_SL1_FDUC1_HB2_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x0000001A), 0x00000101
#define BF_IRQ_SL1_FDUC1_HB3_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x0000001A), 0x00000102
#define BF_IRQ_SL1_FDUC1_HB4_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x0000001A), 0x00000103
#define BF_IRQ_SL1_FDUC1_HB5_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x0000001A), 0x00000104
#define BF_IRQ_SL1_FDUC1_HB6_Q_OVER_FLOW_INFO(inst)   ((inst) + 0x0000001A), 0x00000105

#define REG_SL1_FNCO_OVERFLOW_ADDR(inst)              ((inst) + 0x0000001B)
#define BF_IRQ_SL1_FDUC0_FNCO_I_OVER_FLOW0_INFO(inst) ((inst) + 0x0000001B), 0x00000100
#define BF_IRQ_SL1_FDUC0_FNCO_I_OVER_FLOW1_INFO(inst) ((inst) + 0x0000001B), 0x00000101
#define BF_IRQ_SL1_FDUC0_FNCO_Q_OVER_FLOW0_INFO(inst) ((inst) + 0x0000001B), 0x00000102
#define BF_IRQ_SL1_FDUC0_FNCO_Q_OVER_FLOW1_INFO(inst) ((inst) + 0x0000001B), 0x00000103
#define BF_IRQ_SL1_FDUC1_FNCO_I_OVER_FLOW0_INFO(inst) ((inst) + 0x0000001B), 0x00000104
#define BF_IRQ_SL1_FDUC1_FNCO_I_OVER_FLOW1_INFO(inst) ((inst) + 0x0000001B), 0x00000105
#define BF_IRQ_SL1_FDUC1_FNCO_Q_OVER_FLOW0_INFO(inst) ((inst) + 0x0000001B), 0x00000106
#define BF_IRQ_SL1_FDUC1_FNCO_Q_OVER_FLOW1_INFO(inst) ((inst) + 0x0000001B), 0x00000107

#define REG_CDUC_DAC_ENABLES_ADDR(inst)               ((inst) + 0x0000001C)
#define BF_CDUC_DAC_ENABLES0_INFO(inst)               ((inst) + 0x0000001C), 0x00000200
#define BF_CDUC_DAC_ENABLES1_INFO(inst)               ((inst) + 0x0000001C), 0x00000202
#define BF_CDUC_DAC_ENABLES2_INFO(inst)               ((inst) + 0x0000001C), 0x00000204
#define BF_CDUC_DAC_ENABLES3_INFO(inst)               ((inst) + 0x0000001C), 0x00000206

#define REG_DUC_EN_CFG_ADDR(inst)                     ((inst) + 0x0000001D)
#define BF_CDUC_EN_INFO(inst)                         ((inst) + 0x0000001D), 0x00000400
#define BF_CDUC_SPI_EN_INFO(inst)                     ((inst) + 0x0000001D), 0x00000106
#define BF_FDUC_SPI_EN_INFO(inst)                     ((inst) + 0x0000001D), 0x00000107

#define REG_FDUC_EN_SPI_ADDR(inst)                    ((inst) + 0x0000001E)
#define BF_FDUC_EN_INFO(inst)                         ((inst) + 0x0000001E), 0x00000800

#define REG_FDUC_TEST_MUX_ADDR(inst)                  ((inst) + 0x0000001F)
#define BF_FDUC_TEST_MUX_INFO(inst)                   ((inst) + 0x0000001F), 0x00000600

#define REG_CFIR_DATA_CTRL_ADDR(inst)                 ((inst) + 0x00000020)
#define BF_CFIR1_SAME_AS_CFIR0_EN_INFO(inst)          ((inst) + 0x00000020), 0x00000100

#ifdef USE_PRIVATE_BF
#define REG_LNX_DBG_MUX_SEL_ADDR(inst)                ((inst) + 0x00000021)
#define BF_LNX_DBG_MUX_SEL_INFO(inst)                 ((inst) + 0x00000021), 0x00000400
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_CFIR_FSRC_DBG_CNT_EN_ADDR(inst)           ((inst) + 0x00000022)
#define BF_CFIR_FSRC_DBG_CNT_EN_INFO(inst)            ((inst) + 0x00000022), 0x00001000
#endif /* USE_PRIVATE_BF */

#define REG_CFIR_FSRC_DBG_CNT_EN1_ADDR(inst)          ((inst) + 0x00000023)

#ifdef USE_PRIVATE_BF
#define REG_CFIR_FSRC_DBG_MUX_SEL_ADDR(inst)          ((inst) + 0x00000024)
#define BF_CFIR_FSRC_DBG_MUX_SEL_INFO(inst)           ((inst) + 0x00000024), 0x00000400
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_LINX_DBG_CNT_EN_TX_MISC_ADDR(inst)        ((inst) + 0x0000033E)
#define BF_LNX_DBG_CNT_EN_INFO(inst)                  ((inst) + 0x0000033E), 0x00000800
#endif /* USE_PRIVATE_BF */

#define REG_PROCESS_MON_SEL_ADDR(inst)                ((inst) + 0x0000033F)
#define BF_PROCESS_MON_SEL_INFO(inst)                 ((inst) + 0x0000033F), 0x00000800

#endif /* __ADI_APOLLO_BF_TX_MISC_H__ */
/*! @} */
