/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.8 at 7/19/2021 9:28:19 PM.
 * 
 * @copyright copyright(c) 2021 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup APOLLO_BF
 * @{
 */
#ifndef __ADI_APOLLO_BF_RX_DATIN_H__
#define __ADI_APOLLO_BF_RX_DATIN_H__

/*============= D E F I N E S ==============*/
#define RX_DATIN_RX_SLICE_0_RX_DIGITAL0              0x60209000
#define RX_DATIN_RX_SLICE_1_RX_DIGITAL0              0x60409000
#define RX_DATIN_RX_SLICE_0_RX_DIGITAL1              0x60A09000
#define RX_DATIN_RX_SLICE_1_RX_DIGITAL1              0x60C09000

#define REG_DFIFO_CTRL_RX_DATIN_ADDR(inst)           ((inst) + 0x00000000)
#define BF_DFIFO_EN_RX_DATIN_INFO(inst)              ((inst) + 0x00000000), 0x00000100
#define BF_RXFIFO_WRCLK_INVERT_INFO(inst)            ((inst) + 0x00000000), 0x00000101
#define BF_DAC_FIFO_FORCEON_CTRL_RX_DATIN_INFO(inst) ((inst) + 0x00000000), 0x00000404

#define REG_LAT_CTRL_RX_DATIN_ADDR(inst)             ((inst) + 0x00000001)
#define BF_LAT_PGM_MODE_RX_DATIN_INFO(inst)          ((inst) + 0x00000001), 0x00000200
#define BF_WR_RD_OFFSET_RX_DATIN_INFO(inst)          ((inst) + 0x00000001), 0x00000302

#define REG_LAT_SPI_CTRL_RX_DATIN_ADDR(inst)         ((inst) + 0x00000002)
#define BF_LAT_RD_SPI_RX_DATIN_INFO(inst)            ((inst) + 0x00000002), 0x00000300
#define BF_LAT_WR_SPI_RX_DATIN_INFO(inst)            ((inst) + 0x00000002), 0x00000403

#ifdef USE_PRIVATE_BF
#define REG_SYNCCNT_STRB_RX_DATIN_ADDR(inst)         ((inst) + 0x00000003)
#define BF_RDSYNCCNT_WRSTRB_RX_DATIN_INFO(inst)      ((inst) + 0x00000003), 0x00000300
#define BF_WRSYNCCNT_RDSTRB_RX_DATIN_INFO(inst)      ((inst) + 0x00000003), 0x00000403
#endif /* USE_PRIVATE_BF */

#define REG_LAT_REAL_RX_DATIN_ADDR(inst)             ((inst) + 0x00000004)
#define BF_LAT_RD_REAL_RX_DATIN_INFO(inst)           ((inst) + 0x00000004), 0x00000300
#define BF_LAT_WR_REAL_RX_DATIN_INFO(inst)           ((inst) + 0x00000004), 0x00000403

#define REG_SYNC_STATE_RX_DATIN_ADDR(inst)           ((inst) + 0x00000005)
#define BF_RDSYNC_STATE_RX_DATIN_INFO(inst)          ((inst) + 0x00000005), 0x00000200
#define BF_WRSYNC_STATE_RX_DATIN_INFO(inst)          ((inst) + 0x00000005), 0x00000202

#define REG_DEBUG_CTRL_ADDR(inst)                    ((inst) + 0x00000006)
#define BF_DBG_EN_RX_DATIN_INFO(inst)                ((inst) + 0x00000006), 0x00000100
#define BF_DBG_OUT_INFO(inst)                        ((inst) + 0x00000006), 0x00000101
#define BF_DBG_OUT_DEC2_INFO(inst)                   ((inst) + 0x00000006), 0x00000102

#define REG_ADC_MUX_SEL_ADDR(inst)                   ((inst) + 0x00000007)
#define BF_ADC_0_MUX_SEL_INFO(inst)                  ((inst) + 0x00000007), 0x00000200
#define BF_ADC_1_MUX_SEL_INFO(inst)                  ((inst) + 0x00000007), 0x00000202

#define REG_ADC_WR_SETUP_CTRL_ADDR(inst)             ((inst) + 0x00000008)
#define BF_ADC_ANA_BRIDGE_WR_SETUP_CYCLES_INFO(inst) ((inst) + 0x00000008), 0x00000600

#define REG_ADC_WR_HOLD_CTRL_ADDR(inst)              ((inst) + 0x00000009)
#define BF_ADC_ANA_BRIDGE_WR_HOLD_CYCLES_INFO(inst)  ((inst) + 0x00000009), 0x00000600

#define REG_ADC_RD_CTRL_ADDR(inst)                   ((inst) + 0x0000000A)
#define BF_ADC_ANA_BRIDGE_RD_CYCLES_INFO(inst)       ((inst) + 0x0000000A), 0x00000600

#endif /* __ADI_APOLLO_BF_RX_DATIN_H__ */
/*! @} */
