/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.8 at 7/19/2021 9:28:17 PM.
 * 
 * @copyright copyright(c) 2021 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup APOLLO_BF
 * @{
 */
#ifndef __ADI_APOLLO_BF_TELEMETRY_H__
#define __ADI_APOLLO_BF_TELEMETRY_H__

/*============= D E F I N E S ==============*/
#define REG_TELEMETRY_CTRL_ADDR                                     0x46400000
#define BF_TELEMETRY_MODES_INFO                                     0x46400000, 0x00000200
#define BF_TELEMETRY_ENABLE_INFO                                    0x46400000, 0x00000108

#define REG_TELEMETRY_SOURCE_FILTER0_ADDR                           0x46400004
#define BF_TELEMETRY_RX_FILTER_INFO                                 0x46400004, 0x00000800

#define REG_TELEMETRY_SOURCE_FILTER1_ADDR                           0x46400008
#define BF_TELEMETRY_TX_FILTER_INFO                                 0x46400008, 0x00000800

#define REG_TELEMETRY_SOURCE_FILTER2_ADDR                           0x4640000C
#define BF_TELEMETRY_ORX_FILTER_INFO                                0x4640000C, 0x00000200

#define REG_TELEMETRY_SOURCE_FILTER3_ADDR                           0x46400010
#define BF_TELEMETRY_RESTOFALL_FILTER_INFO                          0x46400010, 0x00000500
#define BF_TELEMETRY_INVALID_DATA_FILTER_INFO                       0x46400010, 0x00000105
#define BF_TELEMETRY_KFA_MPU_START_FILTER_INFO                      0x46400010, 0x00000806
#define BF_TELEMETRY_KFA_MPU_DONE_FILTER_INFO                       0x46400010, 0x0000080E
#define BF_TELEMETRY_KFA_STREAM_FILTER_INFO                         0x46400010, 0x00000116

#define REG_TELEMETRY_EVENT_FILTER0_ADDR                            0x46400014
#define BF_TELEMETRY_RX_EVENT_FILTER_INFO                           0x46400014, 0x00000300

#define REG_TELEMETRY_EVENT_FILTER1_ADDR                            0x46400018
#define BF_TELEMETRY_TX_EVENT_FILTER_INFO                           0x46400018, 0x00000300

#define REG_TELEMETRY_EVENT_FILTER2_ADDR                            0x4640001C
#define BF_TELEMETRY_ORX_EVENT_FILTER_INFO                          0x4640001C, 0x00000300

#define REG_TELEMETRY_EVENT_FILTER3_ADDR                            0x46400020
#define BF_TELEMETRY_CORE_EVENT_FILTER_INFO                         0x46400020, 0x00000800

#define REG_TELEMETRY_TS_MASK_ADDR                                  0x46400024
#define BF_TELEMETRY_TS_MASK_BITS_INFO                              0x46400024, 0x00000300

#define REG_TELEMETRY_CORE0_WRDATA_ADDR                             0x46400028
#define BF_TELEMETRY_CORE0_WRDATA_INFO                              0x46400028, 0x00002000

#define REG_TELEMETRY_CORE1_WRDATA_ADDR                             0x4640002C
#define BF_TELEMETRY_CORE1_WRDATA_INFO                              0x4640002C, 0x00002000

#define REG_TELEMETRY_STREAMPROC_WRDATA_ADDR                        0x46400030
#define BF_TELEMETRY_STREAMPROC_WRDATA_INFO                         0x46400030, 0x00002000

#define REG_TELEMETRY_CORE0_WRDATA_WO_TS_ADDR                       0x46400034
#define BF_TELEMETRY_CORE0_WRDATA_WO_TS_INFO                        0x46400034, 0x00002000

#define REG_TELEMETRY_CORE1_WRDATA_WO_TS_ADDR                       0x46400038
#define BF_TELEMETRY_CORE1_WRDATA_WO_TS_INFO                        0x46400038, 0x00002000

#define REG_TELEMETRY_STREAMPROC_WRDATA_WO_TS_ADDR                  0x4640003C
#define BF_TELEMETRY_STREAMPROC_WRDATA_WO_TS_INFO                   0x4640003C, 0x00002000

#define REG_TELEMETRY_STREAM_OVERFLOW_STATUS_WO_SEQFIFO_REG_ADDR    0x46400040
#define BF_TELEMETRY_STREAM_OVR_BITS_WITH_NO_SEQFIFO_OVR_INFO       0x46400040, 0x00001300

#define REG_TELEMETRY_PROC_WR_OVERFLOW_STATUS_WO_SEQFIFO_REG_ADDR   0x46400044
#define BF_TELEMETRY_PROC_WR_OVR_BITS_WITH_NO_SEQFIFO_OVR_INFO      0x46400044, 0x00000600

#define REG_TELEMETRY_KFA_OVERFLOW_STATUS_WO_SEQFIFO_REG_ADDR       0x46400048
#define BF_TELEMETRY_KFA_OVR_BITS_WITH_NO_SEQFIFO_OVR_INFO          0x46400048, 0x00000900

#define REG_TELEMETRY_STREAM_OVERFLOW_STATUS_WITH_SEQFIFO_REG_ADDR  0x4640004C
#define BF_TELEMETRY_STREAM_OVR_BITS_WITH_SEQFIFO_OVR_INFO          0x4640004C, 0x00001300

#define REG_TELEMETRY_PROC_WR_OVERFLOW_STATUS_WITH_SEQFIFO_REG_ADDR 0x46400050
#define BF_TELEMETRY_PROC_WR_OVR_BITS_WITH_SEQFIFO_OVR_INFO         0x46400050, 0x00000600

#define REG_TELEMETRY_KFA_OVERFLOW_STATUS_WITH_SEQFIFO_REG_ADDR     0x46400054
#define BF_TELEMETRY_KFA_OVR_BITS_WITH_SEQFIFO_OVR_INFO             0x46400054, 0x00000900

#define REG_TELEMETRY_OVERFLOW_INTERRUPT_ENABLE_ADDR                0x46400058
#define BF_TELEMETRY_INTR_ENABLE_BITS_INFO                          0x46400058, 0x00000300
#define BF_TELEMETRY_INTR_ENABLE_FOR_SEQFIFO_BIT_INFO               0x46400058, 0x00000303

#define REG_TELEMETRY_MEM_FIFO_INTR_EN_ADDR                         0x4640005C
#define BF_TELEMETRY_MEM_OV_INTR_EN_INFO                            0x4640005C, 0x00000100
#define BF_TELEMETRY_MEM_FIFO_WATERMARK_INTR_EN_INFO                0x4640005C, 0x00000101

#define REG_TELEMETRY_MEM_FIFO_WATERMARK_ADDR                       0x46400060
#define BF_TELEMETRY_MEM_FIFO_WATERMARK_INFO                        0x46400060, 0x00000E00

#define REG_TELEMETRY_MEM_FIFO_STATUS_ADDR                          0x46400064
#define BF_TELEMETRY_MEM_FIFO_EMPTY_INFO                            0x46400064, 0x00000100
#define BF_TELEMETRY_MEM_FIFO_OVERFLOW_INFO                         0x46400064, 0x00000101
#define BF_TELEMETRY_MEM_FIFO_COUNT_INFO                            0x46400064, 0x00000E02

#define REG_TELEMETRY_MEM_DIRECT_ACCESS_ADDR                        0x46400068
#define BF_TELEMETRY_MEM_DIRECT_ACCESS_INFO                         0x46400068, 0x00000100

#endif /* __ADI_APOLLO_BF_TELEMETRY_H__ */
/*! @} */
