CONFIG_UART=y
CONFIG_IRQ=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_DMA=y
CONFIG_LVGL=y
CONFIG_LVGL_VERSION="v9.3.0"
CONFIG_LVGL_CONF_PATH="projects/ssd1306"
CONFIG_DISPLAY=y
CONFIG_DISPLAY_SSD1306=y
CONFIG_SSD1306_EXAMPLE_EXAMPLE=y
