LIBRARIES += lvgl

EXAMPLE ?= example

include ../../tools/scripts/generic_variables.mk

include ../../tools/scripts/examples.mk

include src.mk

CFLAGS += -Os

include ../../tools/scripts/generic.mk
