## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/fmcomms5/zcu102/fmcomms5_zcu102.sdk/system_top.hdf

include $(NOOS-DIR)/fmcomms5/fmcomms5.mk
include $(NOOS-DIR)/scripts/zynq_u.mk

