## Makefile

include ../../scripts/noos.mk

M_SOPCINFO_FILE := $(HDL-DIR)/projects/daq3/a10gx/system_bd.sopcinfo
M_SOF_FILE := daq3_a10gx.sof

include $(NOOS-DIR)/fmcdaq3/fmcdaq3.mk
include $(NOOS-DIR)/scripts/nios_ii.mk

