## Makefile

include ../../scripts/noos.mk

M_SOPCINFO_FILE := $(HDL-DIR)/projects/daq2/a10gx/system_bd.sopcinfo
M_SOF_FILE := daq2_a10gx.sof

include $(NOOS-DIR)/fmcdaq2/fmcdaq2.mk
include $(NOOS-DIR)/scripts/nios_ii.mk

