## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/adrv9361z7035/ccbob_lvds/adrv9361z7035_ccbob_lvds.sdk/system_top.hdf

M_COMPILER_DEFINES := CONFIG_H_
include $(NOOS-DIR)/adrv9361z7035/adrv9361z7035.mk
include $(NOOS-DIR)/scripts/zynq_ps7.mk
