CONFIG_UART=y
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_DMA=y
CONFIG_TIMER=y
CONFIG_TEMPERATURE=y
CONFIG_TEMPERATURE_ADT75=y
CONFIG_METER=y
CONFIG_METER_ADE9113=y
CONFIG_AD_ACEVSECRDSET_SL_STOUT_APPLICATION_EXAMPLE=y
CONFIG_AD_ACEVSECRDSET_SL_REV_D=y
