## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/fmcomms2/mitx045/fmcomms2_mitx045.sdk/system_top.hdf

include $(NOOS-DIR)/fmcomms2/fmcomms2.mk
include $(NOOS-DIR)/scripts/zynq_ps7.mk

