# Uncomment to use the desired platform
# PLATFORM = xilinx

EXAMPLE := axi_qspi

include ../../tools/scripts/generic_variables.mk

include ../../tools/scripts/examples.mk

include src.mk

include ../../tools/scripts/generic.mk
