/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.8 at 2/15/2023 10:39:25 AM.
 * 
 * @copyright copyright(c) 2023 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup APOLLO_BF
 * @{
 */
#ifndef __ADI_APOLLO_BF_JRX_PHY_IFX_H__
#define __ADI_APOLLO_BF_JRX_PHY_IFX_H__

/*============= D E F I N E S ==============*/
#define JRX_PHY_IFX_JRX_TX_DIGITAL0                  0x61614000
#define JRX_PHY_IFX_JRX_TX_DIGITAL1                  0x61E14000

#ifdef USE_PRIVATE_BF
#define REG_JRX_PHY_IFX_LANE_PHY_SPLIT_ADDR(inst, n) ((inst) + 0x00000000 + 1 * (n))
#define BF_JRX_IFX_LOG2_SPLIT_INFO(inst, n)          ((inst) + 0x00000000 + 1 * (n)), 0x00000200
#define BF_JRX_IFX_LANE_SEL_INFO(inst, n)            ((inst) + 0x00000000 + 1 * (n)), 0x00000502
#define BF_JRX_IFX_LANE_INVERSE_INFO(inst, n)        ((inst) + 0x00000000 + 1 * (n)), 0x00000107
#endif /* USE_PRIVATE_BF */

#endif /* __ADI_APOLLO_BF_JRX_PHY_IFX_H__ */
/*! @} */
