/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.8 at 2/15/2023 10:39:22 AM.
 * 
 * @copyright copyright(c) 2023 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup APOLLO_BF
 * @{
 */
#ifndef __ADI_APOLLO_BF_RX_SMON_H__
#define __ADI_APOLLO_BF_RX_SMON_H__

/*============= D E F I N E S ==============*/
#define RX_SMON0_RX_SLICE_0_RX_DIGITAL0    0x60207000
#define RX_SMON1_RX_SLICE_0_RX_DIGITAL0    0x60208000
#define RX_SMON0_RX_SLICE_1_RX_DIGITAL0    0x60407000
#define RX_SMON1_RX_SLICE_1_RX_DIGITAL0    0x60408000
#define RX_SMON0_RX_SLICE_0_RX_DIGITAL1    0x60A07000
#define RX_SMON1_RX_SLICE_0_RX_DIGITAL1    0x60A08000
#define RX_SMON0_RX_SLICE_1_RX_DIGITAL1    0x60C07000
#define RX_SMON1_RX_SLICE_1_RX_DIGITAL1    0x60C08000

#define REG_SMON_CLK_EN_ADDR(inst)         ((inst) + 0x00000000)
#define BF_SMON_SFRAMER_MODE_EN_INFO(inst) ((inst) + 0x00000000), 0x00000201

#define REG_SMON_STATUS_FCNT_ADDR(inst)    ((inst) + 0x00000001)
#define BF_SMON_STATUS_FCNT_INFO(inst)     ((inst) + 0x00000001), 0x00000800

#define REG_SMON_PERIOD0_ADDR(inst)        ((inst) + 0x00000002)
#define BF_SMON_PERIOD_INFO(inst)          ((inst) + 0x00000002), 0x00002000

#define REG_SMON_PERIOD1_ADDR(inst)        ((inst) + 0x00000003)

#define REG_SMON_PERIOD2_ADDR(inst)        ((inst) + 0x00000004)

#define REG_SMON_PERIOD3_ADDR(inst)        ((inst) + 0x00000005)

#define REG_SMON_STATUS_CTRL_ADDR(inst)    ((inst) + 0x00000006)
#define BF_SMON_STATUS_UPDATE_INFO(inst)   ((inst) + 0x00000006), 0x00000100
#define BF_SMON_STATUS_RDSEL_INFO(inst)    ((inst) + 0x00000006), 0x00000301
#define BF_SMON_PEAK_EN_INFO(inst)         ((inst) + 0x00000006), 0x00000104
#define BF_SMON_JLINK_SEL_INFO(inst)       ((inst) + 0x00000006), 0x00000105
#define BF_SMON_GPIO_EN_INFO(inst)         ((inst) + 0x00000006), 0x00000106

#define REG_SMON_FRAMER_ADDR(inst)         ((inst) + 0x00000007)
#define BF_SMON_SFRAMER_EN_INFO(inst)      ((inst) + 0x00000007), 0x00000100
#define BF_SMON_SFRAMER_MODE_INFO(inst)    ((inst) + 0x00000007), 0x00000101
#define BF_SMON_SFRAMER_INSEL_INFO(inst)   ((inst) + 0x00000007), 0x00000602

#define REG_SMON_SYNC_CTRL_ADDR(inst)      ((inst) + 0x00000008)
#define BF_SMON_SYNC_EN_INFO(inst)         ((inst) + 0x00000008), 0x00000100
#define BF_SMON_SYNC_NEXT_INFO(inst)       ((inst) + 0x00000008), 0x00000101

#define REG_SMON_STATUS_ADDR(inst, n)      ((inst) + 0x00000009 + 1 * (n))
#define BF_SMON_STATUS_INFO(inst, n)       ((inst) + 0x00000009 + 1 * (n)), 0x00000800

#define REG_SMON_THRESH_LOW0_ADDR(inst)    ((inst) + 0x0000000C)
#define BF_SMON_THRESH_LOW_INFO(inst)      ((inst) + 0x0000000C), 0x00000B00

#define REG_SMON_THRESH_LOW1_ADDR(inst)    ((inst) + 0x0000000D)

#define REG_SMON_THRESH_HIGH0_ADDR(inst)   ((inst) + 0x0000000E)
#define BF_SMON_THRESH_HIGH_INFO(inst)     ((inst) + 0x0000000E), 0x00000B00

#define REG_SMON_THRESH_HIGH1_ADDR(inst)   ((inst) + 0x0000000F)

#endif /* __ADI_APOLLO_BF_RX_SMON_H__ */
/*! @} */
