/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.8 at 2/15/2023 10:39:17 AM.
 * 
 * @copyright copyright(c) 2023 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup APOLLO_BF
 * @{
 */
#ifndef __ADI_APOLLO_BF_UARTFIFO_H__
#define __ADI_APOLLO_BF_UARTFIFO_H__

/*============= D E F I N E S ==============*/
#define REG_UARTFIFO_DATA_ADDR             0x46000000
#define BF_FIFODATA_INFO                   0x46000000, 0x00000800

#define REG_UARTFIFO_STATUS_ADDR           0x46000004
#define BF_FIFO_UNDERFLOW_INFO             0x46000004, 0x00000100
#define BF_FIFO_HALF_FULL_INFO             0x46000004, 0x00000101
#define BF_FIFO_ALMOST_FULL_INFO           0x46000004, 0x00000102
#define BF_FIFO_FULL_INFO                  0x46000004, 0x00000103

#define REG_UARTFIFO_INTR_EN_ADDR          0x46000008
#define BF_FIFOINTREN_INFO                 0x46000008, 0x00000400

#define REG_UARTFIFO_OCCUPANCY_STATUS_ADDR 0x4600000C
#define BF_FIFO_OCCUPANCY_STATUS_INFO      0x4600000C, 0x00000900

#endif /* __ADI_APOLLO_BF_UARTFIFO_H__ */
/*! @} */
