/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.8 at 2/15/2023 10:39:24 AM.
 * 
 * @copyright copyright(c) 2023 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup APOLLO_BF
 * @{
 */
#ifndef __ADI_APOLLO_BF_TX_LOOPBACK_H__
#define __ADI_APOLLO_BF_TX_LOOPBACK_H__

/*============= D E F I N E S ==============*/
#define TX_LOOPBACK0_TX_SLICE_0_TX_DIGITAL0 0x61200000
#define TX_LOOPBACK1_TX_SLICE_0_TX_DIGITAL0 0x61201000
#define TX_LOOPBACK0_TX_SLICE_1_TX_DIGITAL0 0x61400000
#define TX_LOOPBACK1_TX_SLICE_1_TX_DIGITAL0 0x61401000
#define TX_LOOPBACK0_TX_SLICE_0_TX_DIGITAL1 0x61A00000
#define TX_LOOPBACK1_TX_SLICE_0_TX_DIGITAL1 0x61A01000
#define TX_LOOPBACK0_TX_SLICE_1_TX_DIGITAL1 0x61C00000
#define TX_LOOPBACK1_TX_SLICE_1_TX_DIGITAL1 0x61C01000

#define REG_LB0_CFG_ADDR(inst)              ((inst) + 0x00000000)
#define BF_LB0_EN_INFO(inst)                ((inst) + 0x00000000), 0x00000100

#define REG_LB0_RDPTR_CTRL_ADDR(inst)       ((inst) + 0x00000001)
#define BF_LB0_RDPTR_SYNC_RSTVAL_INFO(inst) ((inst) + 0x00000001), 0x00000200

#ifdef USE_PRIVATE_BF
#define REG_LB0_STATUS_ADDR(inst)           ((inst) + 0x00000023)
#define BF_LB_STATUS_INFO(inst)             ((inst) + 0x00000023), 0x00000800
#endif /* USE_PRIVATE_BF */

#endif /* __ADI_APOLLO_BF_TX_LOOPBACK_H__ */
/*! @} */
