/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.8 at 2/15/2023 10:39:25 AM.
 * 
 * @copyright copyright(c) 2023 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup APOLLO_BF
 * @{
 */
#ifndef __ADI_APOLLO_BF_JRX_CORE_H__
#define __ADI_APOLLO_BF_JRX_CORE_H__

/*============= D E F I N E S ==============*/
#define JRX_CORE_JRX_TX_DIGITAL0                            0x61604000
#define JRX_CORE_JRX_TX_DIGITAL1                            0x61E04000

#define REG_JRX_CORE_CONFIG_ADDR(inst)                      ((inst) + 0x00000000)
#define BF_JRX_LINK_TYPE_INFO(inst)                         ((inst) + 0x00000000), 0x00000200

#ifdef USE_PRIVATE_BF
#define REG_JRX_CORE_CONFIG0_ADDR(inst, n)                  ((inst) + 0x00000001 + 1 * (n))
#define BF_JRX_CORE_CHKSUM_DISABLE_INFO(inst, n)            ((inst) + 0x00000001 + 1 * (n)), 0x00000100
#define BF_JRX_CORE_CHKSUM_LSB_ALG_INFO(inst, n)            ((inst) + 0x00000001 + 1 * (n)), 0x00000101
#define BF_JRX_CORE_CLEAR_SYNC_NE_COUNT_INFO(inst, n)       ((inst) + 0x00000001 + 1 * (n)), 0x00000102
#define BF_JRX_CORE_PCLK_ERROR_CLEAR_INFO(inst, n)          ((inst) + 0x00000001 + 1 * (n)), 0x00000103
#define BF_JRX_CORE_SYSREF_FOR_RELINK_INFO(inst, n)         ((inst) + 0x00000001 + 1 * (n)), 0x00000104
#define BF_JRX_CORE_SYSREF_FOR_STARTUP_INFO(inst, n)        ((inst) + 0x00000001 + 1 * (n)), 0x00000105
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_CORE_SAMPLE_XBAR_A_ADDR(inst, n)            ((inst) + 0x00000010 + 1 * (n))
#define BF_JRX_CORE_CONV_SEL_LINK0_INFO(inst, n)            ((inst) + 0x00000010 + 1 * (n)), 0x00000700
#define BF_JRX_CORE_CONV_DISABLE_LINK0_INFO(inst, n)        ((inst) + 0x00000010 + 1 * (n)), 0x00000107
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_CORE_SAMPLE_XBAR_B_ADDR(inst, n)            ((inst) + 0x00000090 + 1 * (n))
#define BF_JRX_CORE_CONV_SEL_LINK1_INFO(inst, n)            ((inst) + 0x00000090 + 1 * (n)), 0x00000700
#define BF_JRX_CORE_CONV_DISABLE_LINK1_INFO(inst, n)        ((inst) + 0x00000090 + 1 * (n)), 0x00000107
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_CORE_SYNC_N_SEL_ADDR(inst, n)               ((inst) + 0x00000110 + 1 * (n))
#define BF_JRX_CORE_SYNC_N_SEL_INFO(inst, n)                ((inst) + 0x00000110 + 1 * (n)), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_CORE_SYNC_NE_COUNT_ADDR(inst, n)            ((inst) + 0x00000112 + 1 * (n))
#define BF_JRX_CORE_SYNC_NE_COUNT_INFO(inst, n)             ((inst) + 0x00000112 + 1 * (n)), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_CORE_BUF_DEPTH_ADDR(inst, n)                ((inst) + 0x00000114 + 1 * (n))
#define BF_JRX_CORE_BUF_DEPTH_INFO(inst, n)                 ((inst) + 0x00000114 + 1 * (n)), 0x00000800
#endif /* USE_PRIVATE_BF */

#define REG_JRX_CORE_PHASE_ADJUST0_ADDR(inst, n)            ((inst) + 0x00000116 + 1 * (n))
#define BF_JRX_CORE_PHASE_ADJUST_INFO(inst, n)              ((inst) + 0x00000116 + 1 * (n)), 0x00001000

#define REG_JRX_CORE_PHASE_ADJUST1_ADDR(inst, n)            ((inst) + 0x00000118 + 1 * (n))

#define REG_JRX_CORE_LANE_PHASE_DIFF_0_ADDR(inst, n)        ((inst) + 0x0000011B + 1 * (n))
#define BF_JRX_CORE_PHASE_DIFF_INFO(inst, n)                ((inst) + 0x0000011B + 1 * (n)), 0x00001000

#define REG_JRX_CORE_LANE_PHASE_DIFF_1_ADDR(inst, n)        ((inst) + 0x0000013C + 1 * (n))

#define REG_JRX_TPL_CONFIG0_ADDR(inst, n)                   ((inst) + 0x0000015C + 1 * (n))
#ifdef USE_PRIVATE_BF
#define BF_JRX_CORE_CFG_INVALID_INFO(inst, n)               ((inst) + 0x0000015C + 1 * (n)), 0x00000100
#endif /* USE_PRIVATE_BF */
#define BF_JRX_CORE_USR_DATA_RDY_INFO(inst, n)              ((inst) + 0x0000015C + 1 * (n)), 0x00000101
#define BF_JRX_CORE_SYSREF_RCVD_INFO(inst, n)               ((inst) + 0x0000015C + 1 * (n)), 0x00000102
#ifdef USE_PRIVATE_BF
#define BF_JRX_CORE_SYSREF_N_SHOT_ENABLE_INFO(inst, n)      ((inst) + 0x0000015C + 1 * (n)), 0x00000103
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_CORE_SYSREF_N_SHOT_COUNT_INFO(inst, n)       ((inst) + 0x0000015C + 1 * (n)), 0x00000404
#endif /* USE_PRIVATE_BF */

#define REG_JRX_TPL_CONFIG1_ADDR(inst, n)                   ((inst) + 0x0000015E + 1 * (n))
#ifdef USE_PRIVATE_BF
#define BF_JRX_CORE_SYSREF_PHASE_ERR_INFO(inst, n)          ((inst) + 0x0000015E + 1 * (n)), 0x00000100
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_CORE_SYSREF_CLR_PHASE_ERR_INFO(inst, n)      ((inst) + 0x0000015E + 1 * (n)), 0x00000101
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_CORE_SYSREF_IGNORE_WHEN_LINKED_INFO(inst, n) ((inst) + 0x0000015E + 1 * (n)), 0x00000102
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_CORE_SYSREF_ENABLE_INFO(inst, n)             ((inst) + 0x0000015E + 1 * (n)), 0x00000103
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_CORE_SYNC_FORMAT_EN_INFO(inst, n)            ((inst) + 0x0000015E + 1 * (n)), 0x00000104
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_CORE_BUF_ERROR_INFO(inst, n)                 ((inst) + 0x0000015E + 1 * (n)), 0x00000106
#endif /* USE_PRIVATE_BF */
#define BF_JRX_TPL_BUF_ERROR_INFO(inst, n)                  ((inst) + 0x0000015E + 1 * (n)), 0x00000107

#ifdef USE_PRIVATE_BF
#define REG_JRX_TPL_LANE_BUF_DEPTH_A_ADDR(inst, n)          ((inst) + 0x00000160 + 1 * (n))
#define BF_JRX_TPL_BUF_DEPTH_LINK0_INFO(inst, n)            ((inst) + 0x00000160 + 1 * (n)), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_TPL_LANE_BUF_DEPTH_B_ADDR(inst, n)          ((inst) + 0x00000170 + 1 * (n))
#define BF_JRX_TPL_BUF_DEPTH_LINK1_INFO(inst, n)            ((inst) + 0x00000170 + 1 * (n)), 0x00000800
#endif /* USE_PRIVATE_BF */

#define REG_JRX_CORE_LANE_XBAR_A_ADDR(inst, n)              ((inst) + 0x00000180 + 1 * (n))
#define BF_JRX_CORE_LANE_SEL_LINK0_INFO(inst, n)            ((inst) + 0x00000180 + 1 * (n)), 0x00000500
#ifdef USE_PRIVATE_BF
#define BF_JRX_CORE_PCLK_SLOW_ERROR_LINK0_INFO(inst, n)     ((inst) + 0x00000180 + 1 * (n)), 0x00000106
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_CORE_PCLK_FAST_ERROR_LINK0_INFO(inst, n)     ((inst) + 0x00000180 + 1 * (n)), 0x00000107
#endif /* USE_PRIVATE_BF */

#define REG_JRX_CORE_LANE_XBAR_B_ADDR(inst, n)              ((inst) + 0x00000190 + 1 * (n))
#define BF_JRX_CORE_LANE_SEL_LINK1_INFO(inst, n)            ((inst) + 0x00000190 + 1 * (n)), 0x00000500
#ifdef USE_PRIVATE_BF
#define BF_JRX_CORE_PCLK_SLOW_ERROR_LINK1_INFO(inst, n)     ((inst) + 0x00000190 + 1 * (n)), 0x00000106
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_CORE_PCLK_FAST_ERROR_LINK1_INFO(inst, n)     ((inst) + 0x00000190 + 1 * (n)), 0x00000107
#endif /* USE_PRIVATE_BF */

#endif /* __ADI_APOLLO_BF_JRX_CORE_H__ */
/*! @} */
