/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.8 at 7/19/2021 9:28:19 PM.
 * 
 * @copyright copyright(c) 2021 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup APOLLO_BF
 * @{
 */
#ifndef __ADI_APOLLO_BF_ACTRL_SLICE_OPEN_H__
#define __ADI_APOLLO_BF_ACTRL_SLICE_OPEN_H__

/*============= D E F I N E S ==============*/
#define VENUS_ACTRL_SLICE_REGMAP0_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL0 0x60260400
#define VENUS_ACTRL_SLICE_REGMAP1_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL0 0x60260800
#define VENUS_ACTRL_SLICE_REGMAP2_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL0 0x60260C00
#define VENUS_ACTRL_SLICE_REGMAP3_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL0 0x60261000
#define VENUS_ACTRL_SLICE_REGMAP4_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL0 0x60261400
#define VENUS_ACTRL_SLICE_REGMAP5_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL0 0x60261800
#define VENUS_ACTRL_SLICE_REGMAP6_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL0 0x60261C00
#define VENUS_ACTRL_SLICE_REGMAP7_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL0 0x60262000
#define VENUS_ACTRL_SLICE_REGMAP0_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL0 0x60460400
#define VENUS_ACTRL_SLICE_REGMAP1_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL0 0x60460800
#define VENUS_ACTRL_SLICE_REGMAP2_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL0 0x60460C00
#define VENUS_ACTRL_SLICE_REGMAP3_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL0 0x60461000
#define VENUS_ACTRL_SLICE_REGMAP4_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL0 0x60461400
#define VENUS_ACTRL_SLICE_REGMAP5_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL0 0x60461800
#define VENUS_ACTRL_SLICE_REGMAP6_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL0 0x60461C00
#define VENUS_ACTRL_SLICE_REGMAP7_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL0 0x60462000
#define VENUS_ACTRL_SLICE_REGMAP0_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL1 0x60A60400
#define VENUS_ACTRL_SLICE_REGMAP1_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL1 0x60A60800
#define VENUS_ACTRL_SLICE_REGMAP2_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL1 0x60A60C00
#define VENUS_ACTRL_SLICE_REGMAP3_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL1 0x60A61000
#define VENUS_ACTRL_SLICE_REGMAP4_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL1 0x60A61400
#define VENUS_ACTRL_SLICE_REGMAP5_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL1 0x60A61800
#define VENUS_ACTRL_SLICE_REGMAP6_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL1 0x60A61C00
#define VENUS_ACTRL_SLICE_REGMAP7_ADC8_ANALOG_REGS_RX_SLICE_0_RX_DIGITAL1 0x60A62000
#define VENUS_ACTRL_SLICE_REGMAP0_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL1 0x60C60400
#define VENUS_ACTRL_SLICE_REGMAP1_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL1 0x60C60800
#define VENUS_ACTRL_SLICE_REGMAP2_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL1 0x60C60C00
#define VENUS_ACTRL_SLICE_REGMAP3_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL1 0x60C61000
#define VENUS_ACTRL_SLICE_REGMAP4_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL1 0x60C61400
#define VENUS_ACTRL_SLICE_REGMAP5_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL1 0x60C61800
#define VENUS_ACTRL_SLICE_REGMAP6_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL1 0x60C61C00
#define VENUS_ACTRL_SLICE_REGMAP7_ADC8_ANALOG_REGS_RX_SLICE_1_RX_DIGITAL1 0x60C62000

#define REG_ACTRL_SCRATCH_BEGIN_ACTRL_SLICE__OPEN_ADDR(inst)              ((inst) + 0x00000000)
#define BF_ACTRL_SCRATCH_BEGIN_ACTRL_SLICE__OPEN_INFO(inst)               ((inst) + 0x00000000), 0x00000800

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0001_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000001)
#define BF_BF_5EB08FA9_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000001), 0x00000100
#define BF_BF_126EB5D8_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000001), 0x00000101
#define BF_BF_D1919DE4_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000001), 0x00000102
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0002_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000002)
#define BF_BF_A252E209_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000002), 0x00000100
#define BF_BF_EC0570A1_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000002), 0x00000101
#define BF_BF_9EC08343_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000002), 0x00000102
#define BF_BF_DD32CEDB_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000002), 0x00000103
#define BF_BF_889162C1_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000002), 0x00000104
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0003_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000003)
#define BF_BF_A6D3CBFE_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000003), 0x00000101
#define BF_BF_4018413E_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000003), 0x00000102
#define BF_BF_2D63C129_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000003), 0x00000103
#define BF_BF_339349E3_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000003), 0x00000104
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0004_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000004)
#define BF_BF_AA4FF39E_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000004), 0x00000100
#define BF_BF_001B22C8_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000004), 0x00000101
#define BF_BF_2EAD4958_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000004), 0x00000102
#define BF_BF_0CD0A002_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000004), 0x00000103
#define BF_BF_458B15CA_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000004), 0x00000104
#define BF_BF_99E768C7_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000004), 0x00000105
#define BF_BF_09247BC9_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000004), 0x00000106
#define BF_BF_D9B5E6DC_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000004), 0x00000107
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0005_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000005)
#define BF_BF_4A1CE9FD_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000005), 0x00000100
#define BF_BF_2FB6FEB1_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000005), 0x00000304
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0006_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000006)
#define BF_BF_B1275EF4_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000006), 0x00000100
#define BF_BF_2B4D955F_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000006), 0x00000304
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0007_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000007)
#define BF_BF_D6F9511E_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000007), 0x00000100
#define BF_BF_B2A878C7_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000007), 0x00000304
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0008_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000008)
#define BF_BF_879E702A_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000008), 0x00000100
#define BF_BF_EE1E3FD5_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000008), 0x00000304
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0009_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000009)
#define BF_BF_9F65E970_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000009), 0x00000100
#define BF_BF_9C76E371_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000009), 0x00000404
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X000A_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000000A)
#define BF_BF_4B2ABE3F_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000A), 0x00000100
#define BF_BF_CA3810E7_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000A), 0x00000101
#define BF_BF_7BE4DF0B_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000A), 0x00000102
#define BF_BF_B950B3D9_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000A), 0x00000103
#define BF_BF_03899053_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000A), 0x00000104
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X000B_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000000B)
#define BF_BF_47AD4A09_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000B), 0x00000400
#define BF_BF_C278F62B_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000B), 0x00000304
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X000C_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000000C)
#define BF_BF_4AFC5970_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000C), 0x00000400
#define BF_BF_DC4BD305_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000C), 0x00000304
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X000D_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000000D)
#define BF_BF_AD50EA09_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000D), 0x00000400
#define BF_BF_6B9EF517_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000D), 0x00000304
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X000E_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000000E)
#define BF_BF_31AECD11_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000E), 0x00000400
#define BF_BF_7D3754EB_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000E), 0x00000304
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X000F_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000000F)
#define BF_BF_FE1DA073_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000F), 0x00000400
#define BF_BF_B5F7486C_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000000F), 0x00000404
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0010_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000010)
#define BF_BF_B866A4AB_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000010), 0x00000100
#define BF_BF_DE6A013F_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000010), 0x00000101
#define BF_BF_FD8BEC76_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000010), 0x00000102
#define BF_BF_E582A0EB_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000010), 0x00000103
#define BF_BF_38088E6C_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000010), 0x00000104
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0011_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000011)
#define BF_BF_5587D278_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000011), 0x00000400
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0012_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000012)
#define BF_BF_F0273B9A_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000012), 0x00000400
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0013_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000013)
#define BF_BF_954D455E_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000013), 0x00000400
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0014_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000014)
#define BF_BF_E4A95397_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000014), 0x00000400
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0015_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000015)
#define BF_BF_F908A4B7_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000015), 0x00000400
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0016_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000016)
#define BF_BF_8DCABC6F_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000016), 0x00000200
#define BF_BF_46B72E84_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000016), 0x00000202
#define BF_BF_8AF0C451_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000016), 0x00000204
#define BF_BF_FF501E2E_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000016), 0x00000206
#endif /* USE_PRIVATE_BF */

#define REG_REG_0X0017_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000017)
#ifdef USE_PRIVATE_BF
#define BF_BF_77037A43_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000017), 0x00000100
#endif /* USE_PRIVATE_BF */
#define BF_BF_77037A43_WEB_ACTRL_SLICE__OPEN_INFO(inst)                   ((inst) + 0x00000017), 0x00000101
#ifdef USE_PRIVATE_BF
#define BF_BF_DC5FC06D_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000017), 0x00000102
#endif /* USE_PRIVATE_BF */
#define BF_BF_DC5FC06D_WEB_ACTRL_SLICE__OPEN_INFO(inst)                   ((inst) + 0x00000017), 0x00000103
#ifdef USE_PRIVATE_BF
#define BF_BF_6B686F5F_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000017), 0x00000304
#endif /* USE_PRIVATE_BF */
#define BF_BF_6B686F5F_WEB_ACTRL_SLICE__OPEN_INFO(inst)                   ((inst) + 0x00000017), 0x00000107

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0018_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000018)
#define BF_BF_FE5D14F7_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000018), 0x00000100
#define BF_BF_293203CE_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000018), 0x00000101
#define BF_BF_1F8B49FB_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000018), 0x00000302
#define BF_BF_BC94FEB9_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000018), 0x00000105
#define BF_BF_4932BE36_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000018), 0x00000106
#define BF_BF_15542900_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000018), 0x00000107
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0019_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000019)
#define BF_BF_6E624734_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000019), 0x00000100
#define BF_BF_3451B00C_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000019), 0x00000101
#define BF_BF_11F6B22B_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000019), 0x00000302
#define BF_BF_D74C5E45_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000019), 0x00000105
#define BF_BF_85370402_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000019), 0x00000106
#define BF_BF_4E3ABDB0_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000019), 0x00000107
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X001A_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000001A)
#define BF_BF_DBD9054E_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000001A), 0x00000100
#define BF_BF_8FEFCFA2_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000001A), 0x00000101
#define BF_BF_E209801C_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000001A), 0x00000302
#define BF_BF_22202CD7_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000001A), 0x00000105
#define BF_BF_3D738581_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000001A), 0x00000106
#define BF_BF_46D7DA69_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000001A), 0x00000107
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X001B_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000001B)
#define BF_BF_6F58C319_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000001B), 0x00000100
#define BF_BF_D436DB2D_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000001B), 0x00000101
#define BF_BF_4F00CCC9_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000001B), 0x00000302
#define BF_BF_87949627_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000001B), 0x00000105
#define BF_BF_C86E3FED_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000001B), 0x00000106
#define BF_BF_30A1F19E_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000001B), 0x00000107
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X001C_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000001C)
#define BF_BF_A5738686_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000001C), 0x00002400
#endif /* USE_PRIVATE_BF */

#define REG_REG_0X001D_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000001D)

#define REG_REG_0X001E_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000001E)

#define REG_REG_0X001F_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000001F)

#define REG_REG_0X0020_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000020)

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0021_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000021)
#define BF_BF_3A967583_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000021), 0x00000200
#define BF_BF_55B25744_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000021), 0x00000202
#define BF_BF_6F32B7D5_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000021), 0x00000204
#define BF_BF_4F85E59F_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000021), 0x00000206
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0022_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000022)
#define BF_BF_8B5D9414_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000022), 0x00000200
#define BF_BF_891B6811_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000022), 0x00000202
#define BF_BF_ECCF50C4_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000022), 0x00000204
#define BF_BF_C32291CF_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000022), 0x00000206
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0023_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000023)
#define BF_BF_7A13FD19_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000023), 0x00000200
#define BF_BF_C5D1868C_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000023), 0x00000304
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0024_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000024)
#define BF_BF_8701A65A_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000024), 0x00000200
#define BF_BF_14DF43FB_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000024), 0x00000202
#define BF_BF_C35798E6_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000024), 0x00000204
#define BF_BF_455E4600_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000024), 0x00000206
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0025_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000025)
#define BF_BF_1AD3C3B4_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000025), 0x00000200
#define BF_BF_C13F473C_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000025), 0x00000202
#define BF_BF_D167EABD_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000025), 0x00000204
#define BF_BF_C8945FBC_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000025), 0x00000206
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0026_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000026)
#define BF_BF_2BD68F04_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000026), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0027_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000027)
#define BF_BF_6F0E76C0_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000027), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0028_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000028)
#define BF_BF_1DECF0B5_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000028), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X0029_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x00000029)
#define BF_BF_C5EBC8EF_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x00000029), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X002A_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000002A)
#define BF_BF_C9878C07_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000002A), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_REG_0X002B_ACTRL_SLICE__OPEN_ADDR(inst)                       ((inst) + 0x0000002B)
#define BF_BF_A8BAEFD3_ACTRL_SLICE__OPEN_INFO(inst)                       ((inst) + 0x0000002B), 0x00000800
#endif /* USE_PRIVATE_BF */

#define REG_ACTRL_SCRATCH_END_ACTRL_SLICE__OPEN_ADDR(inst)                ((inst) + 0x000003FF)
#define BF_ACTRL_SCRATCH_END_ACTRL_SLICE__OPEN_INFO(inst)                 ((inst) + 0x000003FF), 0x00000800

#endif /* __ADI_APOLLO_BF_ACTRL_SLICE_OPEN_H__ */
/*! @} */
