# Uncomment to use the desired platform
# PLATFORM = xilinx
# PLATFORM = stm32

EXAMPLE ?= iio

# AD4630 Family = 0 | AD4030 Family = 1 | ADAQ4224 = 2 | ADAQ4216 = 3 | AD4630-20 Family = 4
AD463X_ID=0

include ../../tools/scripts/generic_variables.mk

include ../../tools/scripts/examples.mk

include src.mk

include ../../tools/scripts/generic.mk
