IIOD=y
# Choose the device
# AD4630 Family = 0 | AD4030 Family = 1 | ADAQ4224 = 2
AD463X_ID=2

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
