# Uncomment to use the desired platform
# PLATFORM = xilinx
# PLATFORM = stm32

# Select the example you want to enable by choosing y for enabling and n for disabling
BASIC_EXAMPLE = n
IIO_EXAMPLE = y

# AD4630 Family = 0 | AD4030 Family = 1 | ADAQ4224 = 2
AD463X_ID=0

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
