## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/fmcjesdadc1/vc707/fmcjesdadc1_vc707.sdk/system_top.hdf

include $(NOOS-DIR)/ad-fmcjesdadc1-ebz/ad-fmcjesdadc1-ebz.mk

include $(NOOS-DIR)/scripts/microblaze.mk

