include ../../tools/scripts/generic_variables.mk

USER_INCLUDES = /home/dari/Work/libiio/include /home/dari/Work/libiio /home/dari/Work/libiio/build
EXTRA_LIBS = libtinyiiod.a libiio.a iiod-responder.a
EXTRA_LIBS_PATHS = /home/dari/Work/libiio/build/tinyiiod /home/dari/Work/libiio/build

include src.mk

include ../../tools/scripts/generic.mk
