## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/fmcadc5/vc707/fmcadc5_vc707.sdk/system_top.hdf

include $(NOOS-DIR)/fmcadc5/fmcadc5.mk
include $(NOOS-DIR)/scripts/microblaze.mk

