/** 
 * \file fpgagen6_bf_error_types.h Automatically generated file with generator ver 0.0.16.0.
 * 
 * \brief Contains BitField functions to support FPGAGEN6 transceiver device.
 * 
 * FPGAGEN6 BITFIELD VERSION: 0.0.0.11
 * 
 * Disclaimer Legal Disclaimer
 * 
 * Copyright 2015 - 2023 Analog Devices Inc.
 * 
 * Released under the FPGAGEN6 API license, for more information see the "LICENSE.PDF" file in this zip file.
 */

#ifndef _FPGAGEN6_BF_ERROR_TYPES_H_
#define _FPGAGEN6_BF_ERROR_TYPES_H_

typedef enum
{
    ADI_FPGAGEN6_FILE_PRIVATE_BF_ADRV904X_ADS10 = 600U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_XILINX_I2C = 601U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_ADS10V1_TOP = 602U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_AXI_ADS10V1 = 603U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_XILINX_GPIO = 604U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_AXI_MEMORY_PAGER = 605U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_AXI_RXDMA = 606U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_AXI_TXDMA = 607U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_AXI_ADV_SPI = 608U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_ADRV904X_TOP = 609U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_ADRV904X_TDD = 610U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_ADRV904X_SYSTEM_TIMING_CONTROL = 611U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_ADRV904X_SYSTEM_TIMING = 612U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_XILINX_CLOCK_WIZARD = 613U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_AXI_ADRV904X_PHY = 614U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_AXI_ADRV904X = 615U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_XILINX_JESD = 616U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_AXI_ADRV904X_RX = 617U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_AXI_ADRV904X_TX = 618U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_AXI_ADRV904X_GPIO = 619U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_ADRV904X_ADS10_SHIM_TEST_MODES = 620U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_ADRV904X_ADS10_SHIM = 621U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_ADRV904X_ADS10_SHIM_TX_DATA_PATH = 622U,
    ADI_FPGAGEN6_FILE_PRIVATE_BF_PROJECT_VERSION = 623U
} fpgagen6_File_e;

#endif // _FPGAGEN6_BF_ERROR_TYPES_H_

