## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/fmcomms2/zc702/fmcomms2_zc702.sdk/system_top.hdf

include $(NOOS-DIR)/fmcomms2/fmcomms2.mk
include $(NOOS-DIR)/scripts/zynq_ps7.mk

