## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/adrv9371x/zc706/adrv9371x_zc706.sdk/system_top.hdf

include $(NOOS-DIR)/adrv9371x/adrv9371x.mk
include $(NOOS-DIR)/scripts/zynq.mk

