## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/dac_fmc_ebz/zc706/dac_fmc_ebz_zc706.sdk/system_top.hdf

include $(NOOS-DIR)/ad9144-fmc-ebz/ad9144-fmc-ebz.mk
include $(NOOS-DIR)/scripts/zynq_ps7.mk

