# Uncomment to use the desired platform
# PLATFORM = xilinx

# Select the example you want to enable by choosing y for enabling and n for disabling
IIO_EXAMPLE = y
BASIC_EXAMPLE = n

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
