
INCS += $(PLATFORM_DRIVERS)/$(PLATFORM)_i2c.h		\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_uart.h

SRCS += $(PLATFORM_DRIVERS)/$(PLATFORM)_delay.c		\
        $(PLATFORM_DRIVERS)/$(PLATFORM)_i2c.c		\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_uart.c
