# Select the example you want to enable by chossing y for enabling and n for disabling
BASIC_EXAMPLE = n
IIO_EXAMPLE = y

#select part number to use: adaq7767-1, adaq7768-1, adaq7769-1
ADAQ776x_DEV = adaq7769-1

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
