CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_UART=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_DMA=y
CONFIG_TIMER=y
CONFIG_IIO=y
CONFIG_LWIP=y
CONFIG_NET=y
CONFIG_ADIN1110=y
CONFIG_ADC_DAC=y
CONFIG_ADC_DAC_AD74413R=y
CONFIG_ADC_DAC_IIO_AD74413R=y
CONFIG_DIGITAL_IO=y
CONFIG_DIGITAL_IO_MAX14906=y
CONFIG_DIGITAL_IO_IIO_MAX14906=y
CONFIG_TEMPERATURE=y
CONFIG_TEMPERATURE_ADT75=y
CONFIG_TEMPERATURE_IIO_ADT75=y
CONFIG_SWIOT1L_DEFAULT_FW=y
