CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_UART=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_DMA=y
CONFIG_TIMER=y
CONFIG_IIO=y
CONFIG_LWIP=y
CONFIG_NO_OS_LWIP_INIT_ONETIME=y
CONFIG_NO_OS_DOMAIN_NAME="swiot1l"
CONFIG_NET=y
CONFIG_ADIN1110=y
CONFIG_ADC_DAC=y
CONFIG_ADC_DAC_AD74413R=y
CONFIG_ADC_DAC_IIO_AD74413R=y
CONFIG_DIGITAL_IO=y
CONFIG_DIGITAL_IO_MAX14906=y
CONFIG_DIGITAL_IO_IIO_MAX14906=y
CONFIG_TEMPERATURE=y
CONFIG_TEMPERATURE_ADT75=y
CONFIG_TEMPERATURE_IIO_ADT75=y
CONFIG_SWIOT1L_DEFAULT_FW=y

CONFIG_SWIOT1L_STATIC_IP=n
CONFIG_NO_OS_IP="192.168.97.40"
CONFIG_NO_OS_NETMASK="255.255.0.0"
CONFIG_NO_OS_GATEWAY="0.0.0.0"
