## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/fmcadc2/zc706/fmcadc2_zc706.sdk/system_top.hdf

include $(NOOS-DIR)/fmcadc2/fmcadc2.mk
include $(NOOS-DIR)/scripts/zynq.mk

