CONFIG_UART=y
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_IIO=y
CONFIG_DAC=y
CONFIG_DAC_IIO_AD5791=y
CONFIG_CN0531_IIO_EXAMPLE=y
CONFIG_CN0531_NETWORKING=y
CONFIG_WIFI_SSID="RouterSSID"
CONFIG_WIFI_PWD="******"
