EXAMPLE ?= iio_example

CONFIG_USB_UART_MAXIM = y
IIOD = y

include ../../tools/scripts/generic_variables.mk

include ../../tools/scripts/examples.mk

include src.mk

include ../../tools/scripts/generic.mk
