/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.8 at 2/15/2023 10:39:23 AM.
 * 
 * @copyright copyright(c) 2023 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup APOLLO_BF
 * @{
 */
#ifndef __ADI_APOLLO_BF_TXRX_FINE_NCO_H__
#define __ADI_APOLLO_BF_TXRX_FINE_NCO_H__

/*============= D E F I N E S ==============*/
#define RX_FINE_NCO0_RX_SLICE_0_RX_DIGITAL0                         0x603AA000
#define RX_FINE_NCO1_RX_SLICE_0_RX_DIGITAL0                         0x603AB000
#define RX_FINE_NCO2_RX_SLICE_0_RX_DIGITAL0                         0x603AC000
#define RX_FINE_NCO3_RX_SLICE_0_RX_DIGITAL0                         0x603AD000
#define RX_FINE_NCO0_RX_SLICE_1_RX_DIGITAL0                         0x605AA000
#define RX_FINE_NCO1_RX_SLICE_1_RX_DIGITAL0                         0x605AB000
#define RX_FINE_NCO2_RX_SLICE_1_RX_DIGITAL0                         0x605AC000
#define RX_FINE_NCO3_RX_SLICE_1_RX_DIGITAL0                         0x605AD000
#define RX_FINE_NCO0_RX_SLICE_0_RX_DIGITAL1                         0x60BAA000
#define RX_FINE_NCO1_RX_SLICE_0_RX_DIGITAL1                         0x60BAB000
#define RX_FINE_NCO2_RX_SLICE_0_RX_DIGITAL1                         0x60BAC000
#define RX_FINE_NCO3_RX_SLICE_0_RX_DIGITAL1                         0x60BAD000
#define RX_FINE_NCO0_RX_SLICE_1_RX_DIGITAL1                         0x60DAA000
#define RX_FINE_NCO1_RX_SLICE_1_RX_DIGITAL1                         0x60DAB000
#define RX_FINE_NCO2_RX_SLICE_1_RX_DIGITAL1                         0x60DAC000
#define RX_FINE_NCO3_RX_SLICE_1_RX_DIGITAL1                         0x60DAD000
#define TX_FINE_NCO0_TX_SLICE_0_TX_DIGITAL0                         0x61309000
#define TX_FINE_NCO1_TX_SLICE_0_TX_DIGITAL0                         0x6130A000
#define TX_FINE_NCO2_TX_SLICE_0_TX_DIGITAL0                         0x6130B000
#define TX_FINE_NCO3_TX_SLICE_0_TX_DIGITAL0                         0x6130C000
#define TX_FINE_NCO0_TX_SLICE_1_TX_DIGITAL0                         0x61509000
#define TX_FINE_NCO1_TX_SLICE_1_TX_DIGITAL0                         0x6150A000
#define TX_FINE_NCO2_TX_SLICE_1_TX_DIGITAL0                         0x6150B000
#define TX_FINE_NCO3_TX_SLICE_1_TX_DIGITAL0                         0x6150C000
#define TX_FINE_NCO0_TX_SLICE_0_TX_DIGITAL1                         0x61B09000
#define TX_FINE_NCO1_TX_SLICE_0_TX_DIGITAL1                         0x61B0A000
#define TX_FINE_NCO2_TX_SLICE_0_TX_DIGITAL1                         0x61B0B000
#define TX_FINE_NCO3_TX_SLICE_0_TX_DIGITAL1                         0x61B0C000
#define TX_FINE_NCO0_TX_SLICE_1_TX_DIGITAL1                         0x61D09000
#define TX_FINE_NCO1_TX_SLICE_1_TX_DIGITAL1                         0x61D0A000
#define TX_FINE_NCO2_TX_SLICE_1_TX_DIGITAL1                         0x61D0B000
#define TX_FINE_NCO3_TX_SLICE_1_TX_DIGITAL1                         0x61D0C000

#define REG_FINE_NCO_CLK_CTRL_ADDR(inst)                            ((inst) + 0x00000000)
#define BF_FINE_DRC_EN0_INFO(inst)                                  ((inst) + 0x00000000), 0x00000100
#ifdef USE_PRIVATE_BF
#define BF_CLK_OFFSET_WR_EN_TXRX_FINE_NCO_INFO(inst)                ((inst) + 0x00000000), 0x00000102
#endif /* USE_PRIVATE_BF */
#define BF_FDRC_CLK_EN_INFO(inst)                                   ((inst) + 0x00000000), 0x00000103

#ifdef USE_PRIVATE_BF
#define REG_FINE_BASE_OFFSET_TXRX_FINE_NCO_ADDR(inst)               ((inst) + 0x00000001)
#define BF_DRC_BASE_OFFSET_INFO(inst)                               ((inst) + 0x00000001), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_FINE_I_MXR_OFFSET_ADDR(inst)                            ((inst) + 0x00000002)
#define BF_FINE_I_MXR_OFFSET_INFO(inst)                             ((inst) + 0x00000002), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_FINE_Q_MXR_OFFSET_ADDR(inst)                            ((inst) + 0x00000003)
#define BF_FINE_Q_MXR_OFFSET_INFO(inst)                             ((inst) + 0x00000003), 0x00000800
#endif /* USE_PRIVATE_BF */

#define REG_FINE_MXR_CTRL_ADDR(inst)                                ((inst) + 0x00000004)
#define BF_DRC_IF_MODE_TXRX_FINE_NCO_INFO(inst)                     ((inst) + 0x00000004), 0x00000200
#define BF_DRC_MXR_SEL_INFO(inst)                                   ((inst) + 0x00000004), 0x00000102
#define BF_CMPLX_MXR_MULT_SCALE_EN_INFO(inst)                       ((inst) + 0x00000004), 0x00000103

#ifdef USE_PRIVATE_BF
#define REG_ARAMP_INC_DEC_PROFNUM_ADDR(inst)                        ((inst) + 0x00000005)
#define BF_ARAMP_INC_PROFNUM_INFO(inst)                             ((inst) + 0x00000005), 0x00000400
#define BF_ARAMP_DEC_PROFNUM_INFO(inst)                             ((inst) + 0x00000005), 0x00000404
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_FRAMP_ARAMP_DIR_ADDR(inst)                              ((inst) + 0x00000006)
#define BF_FRAMP_DIR_INFO(inst)                                     ((inst) + 0x00000006), 0x00000100
#define BF_FRAMP_DIR_AUTOFLIP_INFO(inst)                            ((inst) + 0x00000006), 0x00000101
#define BF_ARAMP_DIR_INFO(inst)                                     ((inst) + 0x00000006), 0x00000102
#define BF_ARAMP_DIR_AUTOFLIP_INFO(inst)                            ((inst) + 0x00000006), 0x00000103
#define BF_SYMM_ARAMP_INFO(inst)                                    ((inst) + 0x00000006), 0x00000104
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_FRAMP_INC_PROFNUM_ADDR(inst)                            ((inst) + 0x00000007)
#define BF_FRAMP_INC_PROFNUM_INFO(inst)                             ((inst) + 0x00000007), 0x00000500
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_FRAMP_DEC_PROFNUM_ADDR(inst)                            ((inst) + 0x00000008)
#define BF_FRAMP_DEC_PROFNUM_INFO(inst)                             ((inst) + 0x00000008), 0x00000500
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_ARAMP_SCALE_EN_ADDR(inst)                               ((inst) + 0x00000015)
#define BF_ARAMP_SCALE_EN_INFO(inst)                                ((inst) + 0x00000015), 0x00000100
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_ARAMP_UPDTRATE0_ADDR(inst)                              ((inst) + 0x00000016)
#define BF_ARAMP_UPDTRATE0_INFO(inst)                               ((inst) + 0x00000016), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_ARAMP_UPDTRATE1_ADDR(inst)                              ((inst) + 0x00000017)
#define BF_ARAMP_UPDTRATE1_INFO(inst)                               ((inst) + 0x00000017), 0x00000800
#endif /* USE_PRIVATE_BF */

#define REG_AUTOFLIP_INCDIR_ADDR(inst)                              ((inst) + 0x00000018)
#define BF_AUTOFLIP_INCDIR_TXRX_FINE_NCO_INFO(inst)                 ((inst) + 0x00000018), 0x00000600

#define REG_AUTO_INC_DECB_ADDR(inst)                                ((inst) + 0x00000019)
#define BF_AUTO_INC_DECB_TXRX_FINE_NCO_INFO(inst)                   ((inst) + 0x00000019), 0x00000600

#define REG_CHDIR_INT_STATUS_ADDR(inst)                             ((inst) + 0x0000001A)
#define BF_CHDIR_INT_STATUS_TXRX_FINE_NCO_INFO(inst)                ((inst) + 0x0000001A), 0x00000600

#define REG_DRC_ACTIVE_PHASE_INC0_TXRX_FINE_NCO_ADDR(inst)          ((inst) + 0x0000001B)
#define BF_DRC0_ACTIVE_PHASE_INC_INFO(inst)                         ((inst) + 0x0000001B), 0x00003000

#define REG_DRC_ACTIVE_PHASE_INC1_TXRX_FINE_NCO_ADDR(inst)          ((inst) + 0x0000001C)

#define REG_DRC_ACTIVE_PHASE_INC2_TXRX_FINE_NCO_ADDR(inst)          ((inst) + 0x0000001D)

#define REG_DRC_ACTIVE_PHASE_INC3_TXRX_FINE_NCO_ADDR(inst)          ((inst) + 0x0000001E)

#define REG_DRC_ACTIVE_PHASE_INC4_ADDR(inst)                        ((inst) + 0x0000001F)

#define REG_DRC_ACTIVE_PHASE_INC5_ADDR(inst)                        ((inst) + 0x00000020)

#define REG_DRC_ACTIVE_PHASE_OFFSET0_TXRX_FINE_NCO_ADDR(inst)       ((inst) + 0x00000021)
#define BF_DRC0_ACTIVE_PHASE_OFFSET_INFO(inst)                      ((inst) + 0x00000021), 0x00003000

#define REG_DRC_ACTIVE_PHASE_OFFSET1_TXRX_FINE_NCO_ADDR(inst)       ((inst) + 0x00000022)

#define REG_DRC_ACTIVE_PHASE_OFFSET2_TXRX_FINE_NCO_ADDR(inst)       ((inst) + 0x00000023)

#define REG_DRC_ACTIVE_PHASE_OFFSET3_TXRX_FINE_NCO_ADDR(inst)       ((inst) + 0x00000024)

#define REG_DRC_ACTIVE_PHASE_OFFSET4_ADDR(inst)                     ((inst) + 0x00000025)

#define REG_DRC_ACTIVE_PHASE_OFFSET5_ADDR(inst)                     ((inst) + 0x00000026)

#define REG_DRC_DITHER_TXRX_FINE_NCO_ADDR(inst)                     ((inst) + 0x00000027)
#define BF_DRC0_AMP_DITHER_EN_INFO(inst)                            ((inst) + 0x00000027), 0x00000100
#define BF_DRC0_PHASE_DITHER_EN_INFO(inst)                          ((inst) + 0x00000027), 0x00000101

#define REG_DRC_PHASE_INC_FRAC_A0_TXRX_FINE_NCO_ADDR(inst)          ((inst) + 0x00000028)
#define BF_DRC0_PHASE_INC_FRAC_A_INFO(inst)                         ((inst) + 0x00000028), 0x00001800

#define REG_DRC_PHASE_INC_FRAC_A1_TXRX_FINE_NCO_ADDR(inst)          ((inst) + 0x00000029)

#define REG_DRC_PHASE_INC_FRAC_A2_TXRX_FINE_NCO_ADDR(inst)          ((inst) + 0x0000002A)

#define REG_DRC_PHASE_INC_FRAC_B0_TXRX_FINE_NCO_ADDR(inst)          ((inst) + 0x0000002E)
#define BF_DRC0_PHASE_INC_FRAC_B_INFO(inst)                         ((inst) + 0x0000002E), 0x00001800

#define REG_DRC_PHASE_INC_FRAC_B1_TXRX_FINE_NCO_ADDR(inst)          ((inst) + 0x0000002F)

#define REG_DRC_PHASE_INC_FRAC_B2_TXRX_FINE_NCO_ADDR(inst)          ((inst) + 0x00000030)

#define REG_DUTY_CYCLE0_ADDR(inst)                                  ((inst) + 0x00000034)
#define BF_DUTY_CYCLE0_INFO(inst)                                   ((inst) + 0x00000034), 0x00000800

#define REG_DUTY_CYCLE1_ADDR(inst)                                  ((inst) + 0x00000035)
#define BF_DUTY_CYCLE1_INFO(inst)                                   ((inst) + 0x00000035), 0x00000800

#define REG_NCO_COHRENCE_CTRL_ADDR(inst)                            ((inst) + 0x00000036)
#define BF_FREQ_COHRNCE_TXRX_FINE_NCO_INFO(inst)                    ((inst) + 0x00000036), 0x00000200
#ifdef USE_PRIVATE_BF
#define BF_FJMP_COHRNCE_INFO(inst)                                  ((inst) + 0x00000036), 0x00000202
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_FSTOP_COHRNCE_INFO(inst)                                 ((inst) + 0x00000036), 0x00000204
#endif /* USE_PRIVATE_BF */
#define BF_NCORST_COHRNCE_INFO(inst)                                ((inst) + 0x00000036), 0x00000106

#define REG_INTERRUPT_OUT_ADDR(inst)                                ((inst) + 0x00000037)
#define BF_INTERRUPT_OUT_INFO(inst)                                 ((inst) + 0x00000037), 0x00000100
#ifdef USE_PRIVATE_BF
#define BF_FRMP_ERR_INTRPT_INFO(inst)                               ((inst) + 0x00000037), 0x00000101
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_FRAMP_ERR_INTRP_CLR_ADDR(inst)                          ((inst) + 0x00000038)
#define BF_FRMP_ERR_INTRPT_CLR_INFO(inst)                           ((inst) + 0x00000038), 0x00000100
#endif /* USE_PRIVATE_BF */

#define REG_GPIO_HOP_ADDR(inst)                                     ((inst) + 0x00000039)
#define BF_GPIO_ALL_HOP_INFO(inst)                                  ((inst) + 0x00000039), 0x00000100
#define BF_TXRX_GPIOSHARE_INFO(inst)                                ((inst) + 0x00000039), 0x00000101

#ifdef USE_PRIVATE_BF
#define REG_HOP_AMP0_ADDR(inst)                                     ((inst) + 0x0000003A)
#define BF_HOP_AMP0_INFO(inst)                                      ((inst) + 0x0000003A), 0x00000400
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_AMP1_ADDR(inst)                                     ((inst) + 0x0000003B)
#define BF_HOP_AMP1_INFO(inst)                                      ((inst) + 0x0000003B), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_AMP_INCR0_ADDR(inst)                                ((inst) + 0x0000003C)
#define BF_HOP_AMP_INCR0_INFO(inst)                                 ((inst) + 0x0000003C), 0x00000400
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_AMP_INCR1_ADDR(inst)                                ((inst) + 0x0000003D)
#define BF_HOP_AMP_INCR1_INFO(inst)                                 ((inst) + 0x0000003D), 0x00000800
#endif /* USE_PRIVATE_BF */

#define REG_HOP_CTRL_ADDR(inst)                                     ((inst) + 0x0000003E)
#define BF_HOP_MODE_EN_INFO(inst)                                   ((inst) + 0x0000003E), 0x00000100
#define BF_HOP_MODE_INFO(inst)                                      ((inst) + 0x0000003E), 0x00000301
#define BF_HOP_CTRL_INIT_TXRX_FINE_NCO_INFO(inst)                   ((inst) + 0x0000003E), 0x00000104

#ifdef USE_PRIVATE_BF
#define REG_HOP_FDECR0_ADDR(inst)                                   ((inst) + 0x0000003F)
#define BF_HOP_FDECR0_INFO(inst)                                    ((inst) + 0x0000003F), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_FDECR1_ADDR(inst)                                   ((inst) + 0x00000040)
#define BF_HOP_FDECR1_INFO(inst)                                    ((inst) + 0x00000040), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_FDECR2_ADDR(inst)                                   ((inst) + 0x00000041)
#define BF_HOP_FDECR2_INFO(inst)                                    ((inst) + 0x00000041), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_FDECR3_ADDR(inst)                                   ((inst) + 0x00000042)
#define BF_HOP_FDECR3_INFO(inst)                                    ((inst) + 0x00000042), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_FINCR0_ADDR(inst)                                   ((inst) + 0x00000043)
#define BF_HOP_FINCR0_INFO(inst)                                    ((inst) + 0x00000043), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_FINCR1_ADDR(inst)                                   ((inst) + 0x00000044)
#define BF_HOP_FINCR1_INFO(inst)                                    ((inst) + 0x00000044), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_FINCR2_ADDR(inst)                                   ((inst) + 0x00000045)
#define BF_HOP_FINCR2_INFO(inst)                                    ((inst) + 0x00000045), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_FINCR3_ADDR(inst)                                   ((inst) + 0x00000046)
#define BF_HOP_FINCR3_INFO(inst)                                    ((inst) + 0x00000046), 0x00000800
#endif /* USE_PRIVATE_BF */

#define REG_HOP_HIGHLIMIT_PR0_ADDR(inst)                            ((inst) + 0x00000047)
#define BF_HOP_HIGHLIMIT_PR0_INFO(inst)                             ((inst) + 0x00000047), 0x00000600

#ifdef USE_PRIVATE_BF
#define REG_HOP_HIGHLIMIT_PR1_ADDR(inst)                            ((inst) + 0x00000048)
#define BF_HOP_HIGHLIMIT_PR1_INFO(inst)                             ((inst) + 0x00000048), 0x00000600
#endif /* USE_PRIVATE_BF */

#define REG_HOP_HIGHLIMIT_PR2_ADDR(inst)                            ((inst) + 0x00000049)
#define BF_HOP_HIGHLIMIT_PR2_INFO(inst)                             ((inst) + 0x00000049), 0x00000600

#ifdef USE_PRIVATE_BF
#define REG_HOP_HIGHLIMIT_PR3_ADDR(inst)                            ((inst) + 0x0000004A)
#define BF_HOP_HIGHLIMIT_PR3_INFO(inst)                             ((inst) + 0x0000004A), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_HIGHLIMIT_PR4_ADDR(inst)                            ((inst) + 0x0000004B)
#define BF_HOP_HIGHLIMIT_PR4_INFO(inst)                             ((inst) + 0x0000004B), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_HIGHLIMIT_PR5_ADDR(inst)                            ((inst) + 0x0000004C)
#define BF_HOP_HIGHLIMIT_PR5_INFO(inst)                             ((inst) + 0x0000004C), 0x00000600
#endif /* USE_PRIVATE_BF */

#define REG_HOP_INTRPT_PR0_ADDR(inst)                               ((inst) + 0x0000004D)
#define BF_HOP_INT_NUM0_INFO(inst)                                  ((inst) + 0x0000004D), 0x00000600
#define BF_HOP_INT_MASK_TXRX_FINE_NCO_INFO(inst)                    ((inst) + 0x0000004D), 0x00000606
#define BF_HOP_INT_CLR_TXRX_FINE_NCO_INFO(inst)                     ((inst) + 0x0000004D), 0x00000607

#ifdef USE_PRIVATE_BF
#define REG_HOP_INTRPT_PR1_ADDR(inst)                               ((inst) + 0x0000004E)
#define BF_HOP_INT_NUM1_INFO(inst)                                  ((inst) + 0x0000004E), 0x00000600
#endif /* USE_PRIVATE_BF */

#define REG_HOP_INTRPT_PR2_ADDR(inst)                               ((inst) + 0x0000004F)
#define BF_HOP_INT_NUM2_INFO(inst)                                  ((inst) + 0x0000004F), 0x00000600

#ifdef USE_PRIVATE_BF
#define REG_HOP_INTRPT_PR3_ADDR(inst)                               ((inst) + 0x00000050)
#define BF_HOP_INT_NUM3_INFO(inst)                                  ((inst) + 0x00000050), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_INTRPT_PR4_ADDR(inst)                               ((inst) + 0x00000051)
#define BF_HOP_INT_NUM4_INFO(inst)                                  ((inst) + 0x00000051), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_INTRPT_PR5_ADDR(inst)                               ((inst) + 0x00000052)
#define BF_HOP_INT_NUM5_INFO(inst)                                  ((inst) + 0x00000052), 0x00000600
#endif /* USE_PRIVATE_BF */

#define REG_HOP_INT_STATUS_ADDR(inst)                               ((inst) + 0x00000053)
#define BF_HOP_INT_STATUS_TXRX_FINE_NCO_INFO(inst)                  ((inst) + 0x00000053), 0x00000600

#ifdef USE_PRIVATE_BF
#define REG_HOP_JMP_HIGH0_ADDR(inst)                                ((inst) + 0x00000054)
#define BF_HOP_JMP_HIGH0_INFO(inst)                                 ((inst) + 0x00000054), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_JMP_HIGH1_ADDR(inst)                                ((inst) + 0x00000055)
#define BF_HOP_JMP_HIGH1_INFO(inst)                                 ((inst) + 0x00000055), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_JMP_HIGH2_ADDR(inst)                                ((inst) + 0x00000056)
#define BF_HOP_JMP_HIGH2_INFO(inst)                                 ((inst) + 0x00000056), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_JMP_HIGH3_ADDR(inst)                                ((inst) + 0x00000057)
#define BF_HOP_JMP_HIGH3_INFO(inst)                                 ((inst) + 0x00000057), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_JMP_LOW0_ADDR(inst)                                 ((inst) + 0x00000058)
#define BF_HOP_JMP_LOW0_INFO(inst)                                  ((inst) + 0x00000058), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_JMP_LOW1_ADDR(inst)                                 ((inst) + 0x00000059)
#define BF_HOP_JMP_LOW1_INFO(inst)                                  ((inst) + 0x00000059), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_JMP_LOW2_ADDR(inst)                                 ((inst) + 0x0000005A)
#define BF_HOP_JMP_LOW2_INFO(inst)                                  ((inst) + 0x0000005A), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_JMP_LOW3_ADDR(inst)                                 ((inst) + 0x0000005B)
#define BF_HOP_JMP_LOW3_INFO(inst)                                  ((inst) + 0x0000005B), 0x00000800
#endif /* USE_PRIVATE_BF */

#define REG_HOP_LOWLIMIT_PR0_ADDR(inst)                             ((inst) + 0x0000005C)
#define BF_HOP_LOWLIMIT_PR0_INFO(inst)                              ((inst) + 0x0000005C), 0x00000600

#ifdef USE_PRIVATE_BF
#define REG_HOP_LOWLIMIT_PR1_ADDR(inst)                             ((inst) + 0x0000005D)
#define BF_HOP_LOWLIMIT_PR1_INFO(inst)                              ((inst) + 0x0000005D), 0x00000600
#endif /* USE_PRIVATE_BF */

#define REG_HOP_LOWLIMIT_PR2_ADDR(inst)                             ((inst) + 0x0000005E)
#define BF_HOP_LOWLIMIT_PR2_INFO(inst)                              ((inst) + 0x0000005E), 0x00000600

#ifdef USE_PRIVATE_BF
#define REG_HOP_LOWLIMIT_PR3_ADDR(inst)                             ((inst) + 0x0000005F)
#define BF_HOP_LOWLIMIT_PR3_INFO(inst)                              ((inst) + 0x0000005F), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_LOWLIMIT_PR4_ADDR(inst)                             ((inst) + 0x00000060)
#define BF_HOP_LOWLIMIT_PR4_INFO(inst)                              ((inst) + 0x00000060), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_LOWLIMIT_PR5_ADDR(inst)                             ((inst) + 0x00000061)
#define BF_HOP_LOWLIMIT_PR5_INFO(inst)                              ((inst) + 0x00000061), 0x00000600
#endif /* USE_PRIVATE_BF */

#define REG_HOP_PHASE_INC0_ADDR(inst)                               ((inst) + 0x00000062)
#define BF_HOP_PHASE_INC0_INFO(inst)                                ((inst) + 0x00000062), 0x00000800

#define REG_HOP_PHASE_INC1_ADDR(inst)                               ((inst) + 0x00000063)
#define BF_HOP_PHASE_INC1_INFO(inst)                                ((inst) + 0x00000063), 0x00000800

#define REG_HOP_PHASE_INC2_ADDR(inst)                               ((inst) + 0x00000064)
#define BF_HOP_PHASE_INC2_INFO(inst)                                ((inst) + 0x00000064), 0x00000800

#define REG_HOP_PHASE_INC3_ADDR(inst)                               ((inst) + 0x00000065)
#define BF_HOP_PHASE_INC3_INFO(inst)                                ((inst) + 0x00000065), 0x00000800

#define REG_HOP_PHASE_OFFSET0_ADDR(inst)                            ((inst) + 0x00000066)
#define BF_HOP_PHASE_OFFSET0_INFO(inst)                             ((inst) + 0x00000066), 0x00000800

#define REG_HOP_PHASE_OFFSET1_ADDR(inst)                            ((inst) + 0x00000067)
#define BF_HOP_PHASE_OFFSET1_INFO(inst)                             ((inst) + 0x00000067), 0x00000800

#define REG_HOP_PROFILE_PAGE_ADDR(inst)                             ((inst) + 0x00000068)
#define BF_HOP_PROFILE_PAGE_INFO(inst)                              ((inst) + 0x00000068), 0x00000600

#ifdef USE_PRIVATE_BF
#define REG_HOP_STOP_FREQ0_ADDR(inst)                               ((inst) + 0x00000069)
#define BF_HOP_STOP_FREQ0_INFO(inst)                                ((inst) + 0x00000069), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_STOP_FREQ1_ADDR(inst)                               ((inst) + 0x0000006A)
#define BF_HOP_STOP_FREQ1_INFO(inst)                                ((inst) + 0x0000006A), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_STOP_FREQ2_ADDR(inst)                               ((inst) + 0x0000006B)
#define BF_HOP_STOP_FREQ2_INFO(inst)                                ((inst) + 0x0000006B), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_STOP_FREQ3_ADDR(inst)                               ((inst) + 0x0000006C)
#define BF_HOP_STOP_FREQ3_INFO(inst)                                ((inst) + 0x0000006C), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_TIME0_ADDR(inst)                                    ((inst) + 0x0000006D)
#define BF_HOP_TIME0_INFO(inst)                                     ((inst) + 0x0000006D), 0x00000800
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_HOP_TIME1_ADDR(inst)                                    ((inst) + 0x0000006E)
#define BF_HOP_TIME1_INFO(inst)                                     ((inst) + 0x0000006E), 0x00000800
#endif /* USE_PRIVATE_BF */

#define REG_MAIN_NCO_CTRL_ADDR(inst)                                ((inst) + 0x0000006F)
#define BF_MAIN2_NCO_SEL_INFO(inst)                                 ((inst) + 0x0000006F), 0x00000100
#define BF_MAIN_NCO_SYNC_UPDT_EN_INFO(inst)                         ((inst) + 0x0000006F), 0x00000101
#define BF_MAIN_NCO_SYNC_UPDT_INFO(inst)                            ((inst) + 0x0000006F), 0x00000102

#define REG_MAIN2_PHASE_INC0_ADDR(inst)                             ((inst) + 0x00000070)
#define BF_MAIN2_PHASE_INC_INFO(inst)                               ((inst) + 0x00000070), 0x00003000

#define REG_MAIN2_PHASE_INC1_ADDR(inst)                             ((inst) + 0x00000071)

#define REG_MAIN2_PHASE_INC2_ADDR(inst)                             ((inst) + 0x00000072)

#define REG_MAIN2_PHASE_INC3_ADDR(inst)                             ((inst) + 0x00000073)

#define REG_MAIN2_PHASE_INC4_ADDR(inst)                             ((inst) + 0x00000074)

#define REG_MAIN2_PHASE_INC5_ADDR(inst)                             ((inst) + 0x00000075)

#define REG_MAIN2_PHASE_OFFSET0_ADDR(inst)                          ((inst) + 0x00000076)
#define BF_MAIN2_PHASE_OFFSET_INFO(inst)                            ((inst) + 0x00000076), 0x00003000

#define REG_MAIN2_PHASE_OFFSET1_ADDR(inst)                          ((inst) + 0x00000077)

#define REG_MAIN2_PHASE_OFFSET2_ADDR(inst)                          ((inst) + 0x00000078)

#define REG_MAIN2_PHASE_OFFSET3_ADDR(inst)                          ((inst) + 0x00000079)

#define REG_MAIN2_PHASE_OFFSET4_ADDR(inst)                          ((inst) + 0x0000007A)

#define REG_MAIN2_PHASE_OFFSET5_ADDR(inst)                          ((inst) + 0x0000007B)

#ifdef USE_PRIVATE_BF
#define REG_MAIN_AMP0_ADDR(inst)                                    ((inst) + 0x0000007C)
#define BF_MAIN_AMP0_INFO(inst)                                     ((inst) + 0x0000007C), 0x00000400
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_MAIN_AMP1_ADDR(inst)                                    ((inst) + 0x0000007D)
#define BF_MAIN_AMP1_INFO(inst)                                     ((inst) + 0x0000007D), 0x00000800
#endif /* USE_PRIVATE_BF */

#define REG_MAIN_PHASE_INC0_ADDR(inst)                              ((inst) + 0x0000007E)
#define BF_MAIN_PHASE_INC_INFO(inst)                                ((inst) + 0x0000007E), 0x00003000

#define REG_MAIN_PHASE_INC1_ADDR(inst)                              ((inst) + 0x0000007F)

#define REG_MAIN_PHASE_INC2_ADDR(inst)                              ((inst) + 0x00000080)

#define REG_MAIN_PHASE_INC3_ADDR(inst)                              ((inst) + 0x00000081)

#define REG_MAIN_PHASE_INC4_ADDR(inst)                              ((inst) + 0x00000082)

#define REG_MAIN_PHASE_INC5_ADDR(inst)                              ((inst) + 0x00000083)

#define REG_MAIN_PHASE_OFFSET0_ADDR(inst)                           ((inst) + 0x00000084)
#define BF_MAIN_PHASE_OFFSET_INFO(inst)                             ((inst) + 0x00000084), 0x00003000

#define REG_MAIN_PHASE_OFFSET1_ADDR(inst)                           ((inst) + 0x00000085)

#define REG_MAIN_PHASE_OFFSET2_ADDR(inst)                           ((inst) + 0x00000086)

#define REG_MAIN_PHASE_OFFSET3_ADDR(inst)                           ((inst) + 0x00000087)

#define REG_MAIN_PHASE_OFFSET4_ADDR(inst)                           ((inst) + 0x00000088)

#define REG_MAIN_PHASE_OFFSET5_ADDR(inst)                           ((inst) + 0x00000089)

#ifdef USE_PRIVATE_BF
#define REG_MOD_NCO_LOAD_CTRL_ADDR(inst)                            ((inst) + 0x0000008A)
#define BF_MOD_NCO_PHASE_ERROR_LOAD_ENABLE_TXRX_FINE_NCO_INFO(inst) ((inst) + 0x0000008A), 0x00000100
#define BF_MOD_NCO_PHASE_ERROR_LOAD_STATUS_TXRX_FINE_NCO_INFO(inst) ((inst) + 0x0000008A), 0x00000101
#endif /* USE_PRIVATE_BF */

#define REG_MOD_NCO_CTRL_TXRX_FINE_NCO_ADDR(inst)                   ((inst) + 0x0000008B)
#define BF_MOD_PARAM_SCH_INFO(inst)                                 ((inst) + 0x0000008B), 0x00000200
#define BF_USE_FRC_AB_INFO(inst)                                    ((inst) + 0x0000008B), 0x00000102

#define REG_NEXT_HOP_NUMBER_PR0_ADDR(inst)                          ((inst) + 0x0000008C)
#define BF_NEXT_HOP_NUMBER_PR0_INFO(inst)                           ((inst) + 0x0000008C), 0x00000600

#ifdef USE_PRIVATE_BF
#define REG_NEXT_HOP_NUMBER_PR1_ADDR(inst)                          ((inst) + 0x0000008D)
#define BF_NEXT_HOP_NUMBER_PR1_INFO(inst)                           ((inst) + 0x0000008D), 0x00000600
#endif /* USE_PRIVATE_BF */

#define REG_NEXT_HOP_NUMBER_PR2_ADDR(inst)                          ((inst) + 0x0000008E)
#define BF_NEXT_HOP_NUMBER_PR2_INFO(inst)                           ((inst) + 0x0000008E), 0x00000600

#ifdef USE_PRIVATE_BF
#define REG_NEXT_HOP_NUMBER_PR3_ADDR(inst)                          ((inst) + 0x0000008F)
#define BF_NEXT_HOP_NUMBER_PR3_INFO(inst)                           ((inst) + 0x0000008F), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_NEXT_HOP_NUMBER_PR4_ADDR(inst)                          ((inst) + 0x00000090)
#define BF_NEXT_HOP_NUMBER_PR4_INFO(inst)                           ((inst) + 0x00000090), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_NEXT_HOP_NUMBER_PR5_ADDR(inst)                          ((inst) + 0x00000091)
#define BF_NEXT_HOP_NUMBER_PR5_INFO(inst)                           ((inst) + 0x00000091), 0x00000600
#endif /* USE_PRIVATE_BF */

#define REG_PROFILE_GRP_COUNTER_VAL_PR0_ADDR(inst)                  ((inst) + 0x00000092)
#define BF_PROFILE_GRP_COUNTER_VAL_INFO(inst)                       ((inst) + 0x00000092), 0x00002400

#define REG_PROFILE_GRP_COUNTER_VAL_PR1_ADDR(inst)                  ((inst) + 0x00000093)

#define REG_PROFILE_GRP_COUNTER_VAL_PR2_ADDR(inst)                  ((inst) + 0x00000094)

#define REG_PROFILE_GRP_COUNTER_VAL_PR3_ADDR(inst)                  ((inst) + 0x00000095)

#define REG_PROFILE_GRP_COUNTER_VAL_PR4_ADDR(inst)                  ((inst) + 0x00000096)

#define REG_PROFILE_GRP_COUNTER_VAL_PR5_ADDR(inst)                  ((inst) + 0x00000097)

#define REG_PROFILE_SEL_MODE_TXRX_FINE_NCO_ADDR(inst)               ((inst) + 0x00000098)
#define BF_PROFILE_SEL_MODE_TXRX_FINE_NCO_INFO(inst)                ((inst) + 0x00000098), 0x00000400

#define REG_REGMAP_HOPPROF_ADDR(inst)                               ((inst) + 0x00000099)
#define BF_REGMAP_HOPPROF_INFO(inst)                                ((inst) + 0x00000099), 0x00000600

#define REG_SAW_POSNEG_SEL_ADDR(inst)                               ((inst) + 0x0000009A)
#define BF_SAW_POSNEG_SEL_INFO(inst)                                ((inst) + 0x0000009A), 0x00000100

#define REG_SQW_HIGH0_ADDR(inst)                                    ((inst) + 0x0000009C)
#define BF_SQW_HIGH0_INFO(inst)                                     ((inst) + 0x0000009C), 0x00000800

#define REG_SQW_HIGH1_ADDR(inst)                                    ((inst) + 0x0000009D)
#define BF_SQW_HIGH1_INFO(inst)                                     ((inst) + 0x0000009D), 0x00000800

#define REG_SQW_LOW0_ADDR(inst)                                     ((inst) + 0x0000009E)
#define BF_SQW_LOW0_INFO(inst)                                      ((inst) + 0x0000009E), 0x00000800

#define REG_SQW_LOW1_ADDR(inst)                                     ((inst) + 0x0000009F)
#define BF_SQW_LOW1_INFO(inst)                                      ((inst) + 0x0000009F), 0x00000800

#define REG_TRIG_HOP_SEL0_ADDR(inst)                                ((inst) + 0x000000A0)
#define BF_TRIG_HOP_SEL0_INFO(inst)                                 ((inst) + 0x000000A0), 0x00000600

#ifdef USE_PRIVATE_BF
#define REG_TRIG_HOP_SEL1_ADDR(inst)                                ((inst) + 0x000000A1)
#define BF_TRIG_HOP_SEL1_INFO(inst)                                 ((inst) + 0x000000A1), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_TRIG_HOP_SEL2_ADDR(inst)                                ((inst) + 0x000000A2)
#define BF_TRIG_HOP_SEL2_INFO(inst)                                 ((inst) + 0x000000A2), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_TRIG_HOP_SEL3_ADDR(inst)                                ((inst) + 0x000000A3)
#define BF_TRIG_HOP_SEL3_INFO(inst)                                 ((inst) + 0x000000A3), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_TRIG_HOP_SEL4_ADDR(inst)                                ((inst) + 0x000000A4)
#define BF_TRIG_HOP_SEL4_INFO(inst)                                 ((inst) + 0x000000A4), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_TRIG_HOP_SEL5_ADDR(inst)                                ((inst) + 0x000000A5)
#define BF_TRIG_HOP_SEL5_INFO(inst)                                 ((inst) + 0x000000A5), 0x00000600
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_WAVE_OFFSET0_ADDR(inst)                                 ((inst) + 0x000000A6)
#define BF_WAVE_OFFSET0_INFO(inst)                                  ((inst) + 0x000000A6), 0x00000400
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_WAVE_OFFSET1_ADDR(inst)                                 ((inst) + 0x000000A7)
#define BF_WAVE_OFFSET1_INFO(inst)                                  ((inst) + 0x000000A7), 0x00000800
#endif /* USE_PRIVATE_BF */

#define REG_WAVE_SEL_ADDR(inst)                                     ((inst) + 0x000000A8)
#define BF_WAVE_SEL_INFO(inst)                                      ((inst) + 0x000000A8), 0x00000200

#define REG_PCT_RST_CTRL_TXRX_FINE_NCO_ADDR(inst)                   ((inst) + 0x000000A9)
#define BF_TS_RST_MODE_TXRX_FINE_NCO_INFO(inst)                     ((inst) + 0x000000A9), 0x00000100
#define BF_SPI_TS_RST_TXRX_FINE_NCO_INFO(inst)                      ((inst) + 0x000000A9), 0x00000101

#define REG_PCT_RST_STATUS_TXRX_FINE_NCO_ADDR(inst)                 ((inst) + 0x000000AA)
#define BF_RST_DONE_TXRX_FINE_NCO_INFO(inst)                        ((inst) + 0x000000AA), 0x00000100
#define BF_RST_DONE_CLR_TXRX_FINE_NCO_INFO(inst)                    ((inst) + 0x000000AA), 0x00000101

#define REG_PCT_RD_EN_TXRX_FINE_NCO_ADDR(inst)                      ((inst) + 0x000000AB)
#define BF_TIMESTAMP_READ_EN_TXRX_FINE_NCO_INFO(inst)               ((inst) + 0x000000AB), 0x00000100

#define REG_PCT_STATUS0_TXRX_FINE_NCO_ADDR(inst)                    ((inst) + 0x000000AC)
#define BF_TIMESTAMP_STATUS_TXRX_FINE_NCO_INFO(inst)                ((inst) + 0x000000AC), 0x00004000

#define REG_PCT_STATUS1_TXRX_FINE_NCO_ADDR(inst)                    ((inst) + 0x000000AD)

#define REG_PCT_STATUS2_TXRX_FINE_NCO_ADDR(inst)                    ((inst) + 0x000000AE)

#define REG_PCT_STATUS3_TXRX_FINE_NCO_ADDR(inst)                    ((inst) + 0x000000AF)

#define REG_PCT_STATUS4_TXRX_FINE_NCO_ADDR(inst)                    ((inst) + 0x000000B0)

#define REG_PCT_STATUS5_TXRX_FINE_NCO_ADDR(inst)                    ((inst) + 0x000000B1)

#define REG_PCT_STATUS6_TXRX_FINE_NCO_ADDR(inst)                    ((inst) + 0x000000B2)

#define REG_PCT_STATUS7_TXRX_FINE_NCO_ADDR(inst)                    ((inst) + 0x000000B3)

#define REG_MXR_TEST_MODE_VAL0_ADDR(inst)                           ((inst) + 0x000000B4)
#define BF_MIXER_TEST_MODE_VAL_TXRX_FINE_NCO_INFO(inst)             ((inst) + 0x000000B4), 0x00001000

#define REG_MXR_TEST_MODE_VAL1_ADDR(inst)                           ((inst) + 0x000000B5)

#endif /* __ADI_APOLLO_BF_TXRX_FINE_NCO_H__ */
/*! @} */
