/*!
 * @brief     SPI Register Definition Header File, automatically generated by
 *            yoda2h v1.3.8 at 2/15/2023 10:39:25 AM.
 * 
 * @copyright copyright(c) 2023 - Analog Devices Inc.All Rights Reserved.
 *            This software is proprietary to Analog Devices, Inc. and its
 *            licensor. By using this software you agree to the terms of the
 *            associated analog devices software license agreement.
 */

/*! 
 * @addtogroup APOLLO_BF
 * @{
 */
#ifndef __ADI_APOLLO_BF_JRX_DL_204B_H__
#define __ADI_APOLLO_BF_JRX_DL_204B_H__

/*============= D E F I N E S ==============*/
#define JRX_DL_204B_JRX_TX_DIGITAL0                   0x6160C000
#define JRX_DL_204B_JRX_TX_DIGITAL1                   0x61E0C000

#define REG_JRX_DL_204B_CONFIG0_ADDR(inst)            ((inst) + 0x00000380)
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204B_AR_ECNTR_INFO(inst)            ((inst) + 0x00000380), 0x00000100
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204B_CGS_SEL_INFO(inst)             ((inst) + 0x00000380), 0x00000101
#endif /* USE_PRIVATE_BF */
#define BF_JRX_DL_204B_CHAR_REPL_DIS_INFO(inst)       ((inst) + 0x00000380), 0x00000102
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204B_ENA_RAMP_CHECK_INFO(inst)      ((inst) + 0x00000380), 0x00000103
#endif /* USE_PRIVATE_BF */
#define BF_JRX_DL_204B_FCHK_N_INFO(inst)              ((inst) + 0x00000380), 0x00000104
#define BF_JRX_DL_204B_FORCESYNCREQ_INFO(inst)        ((inst) + 0x00000380), 0x00000105
#define BF_JRX_DL_204B_ILS_MODE_INFO(inst)            ((inst) + 0x00000380), 0x00000106
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204B_QUAL_RDERR_INFO(inst)          ((inst) + 0x00000380), 0x00000107
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_DL_204B_CONFIG1_ADDR(inst)            ((inst) + 0x00000381)
#define BF_JRX_DL_204B_REPDATATEST_INFO(inst)         ((inst) + 0x00000381), 0x00000100
#define BF_JRX_DL_204B_SYNC_ASSERT_MASK_INFO(inst)    ((inst) + 0x00000381), 0x00000301
#define BF_JRX_DL_204B_SYNC_ERR_ENABLE_INFO(inst)     ((inst) + 0x00000381), 0x00000104
#endif /* USE_PRIVATE_BF */

#ifdef USE_PRIVATE_BF
#define REG_JRX_DL_204B_IRQ_CLR0_ADDR(inst)           ((inst) + 0x00000382)
#define BF_JRX_DL_204B_IRQ_CLR_INFO(inst)             ((inst) + 0x00000382), 0x00000900
#endif /* USE_PRIVATE_BF */

#define REG_JRX_DL_204B_IRQ_CLR1_ADDR(inst)           ((inst) + 0x00000383)

#define REG_JRX_DL_204B_ETH_ADDR(inst)                ((inst) + 0x00000384)
#define BF_JRX_DL_204B_ETH_INFO(inst)                 ((inst) + 0x00000384), 0x00000800

#define REG_JRX_DL_204B_KSYNC_ADDR(inst)              ((inst) + 0x00000386)
#define BF_JRX_DL_204B_KSYNC_INFO(inst)               ((inst) + 0x00000386), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_00_ADDR(inst, n)   ((inst) + 0x00000390 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_0_INFO(inst, n)       ((inst) + 0x00000390 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_01_ADDR(inst, n)   ((inst) + 0x000003A0 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_1_INFO(inst, n)       ((inst) + 0x000003A0 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_02_ADDR(inst, n)   ((inst) + 0x000003B0 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_2_INFO(inst, n)       ((inst) + 0x000003B0 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_03_ADDR(inst, n)   ((inst) + 0x000003C0 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_3_INFO(inst, n)       ((inst) + 0x000003C0 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_04_ADDR(inst, n)   ((inst) + 0x000003D0 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_4_INFO(inst, n)       ((inst) + 0x000003D0 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_05_ADDR(inst, n)   ((inst) + 0x000003E0 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_5_INFO(inst, n)       ((inst) + 0x000003E0 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_06_ADDR(inst, n)   ((inst) + 0x000003F0 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_6_INFO(inst, n)       ((inst) + 0x000003F0 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_07_ADDR(inst, n)   ((inst) + 0x00000400 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_7_INFO(inst, n)       ((inst) + 0x00000400 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_08_ADDR(inst, n)   ((inst) + 0x00000410 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_8_INFO(inst, n)       ((inst) + 0x00000410 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_09_ADDR(inst, n)   ((inst) + 0x00000420 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_9_INFO(inst, n)       ((inst) + 0x00000420 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_10_ADDR(inst, n)   ((inst) + 0x00000430 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_10_INFO(inst, n)      ((inst) + 0x00000430 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_11_ADDR(inst, n)   ((inst) + 0x00000440 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_11_INFO(inst, n)      ((inst) + 0x00000440 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_12_ADDR(inst, n)   ((inst) + 0x00000450 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_12_INFO(inst, n)      ((inst) + 0x00000450 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_RXCFG_13_ADDR(inst, n)   ((inst) + 0x00000460 + 1 * (n))
#define BF_JRX_DL_204B_L0_RXCFG_13_INFO(inst, n)      ((inst) + 0x00000460 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_ECNT0_ADDR(inst, n)      ((inst) + 0x00000470 + 1 * (n))
#define BF_JRX_DL_204B_ECNT_ENA_INFO(inst, n)         ((inst) + 0x00000470 + 1 * (n)), 0x00000300
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204B_ECNT_RST_INFO(inst, n)         ((inst) + 0x00000470 + 1 * (n)), 0x00000304
#endif /* USE_PRIVATE_BF */

#define REG_JRX_DL_204B_LANE_ECNT1_ADDR(inst, n)      ((inst) + 0x00000480 + 1 * (n))
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204B_ECNT_TCH_INFO(inst, n)         ((inst) + 0x00000480 + 1 * (n)), 0x00000300
#endif /* USE_PRIVATE_BF */
#define BF_JRX_DL_204B_ECNT_TCR_INFO(inst, n)         ((inst) + 0x00000480 + 1 * (n)), 0x00000304

#define REG_JRX_DL_204B_LANE_ERR_STATUS_ADDR(inst, n) ((inst) + 0x00000490 + 1 * (n))
#define BF_JRX_DL_204B_BDE_INFO(inst, n)              ((inst) + 0x00000490 + 1 * (n)), 0x00000100
#define BF_JRX_DL_204B_CGS_INFO(inst, n)              ((inst) + 0x00000490 + 1 * (n)), 0x00000101
#define BF_JRX_DL_204B_CKS_INFO(inst, n)              ((inst) + 0x00000490 + 1 * (n)), 0x00000102
#define BF_JRX_DL_204B_FS_INFO(inst, n)               ((inst) + 0x00000490 + 1 * (n)), 0x00000103
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204B_ILD_INFO(inst, n)              ((inst) + 0x00000490 + 1 * (n)), 0x00000104
#endif /* USE_PRIVATE_BF */
#define BF_JRX_DL_204B_ILS_INFO(inst, n)              ((inst) + 0x00000490 + 1 * (n)), 0x00000105
#define BF_JRX_DL_204B_NIT_INFO(inst, n)              ((inst) + 0x00000490 + 1 * (n)), 0x00000106
#define BF_JRX_DL_204B_UEK_INFO(inst, n)              ((inst) + 0x00000490 + 1 * (n)), 0x00000107

#define REG_JRX_DL_204B_LANE_BD_ADDR(inst, n)         ((inst) + 0x000004A0 + 1 * (n))
#define BF_JRX_DL_204B_BD_CNT_INFO(inst, n)           ((inst) + 0x000004A0 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_UEK_ADDR(inst, n)        ((inst) + 0x000004B0 + 1 * (n))
#define BF_JRX_DL_204B_UEK_CNT_INFO(inst, n)          ((inst) + 0x000004B0 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_NIT_ADDR(inst, n)        ((inst) + 0x000004C0 + 1 * (n))
#define BF_JRX_DL_204B_NIT_CNT_INFO(inst, n)          ((inst) + 0x000004C0 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_FCHK_ADDR(inst, n)       ((inst) + 0x000004D0 + 1 * (n))
#define BF_JRX_DL_204B_LL_FCHK_INFO(inst, n)          ((inst) + 0x000004D0 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_FCMP_ADDR(inst, n)       ((inst) + 0x000004E0 + 1 * (n))
#define BF_JRX_DL_204B_LL_FCMP_INFO(inst, n)          ((inst) + 0x000004E0 + 1 * (n)), 0x00000800

#define REG_JRX_DL_204B_LANE_LID_ADDR(inst, n)        ((inst) + 0x000004F0 + 1 * (n))
#define BF_JRX_DL_204B_LL_LID_INFO(inst, n)           ((inst) + 0x000004F0 + 1 * (n)), 0x00000500

#define REG_JRX_DL_204B_LANE_STATUS_ADDR(inst, n)     ((inst) + 0x00000500 + 1 * (n))
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204B_EOF_EVENT_INFO(inst, n)        ((inst) + 0x00000500 + 1 * (n)), 0x00000100
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204B_EOMF_EVENT_INFO(inst, n)       ((inst) + 0x00000500 + 1 * (n)), 0x00000101
#endif /* USE_PRIVATE_BF */
#ifdef USE_PRIVATE_BF
#define BF_JRX_DL_204B_FS_LOST_INFO(inst, n)          ((inst) + 0x00000500 + 1 * (n)), 0x00000102
#endif /* USE_PRIVATE_BF */
#define BF_JRX_DL_204B_SYNC_N_INFO(inst, n)           ((inst) + 0x00000500 + 1 * (n)), 0x00000103
#define BF_JRX_DL_204B_USER_DATA_INFO(inst, n)        ((inst) + 0x00000500 + 1 * (n)), 0x00000104
#define BF_JRX_DL_204B_VALID_CKSUM_INFO(inst, n)      ((inst) + 0x00000500 + 1 * (n)), 0x00000105

#define REG_JRX_DL_204B_LANE_IRQ_VEC0_ADDR(inst, n)   ((inst) + 0x00000510 + 1 * (n))
#define BF_JRX_DL_204B_IRQ_VEC_INFO(inst, n)          ((inst) + 0x00000510 + 1 * (n)), 0x00000900

#define REG_JRX_DL_204B_LANE_IRQ_VEC1_ADDR(inst, n)   ((inst) + 0x00000520 + 1 * (n))
#define BF_JRX_DL_204B_IRQ_INFO(inst, n)              ((inst) + 0x00000520 + 1 * (n)), 0x00000107

#endif /* __ADI_APOLLO_BF_JRX_DL_204B_H__ */
/*! @} */
