# PQMON Slave-specific Configuration
# Use with: -DCONF_FILE="prj.conf;prj_slave.conf"

# Static Network Configuration - Slave
CONFIG_NET_CONFIG_MY_IPV4_ADDR="192.0.2.2"

# PTP BTCA - Slave (higher = lower priority)
CONFIG_PTP_PRIORITY1=200
CONFIG_PTP_PRIORITY2=200

# Force this device to be timeReceiver only
CONFIG_PTP_TIME_RECEIVER_ONLY=y
