## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/fmcadc2/vc707/fmcadc2_vc707.sdk/system_top.hdf

include $(NOOS-DIR)/fmcadc2/fmcadc2.mk
include $(NOOS-DIR)/scripts/microblaze.mk

