CONFIG_AD9088_PROFILE="204C_M4_L8_NP16_20p0_4x2.bin"
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_UART=y
CONFIG_IRQ=y
CONFIG_TIMER=y
CONFIG_DMA=y
CONFIG_CLK=y
CONFIG_RF_TRANSCEIVER=y
CONFIG_RF_TRANSCEIVER_AD9088=y
CONFIG_FREQUENCY=y
CONFIG_FREQUENCY_ADF4030=y
CONFIG_FREQUENCY_ADF4382=y
CONFIG_FREQUENCY_HMC7044=y
CONFIG_AXI_CORE=y
CONFIG_AXI_CORE_AXI_ADC_CORE=y
CONFIG_AXI_CORE_AXI_DAC_CORE=y
CONFIG_AXI_CORE_AXI_DMAC=y
CONFIG_AXI_CORE_CLK_AXI_CLKGEN=y
CONFIG_AXI_CORE_JESD204=y
CONFIG_AD9088_BASIC_EXAMPLE=y
