PLATFORM ?= maxim
TARGET ?= max32665

CONFIG_USB_UART_MAXIM = y

FIFO_DEPTH ?= 4096

EXAMPLE ?= iio

include ../../tools/scripts/generic_variables.mk

include ../../tools/scripts/examples.mk

include src.mk

include ../../tools/scripts/generic.mk
