PLATFORM ?= maxim
TARGET ?= max32665

NO_OS_USB_UART = y

FIFO_DEPTH ?= 4096

EXAMPLE ?= iio

include ../../tools/scripts/generic_variables.mk

include ../../tools/scripts/examples.mk

include src.mk

include ../../tools/scripts/generic.mk
