# Select the example you want to enable by choosing y for enabling and n for disabling
DUMMY_EXAMPLE = y
IIO_EXAMPLE = n

# Select the device you want to enable by choosing y for enabling and n for disabling
AD4055 = y

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
