PLATFORM = xilinx
CFLAGS += -DNO_OS_LWIP_NETWORKING
CFLAGS += -DNO_OS_LWIP_INIT_ONETIME=1
CFLAGS += -Wall -Wextra

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
