CONFIG_XILINX_HDL_DESIGN="ad9265_fmc"
CONFIG_SPI=y
CONFIG_IRQ=y
CONFIG_UART=y
CONFIG_IIO=y
CONFIG_ADC=y
CONFIG_ADC_AD9265=y
CONFIG_AXI_CORE=y
CONFIG_AXI_CORE_AXI_ADC_CORE=y
CONFIG_AXI_CORE_AXI_DMAC=y
CONFIG_AXI_CORE_IIO_AXI_ADC=y
CONFIG_AD9265_FMC_125EBZ_IIO_EXAMPLE=y
