CONFIG_XILINX_HDL_DESIGN="dac_fmc_ebz"
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_DAC=y
CONFIG_DAC_AD917X=y
CONFIG_FREQUENCY=y
CONFIG_FREQUENCY_HMC7044=y
CONFIG_AXI_CORE=y
CONFIG_AXI_CORE_AXI_DAC_CORE=y
CONFIG_AXI_CORE_CLK_AXI_CLKGEN=y
CONFIG_AXI_CORE_JESD204=y
CONFIG_AD9172_DEMO_EXAMPLE=y
