CONFIG_UART=y
CONFIG_IIO=y
CONFIG_IRQ=y
CONFIG_TIMER=y
CONFIG_DMA=y
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_GPIO=y
CONFIG_IMU=y
CONFIG_IMU_ADIS1650X=y
CONFIG_IMU_IIO_ADIS1650X=y
CONFIG_ADIS1650X_IIO_TRIGGER_EXAMPLE=y
