## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/ad9434_fmc/zc706/ad9434_fmc_zc706.sdk/system_top.hdf

include $(NOOS-DIR)/ad9434-fmc-500ebz/ad9434_fmc_500ebz.mk
include $(NOOS-DIR)/scripts/zynq_ps7.mk

