CONFIG_XILINX_HDL_DESIGN="ad77681evb"
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_AXI_CORE=y
CONFIG_AXI_CORE_SPI_ENGINE=y
CONFIG_AXI_CORE_AXI_DMAC=y
CONFIG_AXI_CORE_CLK_AXI_CLKGEN=y
CONFIG_ADC=y
CONFIG_ADC_AD7768_1=y
CONFIG_AD7768_1FMCZ_DEMO_EXAMPLE=y
