CONFIG_XILINX_HDL_DESIGN="fmcomms2"
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_RF_TRANSCEIVER=y
CONFIG_RF_TRANSCEIVER_AD9361=y
CONFIG_AXI_CORE=y
CONFIG_AXI_CORE_AXI_ADC_CORE=y
CONFIG_AXI_CORE_AXI_DAC_CORE=y
CONFIG_AXI_CORE_AXI_DMAC=y
CONFIG_AXI_CORE_AXI_SYSID=y
CONFIG_AD9361_DEMO_EXAMPLE=y
