CONFIG_XILINX_HDL_DESIGN="fmcomms5"
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_UART=y
CONFIG_IIO=y
CONFIG_RF_TRANSCEIVER=y
CONFIG_RF_TRANSCEIVER_IIO_AD9361=y
CONFIG_AXI_CORE=y
CONFIG_AXI_CORE_AXI_ADC_CORE=y
CONFIG_AXI_CORE_AXI_DAC_CORE=y
CONFIG_AXI_CORE_AXI_DMAC=y
CONFIG_AXI_CORE_AXI_SYSID=y
CONFIG_AXI_CORE_IIO_AXI_ADC=y
CONFIG_AXI_CORE_IIO_AXI_DAC=y
CONFIG_AD9361_IIO_FMCOMMS5_EXAMPLE=y
