CONFIG_UART=y
CONFIG_SPI=y
CONFIG_IRQ=y
CONFIG_GPIO=y
CONFIG_DMA=y
CONFIG_TIMER=y
CONFIG_IIO=y
CONFIG_ADC=y
CONFIG_ADC_AD7124=y
CONFIG_NET=y
CONFIG_ADIN1110=y
CONFIG_LWIP=y
CONFIG_EVAL_CN0391_ARDZ_IIO_LWIP_EXAMPLE=y
