/**
 * \file
 * \brief BitField accessors for nevis_sys2_regmap_core_1
 *
 * Autogenerated with yoda-gen 1.6.1. Do not modify
 *
 * \copyright Copyright (c) 2024 Analog Devices, Inc. All Rights Reserved.
 * This software is proprietary to Analog Devices, Inc. and its licensors.
 */

 #ifndef __ADRV910X_BF_NEVIS_SYS2_REGMAP_CORE_1_H__
 #define __ADRV910X_BF_NEVIS_SYS2_REGMAP_CORE_1_H__

#include "adrv910x_bf_hal.h"



/**
 * (NEVIS_B0) AHB to AHB clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Ahb2ahbClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x14), (value >> 0), 0x8, 0x3);

    return status;
}

/**
 * (NEVIS_B0) AHB to AHB clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Ahb2ahbClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x14), &register_value, 0x8, 0x3);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Ahb2ahbSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x18), (value >> 0), 0x8, 0x3);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Ahb2ahbSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x18), &register_value, 0x8, 0x3);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (B0 New) Arm clock is automatically realign on Reference counter when arm_clk_div_value change
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_ArmClkAutoAlign_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xf), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (B0 New) Arm clock is automatically realign on Reference counter when arm_clk_div_value change
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_ArmClkAutoAlign_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xf), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_ArmClkDivValue_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0xd), (value >> 0));

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_ArmClkDivValue_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0xd), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (B0 New) Bypass the load process of ARM clock div value
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_ArmClkLoadBypass_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xf), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (B0 New) Bypass the load process of ARM clock div value
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_ArmClkLoadBypass_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xf), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_ArmIrqPulseGenEn_Set(void *const device,
    uint32_t regInstance,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x23 + 0x0 + (regInstance * 0x1)), (value >> 0));

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_ArmIrqPulseGenEn_Get(void *const device,
    uint32_t regInstance,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x23 + 0x0 + (regInstance * 0x1)), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (B0 New) 0: Manual mode, 1: Automatic Mode
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_ArmIrqPulseGenMode_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x22), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (B0 New) 0: Manual mode, 1: Automatic Mode
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_ArmIrqPulseGenMode_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x22), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (B0 New) ARM IRQ Extend Ratio
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_ArmIrqPulseGenRatio_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x22), (value >> 0), 0xfe, 0x1);

    return status;
}

/**
 * (B0 New) ARM IRQ Extend Ratio
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_ArmIrqPulseGenRatio_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x22), &register_value, 0xfe, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Arm clock selection in Sys2 : 0=ARM_CLK selected, 1=REF_CLK selected
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Armclk2RefClkSwitchEnable_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xe), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS) Arm clock selection in Sys2 : 0=ARM_CLK selected, 1=REF_CLK selected
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Armclk2RefClkSwitchEnable_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xe), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Local DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_DmaClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x16), (value >> 0), 0x4, 0x2);

    return status;
}

/**
 * (NEVIS_B0) Local DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_DmaClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x16), &register_value, 0x4, 0x2);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Periph DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_DmaPeriphClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x16), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS_B0) Periph DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_DmaPeriphClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x16), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_DmaPeriphSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1a), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_DmaPeriphSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1a), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_DmaSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1a), (value >> 0), 0x4, 0x2);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_DmaSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1a), &register_value, 0x4, 0x2);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) System DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_DmaSystemClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x16), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (NEVIS_B0) System DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_DmaSystemClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x16), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_DmaSystemSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1a), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_DmaSystemSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1a), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Event Scheduler 1 Clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EvSched1ClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x14), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS_B0) Enable Event Scheduler 1 Clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EvSched1ClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x14), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EvSched1SwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x18), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EvSched1SwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x18), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Event Scheduler 2 Clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EvSched2ClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x14), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (NEVIS_B0) Enable Event Scheduler 2 Clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EvSched2ClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x14), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EvSched2SwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x18), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EvSched2SwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x18), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Event Scheduler 2 Clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EvSched3ClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x14), (value >> 0), 0x4, 0x2);

    return status;
}

/**
 * (NEVIS_B0) Enable Event Scheduler 2 Clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EvSched3ClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x14), &register_value, 0x4, 0x2);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EvSched3SwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x18), (value >> 0), 0x4, 0x2);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EvSched3SwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x18), &register_value, 0x4, 0x2);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Event Logger DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EventLoggerClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x14), (value >> 0), 0x10, 0x4);

    return status;
}

/**
 * (NEVIS_B0) Event Logger DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EventLoggerClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x14), &register_value, 0x10, 0x4);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EventLoggerSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x18), (value >> 0), 0x10, 0x4);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_EventLoggerSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x18), &register_value, 0x10, 0x4);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) The glitch free Mux can switch ONLY if the 2 clock are running. If not, this bit can be used to force the switch on ARM_CLK
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_ForceArmClk_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xe), (value >> 0), 0x10, 0x4);

    return status;
}

/**
 * (NEVIS) The glitch free Mux can switch ONLY if the 2 clock are running. If not, this bit can be used to force the switch on ARM_CLK
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_ForceArmClk_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xe), &register_value, 0x10, 0x4);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) The glitch free Mux can switch ONLY if the 2 clock are running. If not, this bit can be used to force the switch on REF_CLK
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_ForceRefClk_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xe), (value >> 0), 0x20, 0x5);

    return status;
}

/**
 * (NEVIS) The glitch free Mux can switch ONLY if the 2 clock are running. If not, this bit can be used to force the switch on REF_CLK
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_ForceRefClk_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xe), &register_value, 0x20, 0x5);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Divider value for I2c clock from ARM clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_I2cClkDivValue_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x12), (value >> 0));

    return status;
}

/**
 * (NEVIS) Divider value for I2c clock from ARM clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_I2cClkDivValue_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x12), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) I2C clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_I2cClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x17), (value >> 0), 0x8, 0x3);

    return status;
}

/**
 * (NEVIS_B0) I2C clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_I2cClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x17), &register_value, 0x8, 0x3);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_I2cSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1b), (value >> 0), 0x8, 0x3);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_I2cSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1b), &register_value, 0x8, 0x3);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) I2S clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_I2sClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x17), (value >> 0), 0x10, 0x4);

    return status;
}

/**
 * (NEVIS_B0) I2S clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_I2sClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x17), &register_value, 0x10, 0x4);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_I2sSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1b), (value >> 0), 0x10, 0x4);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_I2sSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1b), &register_value, 0x10, 0x4);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) PU1 clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Pu1ClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x17), (value >> 0), 0x20, 0x5);

    return status;
}

/**
 * (NEVIS_B0) PU1 clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Pu1ClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x17), &register_value, 0x20, 0x5);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Pu1SwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1b), (value >> 0), 0x20, 0x5);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Pu1SwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1b), &register_value, 0x20, 0x5);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) PU2 clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Pu2ClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x17), (value >> 0), 0x40, 0x6);

    return status;
}

/**
 * (NEVIS_B0) PU2 clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Pu2ClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x17), &register_value, 0x40, 0x6);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Pu2SwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1b), (value >> 0), 0x40, 0x6);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Pu2SwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1b), &register_value, 0x40, 0x6);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) QSPI clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_QspiClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x17), (value >> 0), 0x4, 0x2);

    return status;
}

/**
 * (NEVIS_B0) QSPI clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_QspiClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x17), &register_value, 0x4, 0x2);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_QspiSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1b), (value >> 0), 0x4, 0x2);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_QspiSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1b), &register_value, 0x4, 0x2);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (B0 New) Internal REF Clock divider by N+1 (0:div1, 1:div2, 2:div3, 3:div4, ...)
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RefclkInternalDivValue_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x9), (value >> 0));

    return status;
}

/**
 * (B0 New) Internal REF Clock divider by N+1 (0:div1, 1:div2, 2:div3, 3:div4, ...)
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RefclkInternalDivValue_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x9), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (B0 New) External REF Clock divider by N+1 (0:div1, 1:div2, 2:div3, 3:div4, ...)
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RefclkPadDivValue_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0xa), (value >> 0));

    return status;
}

/**
 * (B0 New) External REF Clock divider by N+1 (0:div1, 1:div2, 2:div3, 3:div4, ...)
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RefclkPadDivValue_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0xa), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (B0 New) 0: refclk pad tristated , 1 : refclk pad in output mode
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RefclkPadOe_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x8), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (B0 New) 0: refclk pad tristated , 1 : refclk pad in output mode
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RefclkPadOe_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x8), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) RX1 Fifo2mem DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1Fifo2memClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x15), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS_B0) RX1 Fifo2mem DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1Fifo2memClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x15), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1Fifo2memSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x19), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1Fifo2memSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x19), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) RX1 Mem2fifo DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1Mem2fifoClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x15), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (NEVIS_B0) RX1 Mem2fifo DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1Mem2fifoClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x15), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1Mem2fifoSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x19), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1Mem2fifoSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x19), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Clear sample valid Max counter
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1SampleClkCounterClear_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1c), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (NEVIS_B0) Clear sample valid Max counter
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1SampleClkCounterClear_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1c), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Maximum number of sample_valid IRQ generated
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1SampleClkCounterMax_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x1d), (value >> 0));

    return status;
}

/**
 * (NEVIS_B0) Maximum number of sample_valid IRQ generated
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1SampleClkCounterMax_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x1d), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Select the IRQ generation mode : 0=always generate sample valid IRQ to ARM, 1= generate sample valid IRQ to ARM until max counter is reached
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1SampleClkCounterSel_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1c), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS_B0) Select the IRQ generation mode : 0=always generate sample valid IRQ to ARM, 1= generate sample valid IRQ to ARM until max counter is reached
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Rx1SampleClkCounterSel_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1c), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) RXNB Fifo2mem DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbFifo2memClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x15), (value >> 0), 0x4, 0x2);

    return status;
}

/**
 * (NEVIS_B0) RXNB Fifo2mem DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbFifo2memClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x15), &register_value, 0x4, 0x2);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbFifo2memSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x19), (value >> 0), 0x4, 0x2);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbFifo2memSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x19), &register_value, 0x4, 0x2);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) RXNB Mem2fifo DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbMem2fifoClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x15), (value >> 0), 0x8, 0x3);

    return status;
}

/**
 * (NEVIS_B0) RXNB Mem2fifo DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbMem2fifoClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x15), &register_value, 0x8, 0x3);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbMem2fifoSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x19), (value >> 0), 0x8, 0x3);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbMem2fifoSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x19), &register_value, 0x8, 0x3);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Clear sample valid Max counter
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbSampleClkCounterClear_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1e), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (NEVIS_B0) Clear sample valid Max counter
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbSampleClkCounterClear_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1e), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Maximum number of sample_valid IRQ generated
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbSampleClkCounterMax_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x1f), (value >> 0));

    return status;
}

/**
 * (NEVIS_B0) Maximum number of sample_valid IRQ generated
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbSampleClkCounterMax_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x1f), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Select the IRQ generation mode : 0=always generate sample valid IRQ to ARM, 1= generate sample valid IRQ to ARM until max counter is reached
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbSampleClkCounterSel_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1e), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS_B0) Select the IRQ generation mode : 0=always generate sample valid IRQ to ARM, 1= generate sample valid IRQ to ARM until max counter is reached
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_RxnbSampleClkCounterSel_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1e), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * General purpose SW spare bits
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister0_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x0), (value >> 0));

    return status;
}

/**
 * General purpose SW spare bits
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister0_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x0), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister1_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x1), (value >> 0));

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister1_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x1), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister2_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x2), (value >> 0));

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister2_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x2), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister3_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x3), (value >> 0));

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister3_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x3), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister4_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x4), (value >> 0));

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister4_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x4), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister5_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x5), (value >> 0));

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister5_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x5), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister6_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x6), (value >> 0));

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister6_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x6), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister7_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x7), (value >> 0));

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_SwSpareRegister7_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x7), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}


static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2ClkAlignReceived_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x11), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2ClkAlignReceivedClear_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x10), (value >> 0), 0x2, 0x1);

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2ClkAlignReceivedClear_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x10), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2ClkStartClkAlign_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x10), (value >> 0), 0x1, 0x0);

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2ClkStartClkAlign_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x10), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Enable CORE_1 Regmap AHB clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2Core1AhbclkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xc), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (NEVIS) Enable CORE_1 Regmap AHB clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2Core1AhbclkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xc), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Enable CORE_1 Regmap clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2Core1RegclkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xb), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (NEVIS) Enable CORE_1 Regmap clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2Core1RegclkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xb), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Enable CORE_2 Regmap AHB clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2Core2AhbclkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xc), (value >> 0), 0x4, 0x2);

    return status;
}

/**
 * (NEVIS) Enable CORE_2 Regmap AHB clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2Core2AhbclkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xc), &register_value, 0x4, 0x2);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Enable CORE_2 Regmap clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2Core2RegclkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xb), (value >> 0), 0x4, 0x2);

    return status;
}

/**
 * (NEVIS) Enable CORE_2 Regmap clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2Core2RegclkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xb), &register_value, 0x4, 0x2);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Enable CORE Regmap AHB clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2CoreAhbclkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xc), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS) Enable CORE Regmap AHB clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2CoreAhbclkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xc), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}


static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2CoreClkAlignReceived_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x11), &register_value, 0x10, 0x4);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2CoreClkAlignReceivedClear_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x10), (value >> 0), 0x20, 0x5);

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2CoreClkAlignReceivedClear_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x10), &register_value, 0x20, 0x5);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2CoreClkStartClkAlign_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x10), (value >> 0), 0x10, 0x4);

    return status;
}

static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2CoreClkStartClkAlign_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x10), &register_value, 0x10, 0x4);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Enable CORE Regmap clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2CoreRegclkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xb), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS) Enable CORE Regmap clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2CoreRegclkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xb), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Enable RX1_CORE Regmap AHB clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2Rx1CoreAhbclkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xc), (value >> 0), 0x10, 0x4);

    return status;
}

/**
 * (NEVIS) Enable RX1_CORE Regmap AHB clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2Rx1CoreAhbclkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xc), &register_value, 0x10, 0x4);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Enable RX1_CORE Regmap clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2Rx1CoreRegclkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xb), (value >> 0), 0x10, 0x4);

    return status;
}

/**
 * (NEVIS) Enable RX1_CORE Regmap clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2Rx1CoreRegclkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xb), &register_value, 0x10, 0x4);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Enable RX_NB_CORE Regmap AHB clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2RxNbCoreAhbclkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xc), (value >> 0), 0x20, 0x5);

    return status;
}

/**
 * (NEVIS) Enable RX_NB_CORE Regmap AHB clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2RxNbCoreAhbclkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xc), &register_value, 0x20, 0x5);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Enable RX_NB_CORE Regmap clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2RxNbCoreRegclkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xb), (value >> 0), 0x20, 0x5);

    return status;
}

/**
 * (NEVIS) Enable RX_NB_CORE Regmap clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2RxNbCoreRegclkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xb), &register_value, 0x20, 0x5);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Enable TX_CORE Regmap AHB clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2TxCoreAhbclkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xc), (value >> 0), 0x8, 0x3);

    return status;
}

/**
 * (NEVIS) Enable TX_CORE Regmap AHB clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2TxCoreAhbclkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xc), &register_value, 0x8, 0x3);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Enable TX_CORE Regmap clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2TxCoreRegclkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0xb), (value >> 0), 0x8, 0x3);

    return status;
}

/**
 * (NEVIS) Enable TX_CORE Regmap clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Sys2TxCoreRegclkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0xb), &register_value, 0x8, 0x3);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) TX1 Fifo2mem DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Tx1Fifo2memClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x15), (value >> 0), 0x10, 0x4);

    return status;
}

/**
 * (NEVIS_B0) TX1 Fifo2mem DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Tx1Fifo2memClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x15), &register_value, 0x10, 0x4);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Tx1Fifo2memSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x19), (value >> 0), 0x10, 0x4);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Tx1Fifo2memSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x19), &register_value, 0x10, 0x4);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) TX1 Mem2fifo DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Tx1Mem2fifoClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x15), (value >> 0), 0x20, 0x5);

    return status;
}

/**
 * (NEVIS_B0) TX1 Mem2fifo DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Tx1Mem2fifoClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x15), &register_value, 0x20, 0x5);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Tx1Mem2fifoSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x19), (value >> 0), 0x20, 0x5);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Tx1Mem2fifoSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x19), &register_value, 0x20, 0x5);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) TX1 ssi2mem DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Tx1Ssi2memClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x15), (value >> 0), 0x40, 0x6);

    return status;
}

/**
 * (NEVIS_B0) TX1 ssi2mem DMA clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Tx1Ssi2memClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x15), &register_value, 0x40, 0x6);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Tx1Ssi2memSwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x19), (value >> 0), 0x40, 0x6);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Tx1Ssi2memSwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x19), &register_value, 0x40, 0x6);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Clear sample valid Max counter
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_TxSampleClkCounterClear_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x20), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (NEVIS_B0) Clear sample valid Max counter
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_TxSampleClkCounterClear_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x20), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Maximum number of sample_valid IRQ generated
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_TxSampleClkCounterMax_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x21), (value >> 0));

    return status;
}

/**
 * (NEVIS_B0) Maximum number of sample_valid IRQ generated
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_TxSampleClkCounterMax_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x21), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Select the IRQ generation mode : 0=always generate sample valid IRQ to ARM, 1= generate sample valid IRQ to ARM until max counter is reached
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_TxSampleClkCounterSel_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x20), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS_B0) Select the IRQ generation mode : 0=always generate sample valid IRQ to ARM, 1= generate sample valid IRQ to ARM until max counter is reached
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_TxSampleClkCounterSel_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x20), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) UART1 clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Uart1ClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x17), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS_B0) UART1 clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Uart1ClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x17), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Uart1SwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1b), (value >> 0), 0x1, 0x0);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Uart1SwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1b), &register_value, 0x1, 0x0);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) UART2 clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Uart2ClkEn_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x17), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (NEVIS_B0) UART2 clock Enable
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Uart2ClkEn_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x17), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Uart2SwReset_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Field_Write(device, (0x4200 + 0x1b), (value >> 0), 0x2, 0x1);

    return status;
}

/**
 * (NEVIS_B0) Enable Software Reset
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_Uart2SwReset_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Field_Read(device, (0x4200 + 0x1b), &register_value, 0x2, 0x1);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}

/**
 * (NEVIS) Divider value for UART clock from ARM clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_UartClkDivValue_Set(void *const device,
    const uint8_t value)
{
    int32_t status = 0;

    status = adi_bf_hal_Register_Write(device, (0x4200 + 0x13), (value >> 0));

    return status;
}

/**
 * (NEVIS) Divider value for UART clock from ARM clock
 */
static inline int32_t adrv910x_NevisSys2RegmapCore1_UartClkDivValue_Get(void *const device,
    uint8_t *const value)
{
    int32_t status = 0;
    uint8_t register_value = 0;

    status = adi_bf_hal_Register_Read(device, (0x4200 + 0x13), &register_value);
    *value = 0;
    *value = (*value << 8) | register_value;

    return status;
}


#endif // __ADRV910X_BF_NEVIS_SYS2_REGMAP_CORE_1_H__