CONFIG_XILINX_HDL_DESIGN="cn0561"
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_PWM=y
CONFIG_ADC=y
CONFIG_ADC_AD713X=y
CONFIG_AXI_CORE=y
CONFIG_AXI_CORE_SPI_ENGINE=y
CONFIG_AXI_CORE_AXI_DMAC=y
CONFIG_AXI_CORE_AXI_PWMGEN=y
CONFIG_AXI_CORE_CLK_AXI_CLKGEN=y
CONFIG_CN0561_UART_EXAMPLE=y
CONFIG_CN0561_CORAZ7S_CARRIER=y
