## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/ad9265_fmc/zc706/ad9265_fmc_zc706.sdk/system_top.hdf

include $(NOOS-DIR)/ad9265-fmc-125ebz/ad9265_fmc_125ebz.mk
include $(NOOS-DIR)/scripts/zynq_ps7.mk
