# Select the example you want to enable by chossing y for enabling and n for disabling
DUMMY_EXAMPLE = n
IIO_EXAMPLE = y
IIO_TRIGGER_EXAMPLE = n

PLATFORM = maxim
TARGET = max32650

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
