# Select the example you want to enable by chossing y for enabling and n for disabling
DUMMY_EXAMPLE = n
IIO_EXAMPLE = n
IIO_TRIGGER_EXAMPLE = y

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
