## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/fmcadc4/zc706/fmcadc4_zc706.sdk/system_top.hdf

include $(NOOS-DIR)/ad-fmcadc4-ebz/ad_fmcadc4_ebz.mk
include $(NOOS-DIR)/scripts/zynq.mk

