## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/ad9739a_fmc/zc706/ad9739a_fmc_zc706.sdk/system_top.hdf

include $(NOOS-DIR)/ad9739a-fmc-ebz/ad9739a_fmc_ebz.mk
include $(NOOS-DIR)/scripts/zynq_ps7.mk

