SRCS += $(PLATFORM_DRIVERS)/$(PLATFORM)_delay.c \
	$(PLATFORM_DRIVERS)/$(PLATFORM)_irq.c	\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_spi.c	\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_uart.c

INCS +=	$(PLATFORM_DRIVERS)/$(PLATFORM)_irq.h	\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_spi.h	\
	$(PLATFORM_DRIVERS)/$(PLATFORM)_uart.h
