CONFIG_UART=y
CONFIG_IRQ=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_DMA=y
CONFIG_TIMER=y
CONFIG_TRNG=y
CONFIG_RTC=y
CONFIG_MQTT=y
CONFIG_MBEDTLS=y
CONFIG_MBEDTLS_CONFIG_FILE="projects/eval-ade9430/src/examples/iot_example/noos_mbedtls_config.h"
CONFIG_AZURE=y
CONFIG_RTC_DRIVERS=y
CONFIG_RTC_DRIVERS_PCF85263=y
CONFIG_METER=y
CONFIG_METER_ADE9430=y
CONFIG_EVAL_ADE9430_IOT_EXAMPLE=y
CONFIG_EVAL_ADE9430_IOT_AZURE=y
