################################################################################
#
# Makefile for the max20362 project
#
################################################################################

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
