CONFIG_UART=y
CONFIG_IRQ=y
CONFIG_GPIO=y
CONFIG_SPI=y
CONFIG_I2C=y
CONFIG_DMA=y
CONFIG_TIMER=y
CONFIG_IIO=y
CONFIG_LVGL=y
CONFIG_LVGL_VERSION="v9.3.0"
CONFIG_LVGL_CONF_PATH="projects/eval-powrms"
CONFIG_DISPLAY=y
CONFIG_DISPLAY_SSD1306=y
CONFIG_ADC=y
CONFIG_ADC_AD7091R5=y
CONFIG_EEPROM=y
CONFIG_EEPROM_DRIVERS=y
CONFIG_EEPROM_DRIVERS_M24512=y
CONFIG_EVAL_POWRMS_EXAMPLE_EXAMPLE=y
