## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/fmcadc4/zc706/fmcadc4_zc706.sdk/system_top.hdf

include $(NOOS-DIR)/fmcadc4/fmcadc4.mk
include $(NOOS-DIR)/scripts/zynq_ps7.mk

