CONFIG_UART=y
CONFIG_UART_STM32=y
CONFIG_UART_STDIO_STM32=y
CONFIG_I2C=y
CONFIG_I2C_STM32=y
CONFIG_GPIO=y
CONFIG_GPIO_STM32=y
CONFIG_GPIO_IRQ_STM32=y
CONFIG_IRQ=y
CONFIG_IRQ_STM32=y
CONFIG_POWER=y
CONFIG_POWER_LTM3360B=y
CONFIG_LTM3360B_BASIC_EXAMPLE=y
