PLATFORM = mbed

# Choose the default example to build
EXAMPLE ?= iio_example


include ../../tools/scripts/generic_variables.mk

include ../../tools/scripts/examples.mk

include src.mk

include ../../tools/scripts/generic.mk
