# Select the example you want to enable by chossing y for enabling and n for disabling
IIO_EXAMPLE = y
IIO_TRIGGER_EXAMPLE = n

include ../../tools/scripts/generic_variables.mk

include src.mk

include ../../tools/scripts/generic.mk
