CONFIG_XILINX_HDL_DESIGN="adaq8092_fmc"
CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_IRQ=y
CONFIG_UART=y
CONFIG_IIO=y
CONFIG_ADC=y
CONFIG_ADC_ADAQ8092=y
CONFIG_AXI_CORE=y
CONFIG_AXI_CORE_AXI_ADC_CORE=y
CONFIG_AXI_CORE_AXI_DMAC=y
CONFIG_AXI_CORE_IIO_AXI_ADC=y
CONFIG_ADAQ8092_FMC_IIO_EXAMPLE=y
