## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/daq3/kcu105/daq3_kcu105.sdk/system_top.hdf

include $(NOOS-DIR)/fmcdaq3/fmcdaq3.mk
include $(NOOS-DIR)/scripts/microblaze.mk

