name: Build projects for Pico platform

on:
  pull_request:
    branches:
      - main
      - next_stable
      - 'release/*'
      - '20*'
    paths-ignore:
      - '**/*.rst'
      - '**/*.md'
      - 'drivers/platform/stm32/**'
      - 'drivers/platform/xilinx/**'
      - 'drivers/platform/aducm3029/**'
      - 'drivers/platform/maxim/**'
      - '.github/config/**'
      - '.github/scripts/**'
      - '.github/workflows/build-xilinx-platform.yaml'
      - '.github/workflows/build-maxim-platform.yaml'
      - '.github/workflows/build-aducm3029-platform.yaml'
      - '.github/workflows/build-stm32-platform.yaml'
      - '.github/workflows/build-common.yaml'
      - '.github/workflows/deploy-docs.yaml'
  push:
    branches:
      - main
      - next_stable
      - 'release/*'
      - '20*'
    paths-ignore:
      - '**/*.rst'
      - '**/*.md'
      - 'drivers/platform/stm32/**'
      - 'drivers/platform/xilinx/**'
      - 'drivers/platform/aducm3029/**'
      - 'drivers/platform/maxim/**'
      - '.github/config/**'
      - '.github/scripts/**'
      - '.github/workflows/build-xilinx-platform.yaml'
      - '.github/workflows/build-maxim-platform.yaml'
      - '.github/workflows/build-aducm3029-platform.yaml'
      - '.github/workflows/build-stm32-platform.yaml'
      - '.github/workflows/build-common.yaml'
      - '.github/workflows/deploy-docs.yaml'
  pull_request_target:
    branches:
      - main
      - next_stable
      - 'release/*'
      - '20*'
    paths-ignore:
      - '**/*.rst'
      - '**/*.md'
      - 'drivers/platform/stm32/**'
      - 'drivers/platform/pico/**'
      - 'drivers/platform/aducm3029/**'
      - 'drivers/platform/maxim/**'
      - '.github/config/**'
      - '.github/scripts/**'
      - '.github/workflows/build-xilinx-platform.yaml'
      - '.github/workflows/build-maxim-platform.yaml'
      - '.github/workflows/build-aducm3029-platform.yaml'
      - '.github/workflows/build-stm32-platform.yaml'
      - '.github/workflows/build-common.yaml'
      - '.github/workflows/deploy-docs.yaml'

permissions:
  contents: read
  id-token: write
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-pico-projects:
    if: |
      github.event_name != 'pull_request' ||
      github.event.pull_request.head.repo.full_name == github.repository
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      TOOLS_REPO: ${{ secrets.TOOLS_REPO }}
      BLACKLIST_URL: ${{ secrets.BLACKLIST_URL }}
      HDL_BRANCH: 'main'
      BUILDS_DIR: ${{ github.workspace }}/builds
      RELEASES_DIR: ${{ github.workspace }}/latest_build
      LOGS_DIR: ${{ github.workspace }}/logs
      PICO_SDK_PATH: ${{ github.workspace }}/libraries/pico-sdk
    container:
      image: ${{ vars.DOCKER_REGISTRY }}/pico-platform:latest
      credentials:
        username: ${{ secrets.CLOUDSMITH_USER }}
        password: ${{ secrets.CLOUDSMITH_API_KEY }}
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: recursive
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Building for platform Pico
        shell: sh
        run: |
          echo "Setup cloudsmith helper ..."
          wget https://raw.githubusercontent.com/analogdevicesinc/wiki-scripts/refs/heads/main/utils/cloudsmith_utils/cloudsmith_helper.py \
            -O ./tools/scripts/cloudsmith_temp.py
          cat tools/scripts/cloudsmith_temp.py | sed 's#/usr/bin/python3#/usr/bin/env python3#' > tools/scripts/cloudsmith_helper.py
          rm tools/scripts/cloudsmith_temp.py

          echo "Running project build ..."
          ${{ github.workspace }}/tools/scripts/build_projects.py \
            ${{ github.workspace }} \
            -export_dir ${{ env.RELEASES_DIR }} \
            -log_dir ${{ env.LOGS_DIR }} \
            -builds_dir ${{ env.BUILDS_DIR }} \
            -platform pico \
            -hdl_branch ${{ env.HDL_BRANCH }}
        env:
          CLOUDSMITH_API_KEY: ${{ env.CLOUDSMITH_API_KEY }}
          TOKEN: ${{ secrets.GH_GHDL_TOKEN }}
      - name: Upload artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.RELEASES_DIR }}
          name: ${{ github.job }}-binaries
      - name: Upload logs artifact
        if: always()
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.LOGS_DIR }}
          name: ${{ github.job }}-logs
