name: Build Xilinx platform

on:
  pull_request:
    branches:
      - main
      - next_stable
      - release
      - '20*'
    paths-ignore:
      - '**/*.rst'
      - '**/*.md'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.rst'
      - '**/*.md'

permissions:
  contents: read
  id-token: write
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-xilinx-platform:
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      TOOLS_REPO: ${{ secrets.TOOLS_REPO }}
      BLACKLIST_URL: ${{ secrets.BLACKLIST_URL }}
      HDL_BRANCH: 'main'
      BRANCH: 'main'
      BUILDS_DIR: ${{ github.workspace }}/builds
      RELEASES_DIR: ${{ github.workspace }}/latest_build
      LOGS_DIR: ${{ github.workspace }}/logs
    runs-on: noos-runner-xilinx
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: false
      - name: Setup Xilinx platform env
        shell: sh
        run: |
          ${{ github.workspace }}/.github/scripts/setup-platform-env.sh
        env:
          PLATFORM: xilinx
          WORKSPACE: ${{ github.workspace }}
      - name: Build Xilinx projects
        shell: sh
        run: |
          echo "Setup cloudsmith helper ..."
          wget -P ./tools/scripts/ \
            https://raw.githubusercontent.com/analogdevicesinc/wiki-scripts/refs/heads/main/utils/cloudsmith_utils/cloudsmith_helper.py -O ./tools/scripts/cloudsmith_temp.py
          cat tools/scripts/cloudsmith_temp.py | sed 's#/usr/bin/python3#/usr/bin/env python3#' > tools/scripts/cloudsmith_helper.py
          
          echo "Running project build ..."
          ${{ github.workspace }}/tools/scripts/build_projects.py \
            ${{ github.workspace }} \
            -export_dir ${{ env.RELEASES_DIR }} \
            -log_dir ${{ env.LOGS_DIR }} \
            -builds_dir ${{ env.BUILDS_DIR }} \
            -platform xilinx \
            -hdl_branch ${{ env.HDL_BRANCH }}
        env:
          CLOUDSMITH_API_KEY: ${{ env.CLOUDSMITH_API_KEY }}
          TOKEN: ${{ secrets.GH_GHDL_TOKEN }}
      - name: Upload Xilinx artifacts
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.RELEASES_DIR }}
          name: release_xilinx_${{ github.job }}
      - name: Upload Xilinx build logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.LOGS_DIR }}
          name: logs_xilinx_${{ github.job }}
      - name: Remove logs, new_hardware and release output
        shell: sh
        run: |
          rm -rf ${{ env.RELEASES_DIR }} ${{ env.LOGS_DIR }} ${{ env.BUILDS_DIR }}_${{ env.HDL_BRANCH }}/new_hardware
