name: Build projects for Xilinx platform

on:
  pull_request:
    branches:
      - main
      - next_stable
      - 'release/*'
      - '20*'
    paths-ignore:
      - '**/*.rst'
      - '**/*.md'
      - 'drivers/platform/stm32/**'
      - 'drivers/platform/pico/**'
      - 'drivers/platform/aducm3029/**'
      - 'drivers/platform/maxim/**'
      - '.github/config/**'
      - '.github/scripts/**'
      - '.github/workflows/build-pico-platform.yaml'
      - '.github/workflows/build-maxim-platform.yaml'
      - '.github/workflows/build-aducm3029-platform.yaml'
      - '.github/workflows/build-stm32-platform.yaml'
      - '.github/workflows/build-common.yaml'
      - '.github/workflows/deploy-docs.yaml'
  push:
    branches:
      - main
      - next_stable
      - 'release/*'
      - '20*'
    paths-ignore:
      - '**/*.rst'
      - '**/*.md'
      - 'drivers/platform/stm32/**'
      - 'drivers/platform/pico/**'
      - 'drivers/platform/aducm3029/**'
      - 'drivers/platform/maxim/**'
      - '.github/config/**'
      - '.github/scripts/**'
      - '.github/workflows/build-pico-platform.yaml'
      - '.github/workflows/build-maxim-platform.yaml'
      - '.github/workflows/build-aducm3029-platform.yaml'
      - '.github/workflows/build-stm32-platform.yaml'
      - '.github/workflows/build-common.yaml'
      - '.github/workflows/deploy-docs.yaml'

permissions:
  contents: read
  id-token: write
  checks: write
  pull-requests: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  build-xilinx-projects:
    # TEST
    continue-on-error: true
    strategy:
      matrix:
        runs-on: [noos-runner-xilinx-test, noos-runner-xilinx-test, noos-runner-xilinx-test, noos-runner-xilinx-test]
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
      TOOLS_REPO: ${{ secrets.TOOLS_REPO }}
      BLACKLIST_URL: ${{ secrets.BLACKLIST_URL }}
      HDL_BRANCH: 'main'
      BRANCH: ${{ github.event_name == 'pull_request' && github.base_ref || github.ref_name }}
      BUILDS_DIR: ${{ secrets.PRIVATE_WORKSPACE }}/builds
      RELEASES_DIR: ${{ github.workspace }}/latest_build
      LOGS_DIR: ${{ github.workspace }}/logs
      NO_OS_CACHE_DIR: ${{ github.workspace }}/deps_cache
    # TEST
    runs-on: ${{ matrix.runs-on }}
    timeout-minutes: 600
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: false
          clean: false
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@9426d40962ed5378910ee2e21d5f8c6fcbf2dd96 # v47.0.6
      - name: Get changed projects
        id: projects-list
        shell: sh
        run: |
          ${{ github.workspace }}/.github/scripts/get-changed-projects.sh
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
      - name: Building for platform Xilinx 
        shell: sh
        run: |
          ${{ github.workspace }}/.github/scripts/build-projects.sh
        env:
          WORKSPACE: ${{ github.workspace }}
          PLATFORM: xilinx
          CLOUDSMITH_API_KEY: ${{ env.CLOUDSMITH_API_KEY }}
          TOKEN: ${{ secrets.GH_GHDL_TOKEN }}
          PROJECTS: ${{ steps.projects-list.outputs.projects }}
      - name: Upload Xilinx artifacts
        if: always()
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.RELEASES_DIR }}
          name: ${{ github.job }}-binaries
      - name: Upload Xilinx build logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          path: ${{ env.LOGS_DIR }}
          name: ${{ github.job }}-logs
      - name: Remove logs, release output and lockfile
        if: always()
        shell: bash
        run: |
          rm -rf ${{ env.RELEASES_DIR }} ${{ env.LOGS_DIR }}
          if [[ "${{ job.status }}" == "cancelled" ]]; then
            lockfile=$(find ${{ github.workspace }}/ -maxdepth 1 | grep ".lock" | sed 's:.*/::')
            if [[ ! -z "$lockfile" ]]; then
              rm -rf ${{ env.BUILDS_DIR }}_${{ env.HDL_BRANCH }}_cmake/$lockfile ${{ github.workspace }}/$lockfile
            fi
          fi
