## Makefile

include ../../scripts/noos.mk

M_HDF_FILE := $(HDL-DIR)/projects/daq2/vc707/daq2_vc707.sdk/system_top.hdf

include $(NOOS-DIR)/fmcdaq2/fmcdaq2.mk
include $(NOOS-DIR)/scripts/microblaze.mk

