PLATFORM ?= maxim
TARGET ?= max32670
EXAMPLE ?= basic_init_2devices

include ../../tools/scripts/generic_variables.mk
include ../../tools/scripts/examples.mk
include src.mk
include ../../tools/scripts/generic.mk
